### ISSUE TITLE
"key too large to index" reloaded

### ISSUE THREAD

**Issue by svoop** [errbit/errbit#1001]
This seems to be related to #848.

I sometimes get the following Mongo::Error::OperationFailure:

> Mongo::Error::OperationFailure: exception: insertDocument :: caused by :: 17280 Btree::insert: key too large to index, failing errbit_production.problems.$message_1 1656 { : "ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR: syntax error at or near "AND" LINE 1: ...LECT "areas".* FROM "areas" WHERE "areas"."id" = AN..." } (17280)

The backtrace shows:

    app/models/problem.rb:85→ cache_notice
    app/models/error_report.rb:78→ cache_attributes_on_problem
    app/models/error_report.rb:56→ generate_notice!
    app/controllers/notices_controller.rb:15→ create

Which points to this code:

    Problem.where('_id' => id).find_one_and_update({
      '$set' => {
        'environment'                            => notice.environment_name,
        'error_class'                            => notice.error_class,
        'last_notice_at'                         => notice.created_at.utc,
        'message'                                => notice.message,
        'resolved'                               => false,
        'resolved_at'                            => nil,
        'where'                                  => notice.where,
        "messages.#{message_digest}.value"       => notice.message,
        "hosts.#{host_digest}.value"             => notice.host,
        "user_agents.#{user_agent_digest}.value" => notice.user_agent_string
      },
      '$inc' => {
        'notices_count'                          => 1,
        "messages.#{message_digest}.count"       => 1,
        "hosts.#{host_digest}.count"             => 1,
        "user_agents.#{user_agent_digest}.count" => 1
      }
    }, return_document: :after)

Shouldn't the `before_save :truncate_message` callback from #848 prevent this?

My install is on commit c5393af

**Comment by stevecrozz** [comment]
Good catch. I think the optimizations I made here actually bypass the before_save hooks. We'll need to apply the same fix here.

**Comment by stevecrozz** [comment]
@svoop Should be resolved now
