### ISSUE TITLE
Layout broken when Apps name is too long

### ISSUE THREAD

**Issue by YoHarmonica** [errbit/errbit#1011]
It seemed that when the App name is too long, it break the layout.
![break](https://cloud.githubusercontent.com/assets/10822260/11921623/b94c90a6-a7cf-11e5-94d9-0897400defbb.png)
with long name, the layout is broken.

![no_break](https://cloud.githubusercontent.com/assets/10822260/11921625/c3131ed4-a7cf-11e5-8b48-093be02f8eec.png)
when the name is renamed to shorter one, the layout looked fine.

I haven't tried to tinkering the CSS so I didn't know what had caused that.

**Comment by stevecrozz** [comment]
Yeah, I've noticed this but never bothered to get it fixed. Now its on the hit list for 0.6.0. Thanks for the report.

**Comment by YoHarmonica** [comment]
@stevecrozz 

Thanks for the quick response!

**Comment by stevecrozz** [comment]
@YoHarmonica Can you give this a try and report back on how it works for you?
https://github.com/errbit/errbit/pull/1022

**Comment by stevecrozz** [comment]
I believe this is solved.
