### ISSUE TITLE
airbrake gem v5 has been released. Complete rewrite

### ISSUE THREAD

**Issue by tmaier** [errbit/errbit#1012]
[airbrake v5](https://rubygems.org/gems/airbrake) is complete rewrite of the gem.

* The namings of all keys has been changed
* Airbrake expects now a `project_id` and a `project_key` (the former `api_key`)

```ruby
Airbrake.configure do |c|
  c.project_id = 113743
  c.project_key = 'fd04e13d806a90f96614ad8e529b2822'
end
```

Migration guide: https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md

* errbit should be adapted and tested for that new version
* the [configuration instructions](https://github.com/errbit/errbit/blob/8cf20c3e4b612b23f643d9c3517e635f4636fb3c/app/views/apps/_configuration_instructions.html.haml) require an update

**Comment by stevecrozz** [comment]
It looks like the new notifier still uses the v3 API which is already supported by Errbit since it's also used by airbrake-js. But there's bound to be something we haven't accounted for so we should look into this a bit.

**Comment by stevecrozz** [comment]
The changes seemed pretty simple. I tested this approach and it worked for me. Let me know if you have any issues with it.

**Comment by svoop** [comment]
@stevecrozz 

I'm a little puzzled when it comes to the reporting of the current user. The https://airbrake.io/docs (create notice v3) seem to be inconsistent. The "JSON example" looks as follows:

    "context": {
      "userId": "12345",
      "userName": "root",
      "userEmail": "root@root.com"
    }

But the "POST data fields v3" description states:

    context/user/id 	false 	If applicable, the current user’s ID.
    context/user/name 	false 	If applicable, the current user’s username.
    context/user/email 	false 	If applicable, the current user’s email address.

The v5 gem apparently sends the user the latter way which appears not yet to be supported by Errbit.

**Comment by stevecrozz** [comment]
Yeah. It seems like they change the API, and from what I gather they don't give it a new version as long as airbrake (the platform) remains backwards compatible. We should probably support both formats for user info. I'll make a ticket for that.

**Comment by ronwsmith** [comment]
Didn't think this question was worthy of a new 'issue', so I'm hoping it can sneak in to this relevant one:

For `project_id`, I assume we can just put in anything?

**Comment by stevecrozz** [comment]
@ronwsmith That does seem to be the case. It just can't be false or nil.
