### ISSUE TITLE
Notice for old app version ignored

### ISSUE THREAD

**Issue by StickyBros** [errbit/errbit#1024]
Hi there,

I'm trying to get airbrake-js v0.5.8 to work with errbit 0.5.0 (I also tried building the head of the master branch with the same results)

My code looks like:

```
const AirbrakeClient = require('airbrake-js');
const airbrake = new AirbrakeClient();
airbrake.setHost('http://192.168.99.100:5000');
airbrake.setProject('105cd6c8fb856...', '105cd6c8fb856...');
airbrake.notify({error: {message: 'test'}});
``` 

My app is running on localhost, so the request is going cross-domain.  I'm guessing because the response body isn't JSON it causes another error which triggers airbrake to send another request which causes an infinite loop of these:

Request

```
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Content-Length:689
Content-Type:text/plain;charset=UTF-8
Host:192.168.99.100:5000
Origin:http://localhost:8000
Pragma:no-cache
Referer:http://localhost:8000/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2604.0 Safari/537.36
```

What I get back is:

```
Access-Control-Allow-Headers:origin, content-type, accept
Access-Control-Allow-Origin:*
Cache-Control:max-age=0, private, must-revalidate
Connection:close
Content-Encoding:gzip
Content-Type:text/html; charset=utf-8
Date:Tue, 05 Jan 2016 21:04:41 GMT
ETag:W/"d75e9c79cd8a749c7fc2094f74d81a36"
Status:200 OK
Vary:Accept-Encoding
X-Content-Type-Options:nosniff
X-Frame-Options:SAMEORIGIN
X-Request-Id:ac075876-6574-4c69-a529-37fc323ca577
X-Runtime:0.004290
X-XSS-Protection:1; mode=block
```

with the body

```
Notice for old app version ignored
```

**Comment by stevecrozz** [comment]
It looks like we have some code that's intending to reject error notifications for old versions. Can you check to see what you have set for LATEST APP VERSION for this Errbit app? If I understand the intent correctly, you'll need to pass a newer app version in the notification than the one you have set in your Errbit app.

**Comment by StickyBros** [comment]
Ah, good catch.

The version on the server was set to 1.0.0.  (How do you change this, btw?)

By adding the following code it works now:

```
airbrake.addFilter((notice) => {
  notice.context.version = '1.0.0';
  return notice;
});
```

Thanks!

**Comment by stevecrozz** [comment]
You can change that field by editing the app in the Errrbit UI. Can you contribute any more information about this infinite loop you observed? I'd like to get that fixed if there is one.

**Comment by StickyBros** [comment]
Sure.  The console produced tons of these:

```
VM6299:1 Uncaught SyntaxError: Unexpected token N
req.onreadystatechange @ xhr.js:16
```

From looking in xhr.js, line 16 is:
``` 
        resp = JSON.parse(req.responseText);
```

So yeah, it blindly parses the response which in this case isn't JSON.  That throws an error and hence the infinite loop.

**Comment by stevecrozz** [comment]
This is confusing to me because it should only be doing this when the response code is 201 according to to the source code I'm reading: https://github.com/airbrake/airbrake-js/blob/v0.5.8/src/reporters/xhr.coffee#L13 and the response code from Errbit is 200. Although now I'm seeing https://github.com/airbrake/airbrake-js/blob/v0.5.8/src/reporters/compat.coffee which does parse on a 200 response and now I'm confused about which reporter is typically used by airbrake-js. I guess I have some studying to do.

**Comment by stevecrozz** [comment]
On closer inspection, it looks like compat is the one that is in use by airbrake-js. There's no documentation on using the xhr reporter or any indication that anyone uses it, so this makes sense to me now. I'll add a commit to return a status code in the 4xx range when encountering this error so we avoid the infinite error loop.
