### ISSUE TITLE
multiple format compatibility for user information

### ISSUE THREAD

**Issue by stevecrozz** [errbit/errbit#1026]
As @svoop points out in #1012, airbrake is makeing changes to their API clients around user information. Because airbrake changes their API fairly regularly, we need to update Errbit to accept new notice formats as they appear while still supporting the old notice format. We need to support user information that looks like this:
```
"context": {
  "userId": "12345",
  "userName": "root",
  "userEmail": "root@root.com"
}
```
and like this:
```
"context": {
  "user": {
    "id": "12345",
    "name": "root",
    "email": "root@root.com"
  }
}
```

**Comment by svoop** [comment]
I could help with that, however, most likely not before next week since I'm still on the road.

**Comment by stevecrozz** [comment]
Awesome. I'll take all the help I can get.

**Comment by stevecrozz** [comment]
Looks good to me.

I added a PR to your PR which I think is a simplification of the old user data handling:
https://github.com/svoop/errbit/pull/1

Your logic did work and it was awesomely compact, but I was having trouble reading it. I hope you don't mind. Let me know if you spot anything wrong. If it all looks good, then this is ready to go.

**Comment by svoop** [comment]
@stevecrozz You're right, the old format was parsed in a very clever yet not very readable manner, I've only added the mnemonic-style block to it. However, it had one advantage: Special cases such as `context['userCity']` were parsed as well, but I doubt such cases exist. And even if, upping to the v5 gem brings this feature back. I've merged your PR, thanks for merging mine :smile:

**Comment by stevecrozz** [comment]
Great! One more issue squashed!
