### ISSUE TITLE
Has version 0.6.0 been done and released?

### ISSUE THREAD

**Issue by kimrgrey** [errbit/errbit#1031]
All issues in milestone for this version has been closed, but I can't find appropriate tag in repository. This question is very important for me, because I want to upgrade airbrake gem in my application to latest version and some known bugs with it were fixed in 0.6.0.

**Comment by stevecrozz** [comment]
Ready to go. I just needed to create and push the v0.6.0 tag (https://github.com/errbit/errbit/tree/v0.6.0).

**Comment by kimrgrey** [comment]
Cool! And thank you very much for such great software, by the way :+1:

**Comment by stevecrozz** [comment]
No prob! I love doing this and it's fun for me to hear from others who use Errbit.
