### ISSUE TITLE
My Errbit instance is filling with "NoMethodError" undefined method `call' for nil:NilClass errors

### ISSUE THREAD

**Issue by zedalaye** [errbit/errbit#1034]
These errors have no origin, no backtrace, no environment, no parameter and no session and they occur every ~20 minutes.

I don't know if they are due to the Airbrake 5+ gem or to errbit

My version of errbit is 8c1057943f79132aec23f0fff7d6d7d6aebfede7

**Comment by zedalaye** [comment]
I found that in my production.log :

**Comment by stevecrozz** [comment]
These appear to be errors from another application that are being sent to errbit. It could be a problem with the airbrake gem, or it could be a problem with your application. I would guess that more information should be available in your application logs, but I'm not sure. Have you already checked there?

**Comment by zedalaye** [comment]
Sure. I checked all production.log files (the Errbit one and the other applications ones) with no luck.

**Comment by rickclare** [comment]
Are you using Passenger as your app-server? There is an upcoming fix (Passenger v5.0.24) which should result this:  https://github.com/phusion/passenger/issues/1730

**Comment by zedalaye** [comment]
Yes. I use Passenger. I'll wait for the fix to be available in production. Many thanks.
