### ISSUE TITLE
Errbit ist not sending out Error-Notification-Mails

### ISSUE THREAD

**Issue by maxigs** [errbit/errbit#1038]
I have a working Errbit installation running but can't get it to send out error-notifications.

Other emails, like passwort reminders work fine, so i assume the mail setup in general is fine.

Incoming errors are tracked as they should be, so here everything seems to be fine too.

I have set all the checkboxes for errors to send out notifications, but still don't get any:

<img width="323" alt="screen shot 2016-01-30 at 09 52 24" src="https://cloud.githubusercontent.com/assets/13007/12694713/300339c6-c737-11e5-8667-0466ee556d02.png">

There is no errors or anything in the logs either.

I'm out of ideas where to look to get this working, without starting to take apart the errbit code and stuff in debug puts to see what is going on.
Any clue what i could look into?

**Comment by stevecrozz** [comment]
My only thought right now is the configuration of ERRBIT_NOTIFY_AT_NOTICES. Is it set to '[0]' as described in https://github.com/errbit/errbit/blob/master/docs/configuration.md ?

**Comment by maxigs** [comment]
Thank you Steve, this was really it.

I set `ERRBIT_NOTIFY_AT_NOTICES` to the same value as `ERRBIT_EMAIL_AT_NOTICES`.
Both are `[1,10,100]` now and it works fine.

**Comment by stevecrozz** [comment]
Excellent!
