### ISSUE TITLE
Aribrake expects 201 Created from notices API

### ISSUE THREAD

**Issue by kimrgrey** [errbit/errbit#1042]
As described in documentation here: https://airbrake.io/docs/#create-notice-v3, - Airbrake expects 201 Created response when error was successfully registered. 

![screen shot 2016-02-04 at 03 03 12](https://cloud.githubusercontent.com/assets/855918/12801220/e77a0762-caeb-11e5-91eb-8d7a033850cc.png)

But Errbit returns 200 OK here: https://git.io/vgOsU. And it makes latest airbrake gem a little bit sad:

![screen shot 2016-02-04 at 03 04 23](https://cloud.githubusercontent.com/assets/855918/12801255/39483d16-caec-11e5-8d1b-fa82b0bb4cab.png)

I'm not sure that it is a bug, because correct behaviour was changed purposely by this commit just a few days ago: https://github.com/errbit/errbit/commit/7b12c407a7bb936fb1d9cd8c9920bc5b2f761026. So, may be something wrong with our app configuration? Or it's a bug?

**Comment by stevecrozz** [comment]
Thanks. This should be fixed with: https://github.com/errbit/errbit/pull/1041

**Comment by kimrgrey** [comment]
@stevecrozz, cool, thank you for a fast response. Are you going to release a minor version with this fix? It would be awesome, because it's not very comfortable to have such error in production ^_^

**Comment by stevecrozz** [comment]
I wasn't planning on it, but I will if you need a version number in order to deploy this fix. Can you refer to the current Sha1 with the fix instead for your deployment? https://github.com/errbit/errbit/commit/a0929bc86efafc3536b97c818b540d8173842326

**Comment by kimrgrey** [comment]
Oh, sad news... :disappointed:  But why not? This is a bug, it was fixed... You can just release a v0.6.1. Isn't? 

Well, sure, I can use a maser version or a commit hash, but it always better to have a released version instead if something was fixed just to let people know, that something was broken. 

But it's up to you, of course. May be I'm wrong... Thank you again!

**Comment by stevecrozz** [comment]
Sure, I can do it. Let's see if anything shakes out from https://github.com/errbit/errbit/pull/1041 first. Apparently there's at least one official airbrake client that was expecting a 200 OK response.

**Comment by stevecrozz** [comment]
I released v0.6.1 just for you @kimrgrey :) It includes the correct response status code for the v3 notices API.

**Comment by kimrgrey** [comment]
You are so kind :smile: Thanks! I'll try to do my best to return this debt :smile:
