### ISSUE TITLE
minor problem with problem table view

### ISSUE THREAD

**Issue by mfrederickson** [errbit/errbit#1051]
It seems to possibly be short a colspan or something...
![image](https://cloud.githubusercontent.com/assets/473165/13193900/bf88450e-d72d-11e5-9199-d78bc3b5df6f.png)
... not to mention that fact that the table is extending beyond it's "container".

**Comment by mfrederickson** [comment]
@stevecrozz this is solved in my bootstrap-ui branch, if you're interested in that.

**Comment by stevecrozz** [comment]
This appears to have been resolved in #1217
