### ISSUE TITLE
user validation messages duplicated

### ISSUE THREAD

**Issue by mfrederickson** [errbit/errbit#1057]
![image](https://cloud.githubusercontent.com/assets/473165/13198959/6540abcc-d7c3-11e5-94c6-5b7aa8df7a89.png)

**Comment by mfrederickson** [comment]
@stevecrozz this one is also solved in my bootstrap-ui branch, if you're interested in that.

**Comment by stevecrozz** [comment]
I am interested :)

What's the status of your bootstrap-ui branch? Is it something you're aiming to bring upstream? It looks like you've been putting in some solid effort over there and you obviously have an eye for detail. I'm excited to see it whenever you think its ready for a look.

**Comment by mfrederickson** [comment]
It's ready.  I was going to create a PR but then I saw the issues of other people's efforts on it and didn't want to step on any toes.  Plus I liked their perspectives on it.  Mines just a "plain Jane" take.  It's ready though, so take a look if you'd like and let me know.
