### ISSUE TITLE
Apache + errbit

### ISSUE THREAD

**Issue by federicolucca** [errbit/errbit#1072]
Hi everyone,

I need to deploy errbit on a Ubuntu Ec2 instance,I followed the installation steps,but when i try to load the login page. the Js and Css resources are 404.

Some ideas?

Federico

**Comment by federicolucca** [comment]
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
App 7401 stdout:   actionpack (4.2.5.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
App 7401 stdout:   actionpack (4.2.5.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'

**Comment by stevecrozz** [comment]
Not sure what's going on there. Can you try without apache? It should work fine with only puma.

**Comment by stevecrozz** [comment]
I'm going to close this, but come back to the mailing list or the gitter channel if you need help getting puma going.
