### ISSUE TITLE
remove the concept of issue status (resolving issues)

### ISSUE THREAD

**Issue by stevecrozz** [errbit/errbit#1074]
This is a proposal and feedback is welcome before we actually decide to do this.

The concept of issue status is something that is best handled in an issue tracker. Errbit does not aim to be an issue tracker, but works well with many external issue trackers through the errbit_plugin interface.

Errbit's job is to accept error reports and provide a nice UI for browsing them. I don't see any value in having the option to declare an error resolved or unresolved. If an error report comes in, then the issue is not resolved (at least on that system and at that time).

So I would like to propose we remove this concept entirely and create a new rake task for cleaning old issues. There could be a new system-wide configuration to set the number of days to keep Errors around, and a background task could clean them up when they get too old. The old errbit:clear_resolved rake task could issue a warning about being deprecated and automatically invoke a new rake task that clears expired error notices instead.

**Comment by Polarisation** [comment]
Issue status is a key feature for me. When there are hundreds of errors reported each day, it is very helpful to be able to quickly hide issues by marking them resolved and have them pop up as unresolved if they appear again. For complex/reoccurring issues I would log an issue in an issue tracker, but for quick fixes it's very helpful to have the resolve feature there in ErrBit.

**Comment by stevecrozz** [comment]
@Polarisation If I understand correctly, you're saying you have not just hundreds of errors, but hundreds of distinct types of errors happening every day. And you are using the resolve feature as a kind of 'mark as read' feature so you know what you have and haven't looked it. If that's the case, then that does sound reasonable. I hadn't thought of it this way. But I'll leave this open for a while to see if there are any other thoughts out there.

**Comment by Polarisation** [comment]
@stevecrozz Yes, "mark as read" is a good analogy, so perhaps it should be renamed. I do sometimes mark errors resolved when they were not truly resolved, but I had made a judgement that they were not important.

I'm probably not dealing with hundreds of distinct errors each day, but sometimes the grouping does not work perfectly (I'm aware that with more effort I could customise it), which is another reason why creating a corresponding issue is not always practical, and marking errors as dealt with is often preferred.

**Comment by stevecrozz** [comment]
I'm convinced to not remove issue status tracking. I think it could make sense to rework the naming to track your specific use case more closely because 'read' makes more sense than 'status', but that seems like a pretty unimportant change, and possibly not worth the effort. What I would like to do though is add documentation for issue statuses. So I'll make an issue for that.
