### ISSUE TITLE
Filter (or discard) notices based on user agent

### ISSUE THREAD

**Issue by danielneis** [errbit/errbit#1081]
Hello,

here an example of browser statistics for a "file not found" exception thrown by a Moodle site I help maintain:

Browser 	
97.7% 	facebookexternalhit 1.1 ()
1.1% 	Googlebot-Image 1.0 ()
0.6% 	Firefox 11.0 (Windows XP)
0.4% 	Safari 9.0 (iOS 9.3)
0.2% 	Firefox 43.0 (Linux x86_64)

So, it would be very nice if we could filter out those 98.8% of "false positives", what do you think?

We could have a list provided by configuration (or may suggest some default) that we could test in the "ErrorReport.should_keep?" method and return false if matches. May be, of course, a better place to do the filter, I had just a quick look at the code and found that.

Kind regards,
Daniel

**Comment by mattberther** [comment]
Hi @danielneis,

I might be missing what you're asking for -- but Im not sure this belongs in errbit. Errbit should just be logging whatever it receives. If you dont want something logged, then the request to errbit shouldnt happen.

The official airbrake gem for Ruby allows for your scenario thusly:

``` ruby
Airbrake.configure do |config|
  config.api_key = '1234567890abcdef'
  config.ignore_user_agent << /Ignored/
  config.ignore_user_agent << 'IgnoredUserAgent'
end
```

You didnt mention what airbrake library you're using from your application -- maybe it has a similar user-agent filtering capability?

**Comment by danielneis** [comment]
Hi, @mattberther 

thanks for your response.
I was really wondering if this should be done on the client library or on the errbit side, and just because I saw it on the ruby gem config I thought it would be done on errbit, but looking again it seems better to be a "per application" decision like your example.
I am currently using the PHP lib from https://github.com/emgiezet/errbitPHP
May I suggest to add the option there?

Kind regards,
Daniel

**Comment by mattberther** [comment]
@danielneis I just looked at the errbitPHP project and it appears as though theres an undocumented config option that you might be able to use.

https://github.com/emgiezet/errbitPHP/blob/master/src/Errbit/Errbit.php#L157

Maybe you can try setting the `skipped_exceptions` property in your configure call.

**Comment by danielneis** [comment]
Huum... quite there, but the test that is made is "$exception instanceof $skippedException"
https://github.com/emgiezet/errbitPHP/blob/master/src/Errbit/Errbit.php#L168

I do not want to ignore a type of error, I want to ignore when te error is caused by a particular user agent. I will suggest there that we do anoter test with another config option to skip user agents.

Kind regards,
Daniel

**Comment by mattberther** [comment]
Yes, of course. Sorry about the erroneous information.

**Comment by stevecrozz** [comment]
Looks like this one is solved in the errbitPHP package. Closing this issue.
