### ISSUE TITLE
Issues when linking Google account

### ISSUE THREAD

**Issue by yhourdel** [errbit/errbit#1085]
Hi,
I'm having issues while trying to link a Google account to an existing User: when I click on the "Link Google account" I am redirected to the homepage with the following message: "You are already signed in.".
Any idea on how to fix this ? Google auth is really a great feature, and I'm happy you guys are trying to make it available.

**Comment by stevecrozz** [comment]
@8398a7 Are you able to chime in and help support this new feature?

**Comment by 8398a7** [comment]
@yhourdel 
Is error message the "User already registered with..."?
In that case, the specified Google account already there is a possibility that has been linked to another account.
https://github.com/errbit/errbit/blob/master/app/controllers/users/omniauth_callbacks_controller.rb#L50
In the case of the above, I think the solution is to break the link of the Google account that is tied in with a different account.

In `google_oauth2` method should not contain the process of issuing a message of "You are already signed in." ...
Is there a record that corresponds to when you run the following command in terminal?
```
cd your_errbit_root
rails c -e your_environment
> User.where.not(google_uid: nil)
```

**Comment by yhourdel** [comment]
@8398a7 
Nope, I double checked and no user have a google_uid. I've just migrated from a previous version, it's the first time anyone tries that.
And the message is texto "You are already signed in.".

**Comment by 8398a7** [comment]
>no user has a google_uid.

Field of google_uid within mongodb will exist?

Is the results of `User.first.google_uid` nil?
Or is the exception?

**Comment by yhourdel** [comment]
@8398a7 `User.first.google_uid` returns `nil`

**Comment by 8398a7** [comment]
Please show me the stack trace of that time

**Comment by yhourdel** [comment]
Ok got it, the G+ API was not activated:
```
Started GET "/users/auth/google_oauth2/callback?state=xxx&code=yyy" for a.b.c.d at 2016-05-06 13:10:13 -0400
(google_oauth2) Callback phase initiated.
(google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, {"errors"=>[{"domain"=>"usageLimits", "reason"=>"accessNotConfigured", "message"=>"Access Not Configured. Google+ API has not been used in project xxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus/overview?project=xxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.", "extendedHelp"=>"https://console.developers.google.com/apis/api/plus/overview?project=xxx"}], "code"=>403, "message"=>"Access Not Configured. Google+ API has not been used in project 708248320427 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus/overview?project=xxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."}:
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Access Not Configured. Google+ API has not been used in project xxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus/overview?project=xxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "extendedHelp": "https://console.developers.google.com/apis/api/plus/overview?project=xxx"
   }
  ],
  "code": 403,
  "message": "Access Not Configured. Google+ API has not been used in project xxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus/overview?project=xxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
 }
}
```

I guess the error message should just be clearer, if anything.
Thanks!
