### ISSUE TITLE
Deploy to Heroku MongoDB config not working

### ISSUE THREAD

**Issue by martnst** [errbit/errbit#1088]
Hey,

when using the Deploy to Heroku button it will setup a new app with where the URL to the mongo db add-on is configured in `MONGODB_URI`. This configuration seems to be not taken into consideration though, see [here](https://github.com/errbit/errbit/blob/master/config%2Fload.rb#L29).

**Comment by trueinviso** [comment]
+1, I had to add the key MONGODB_URL = <url> that was under the MONGODB_URI key on heroku to get this to work.

**Comment by stevecrozz** [comment]
ha, they changed url to uri? Anyone want to do the honors or shall I?
