### ISSUE TITLE
Problem deploying

### ISSUE THREAD

**Issue by ngw** [errbit/errbit#1091]
I'm having problems deploying, and I can't find a way to solve them

Gemfile.lock: https://gist.github.com/ngw/e1219d799cac2d1ecde23e83c6975e30
Backtrace: https://gist.github.com/ngw/bef9a26b9536a7f782c8a8c1e7db303f

This is almost plain errbit, and capistrano fails...

**Comment by stevecrozz** [comment]
Not sure what's going on here. Is this a brand new install? I'd consider removing /home/deployer/apps/errbit/ and starting over...
