### ISSUE TITLE
Trick to getting smtp to work?

### ISSUE THREAD

**Issue by blimey85** [errbit/errbit#1096]
My install and instal setup went swimmingly. Then I spent a little over three hours trying everything I could think of to get SMTP working. I'm using SendGrid but I've also tried Gmail with no luck. I don't get any errors, notifications, or any mention in the log file that it's even attempting to send an email. I'm running this on Ubuntu using Nginx and Passenger. My other Rails apps send fine. My .env looks like this:

```
ERRBIT_HOST=errbit.nutrikeeper.com
ERRBIT_PROTOCOL=http
ERRBIT_ENFORCE_SSL=false
CONFIRM_RESOLVE_ERR=true
ERRBIT_CONFIRM_ERR_ACTIONS=true
ERRBIT_USER_HAS_USERNAME=false
ERRBIT_USE_GRAVATAR=true
ERRBIT_GRAVATAR_DEFAULT=identicon
ALLOW_COMMENTS_WITH_ISSUE_TRACKER=true
SERVE_STATIC_ASSETS=true
SECRET_KEY_BASE=*
ERRBIT_EMAIL_FROM='errbit@nutrikeeper.com'
ERRBIT_EMAIL_AT_NOTICES='[1,10,100]'
ERRBIT_PER_APP_EMAIL_AT_NOTICES=false
ERRBIT_NOTIFY_AT_NOTICES='[0]'
ERRBIT_PER_APP_NOTIFY_AT_NOTICES=false
MONGO_URL='mongodb://localhost'
ERRBIT_LOG_LEVEL=debug
ERRBIT_LOG_LOCATION=STDOUT
GITHUB_URL=https://github.com
GITHUB_AUTHENTICATION=true
GITHUB_API_URL=https://api.github.com
GITHUB_ACCESS_SCOPE='[repo]'
GITHUB_SITE_TITLE=GitHub
DEVISE_MODULES='[database_authenticatable,recoverable,rememberable,trackable,validatable,omniauthable]'
GOOGLE_AUTHENTICATION=false
GOOGLE_SITE_TITLE=Google
EMAIL_DELIVERY_METHOD=:smtp
SMTP_SERVER=smtp.sendgrid.net
SMTP_PORT=25
SMTP_DOMAIN=<%= ENV["SENDGRID_DOMAIN"] ?>
SMTP_USERNAME=<%= ENV["SENDGRID_USERNAME"] ?>
SMTP_PASSWORD=<%= ENV["SENDGRID_PASSWORD"] ?>
SMTP_AUTHENTICATION=plain
```

The SMTP settings are pulling from Passenger env variables. I tested this via another Rails app and that's working. I also tried hard coding them. Also tried setting it up for Gmail per what was listed in a GitHub issue. Tried everything I could think of an no dice. I feel like there's a switch somewhere that is telling it I don't want to send email. Also of note, I confirmed it is running in production mode... and everything else works great. Well everything but GitHub login... that doesn't work either but I don't really care about that. I need the email part working though.

Is there a setting I'm missing? Something I need to change somewhere?

**Comment by stevecrozz** [comment]
I don't think this kind of ERB syntax works inside a .env file, but you should be able to run a console with ./bin/rails console and check the values in:
ActionMailer::Base.smtp_settings

**Comment by blimey85** [comment]
Thank you for your help on this! You are correct about ERB not working inside the .env file. So I took that out and hard coded the values in there. Running in console I get:
```
irb(main):001:0> ActionMailer::Base.smtp_settings
=> {:address=>"smtp.sendgrid.net", :port=>25, :authentication=>"plain", :user_name=>"blimey85", :password=>"supersecret", :domain=>"nutrikeeper.com"}
```
Which looks correct. I did another test and no dice. Should I be seeing something in the log where it's attempting to send the email? I have logging set to debug but I get the params and then the database stuff. No mention of it attempting to email.

To enable emails all that needs to be done is adding the SMTP info in the .env file? Is there something in the app that I need to change? I looked through everything and couldn't find anything that seemed related.

**Comment by blimey85** [comment]
Ok, this was my own fault. @stevecrozz was awesome in helping me figure out what I was doing wrong. In case anyone comes across this, by default emails are sent 1, 10, and 100th time an error occurs. I was testing the same error over and over and wondering why email wasn't working. Everything was working fine. Frustrating to waste several hours chasing my tail.
