### ISSUE TITLE
Add backtrace to Slack's notification

### ISSUE THREAD

**Issue by dsandstrom** [errbit/errbit#1104]
I added a backtrace to my Slack notification.  Is there interest in a PR?

**Comment by nmenag** [comment]
this is possible, if you create a app in the section of **NOTIFICATION SERVICE** you can added the hook url of you Slack

**Comment by dsandstrom** [comment]
I know that you can send a notification to slack. However, I propose that a
short backtrace gets added to the notification.  Is that currently an
option?

**Comment by s2ugimot** [comment]
@dsandstorm I'm interested and was looking for exactly the same thing what you have done. Can you push your branch or put patch on gist?

**Comment by dsandstrom** [comment]
Added a PR.
