### ISSUE TITLE
Suggest adding environment to configuration instructions

### ISSUE THREAD

**Issue by dsandstrom** [errbit/errbit#1106]
Specifying the environment an an app's initializer is now required for Errbit to know which environment the error occurred in.  I suggest adding:
```ruby
# Uncomment for Rails apps
# config.environment = Rails.env
# config.ignore_environments = %w(development test)
```
or something similar to the instructions or README.

**Comment by dsandstrom** [comment]
Or you could instruct the user to run Airbrake's generator.  Provide the command with the appropriate attributes.

**Comment by weh** [comment]
tested with airbrake gem version 4.3.6 and 5.4.0, and can confirm that the environment is missing when using 5.4.0

see https://github.com/airbrake/airbrake-ruby#environment
