### ISSUE TITLE
Missing "environment" field causes a NoMethodError

### ISSUE THREAD

**Issue by blackghost1987** [errbit/errbit#1110]
If the v3 error notice doesn't contain the environment field (which should contain the table of the environment key-value pairs), a NoMethodError is raised because it's value will be nil. According to the Airbrake documentation, the field is optional, so nil should be handled.

NoMethodError: undefined method `merge' for nil:NilClass

Backtrace:
lib/airbrake_api/v3/notice_parser.rb:57→ request
lib/airbrake_api/v3/notice_parser.rb:17→ attributes
lib/airbrake_api/v3/notice_parser.rb:26→ report
app/controllers/api/v3/notices_controller.rb:16→ create
actionpack-4.2.5.2/lib/action_controller/metal/implicit_render.rb:4→ send_action
actionpack-4.2.5.2/lib/abstract_controller/base.rb:198→ process_action
actionpack-4.2.5.2/lib/action_controller/metal/rendering.rb:10→ process_action
actionpack-4.2.5.2/lib/abstract_controller/callbacks.rb:20→ block in process_action
activesupport-4.2.5.2/lib/active_support/callbacks.rb:117→ call
activesupport-4.2.5.2/lib/active_support/callbacks.rb:117→ call
activesupport-4.2.5.2/lib/active_support/callbacks.rb:555→ block (2 levels) in compile
activesupport-4.2.5.2/lib/active_support/callbacks.rb:505→ call
activesupport-4.2.5.2/lib/active_support/callbacks.rb:505→ call
activesupport-4.2.5.2/lib/active_support/callbacks.rb:92→ __run_callbacks__
activesupport-4.2.5.2/lib/active_support/callbacks.rb:778→ _run_process_action_callbacks
activesupport-4.2.5.2/lib/active_support/callbacks.rb:81→ run_callbacks
actionpack-4.2.5.2/lib/abstract_controller/callbacks.rb:19→ process_action
actionpack-4.2.5.2/lib/action_controller/metal/rescue.rb:29→ process_action
actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:32→ block in process_action
activesupport-4.2.5.2/lib/active_support/notifications.rb:164→ block in instrument
activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20→ instrument
activesupport-4.2.5.2/lib/active_support/notifications.rb:164→ instrument
actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:30→ process_action
actionpack-4.2.5.2/lib/action_controller/metal/params_wrapper.rb:250→ process_action
actionpack-4.2.5.2/lib/abstract_controller/base.rb:137→ process
actionview-4.2.5.2/lib/action_view/rendering.rb:30→ process
actionpack-4.2.5.2/lib/action_controller/metal.rb:196→ dispatch
actionpack-4.2.5.2/lib/action_controller/metal/rack_delegation.rb:13→ dispatch
actionpack-4.2.5.2/lib/action_controller/metal.rb:237→ block in action
actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:74→ call
actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:74→ dispatch
actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:43→ serve
actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:43→ block in serve
actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:30→ each
actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:30→ serve
actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:815→ call
omniauth-1.2.2/lib/omniauth/strategy.rb:186→ call!
omniauth-1.2.2/lib/omniauth/strategy.rb:164→ call
omniauth-1.2.2/lib/omniauth/strategy.rb:186→ call!
omniauth-1.2.2/lib/omniauth/strategy.rb:164→ call
warden-1.2.4/lib/warden/manager.rb:35→ block in call
warden-1.2.4/lib/warden/manager.rb:34→ catch
warden-1.2.4/lib/warden/manager.rb:34→ call
rack-1.6.4/lib/rack/etag.rb:24→ call
rack-1.6.4/lib/rack/conditionalget.rb:38→ call
rack-1.6.4/lib/rack/head.rb:13→ call
actionpack-4.2.5.2/lib/action_dispatch/middleware/params_parser.rb:27→ call
actionpack-4.2.5.2/lib/action_dispatch/middleware/flash.rb:260→ call
rack-1.6.4/lib/rack/session/abstract/id.rb:225→ context
rack-1.6.4/lib/rack/session/abstract/id.rb:220→ call
actionpack-4.2.5.2/lib/action_dispatch/middleware/cookies.rb:560→ call
actionpack-4.2.5.2/lib/action_dispatch/middleware/callbacks.rb:29→ block in call
activesupport-4.2.5.2/lib/active_support/callbacks.rb:88→ __run_callbacks__
activesupport-4.2.5.2/lib/active_support/callbacks.rb:778→ _run_call_callbacks
activesupport-4.2.5.2/lib/active_support/callbacks.rb:81→ run_callbacks
actionpack-4.2.5.2/lib/action_dispatch/middleware/callbacks.rb:27→ call
actionpack-4.2.5.2/lib/action_dispatch/middleware/remote_ip.rb:78→ call
actionpack-4.2.5.2/lib/action_dispatch/middleware/debug_exceptions.rb:17→ call
actionpack-4.2.5.2/lib/action_dispatch/middleware/show_exceptions.rb:30→ call
railties-4.2.5.2/lib/rails/rack/logger.rb:38→ call_app
railties-4.2.5.2/lib/rails/rack/logger.rb:22→ call
request_store-1.1.0/lib/request_store/middleware.rb:8→ call
actionpack-4.2.5.2/lib/action_dispatch/middleware/request_id.rb:21→ call
rack-1.6.4/lib/rack/methodoverride.rb:22→ call
rack-1.6.4/lib/rack/runtime.rb:18→ call
activesupport-4.2.5.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28→ call
actionpack-4.2.5.2/lib/action_dispatch/middleware/static.rb:116→ call
rack-1.6.4/lib/rack/sendfile.rb:113→ call
railties-4.2.5.2/lib/rails/engine.rb:518→ call
railties-4.2.5.2/lib/rails/application.rb:165→ call
rack-1.6.4/lib/rack/deflater.rb:35→ call
unicorn-5.0.1/lib/unicorn/http_server.rb:562→ process_client
unicorn-5.0.1/lib/unicorn/http_server.rb:658→ worker_loop
unicorn-5.0.1/lib/unicorn/http_server.rb:508→ spawn_missing_workers
unicorn-5.0.1/lib/unicorn/http_server.rb:132→ start
unicorn-5.0.1/bin/unicorn_rails:209→ <top (required)>
[GEM_ROOT]/bin/unicorn_rails:23→ load
[GEM_ROOT]/bin/unicorn_rails:23→ <main>

**Comment by stevecrozz** [comment]
@blackghost1987 Can you add the version number and sha1 for the Errbit version with this error?

**Comment by blackghost1987** [comment]
Error detected on v0.6.0, the latest master with SHA1: 0edf36b594b1ec585f02f4bfcc674a8b8c8b01b7

**Comment by stevecrozz** [comment]
Thanks for the report @blackghost1987. We'll get a fix in the next release.
