### ISSUE TITLE
Empty backtrace list causes an error when displaying the problem

### ISSUE THREAD

**Issue by blackghost1987** [errbit/errbit#1111]
If the v3 error notice contains an empty list of backtrace lines, the request is accepted, but the issue cannot be displayed in the ErrBit UI, because it fails with an error. The backtrace list is a mandatory parametera according to the Airbrake v3 API, but I'm not sure if an empty backtrace list is considered as a valid notice. If not, then the lower processing layers should reject the POST request, but if it's valid then the display layer should be able to handle it as well.

Error and backtrace:

NoMethodError: undefined method `map' for nil:NilClass

app/decorators/backtrace_decorator.rb:3→ lines
app/decorators/backtrace_decorator.rb:8→ grouped_lines
app/views/notices/_backtrace.html.haml:6→ _app_views_notices__backtrace_html_haml__4311720278790716856_70184625016960
actionview-4.2.5.2/lib/action_view/template.rb:145→ block in render
activesupport-4.2.5.2/lib/active_support/notifications.rb:166→ instrument
actionview-4.2.5.2/lib/action_view/template.rb:333→ instrument
actionview-4.2.5.2/lib/action_view/template.rb:143→ render
actionview-4.2.5.2/lib/action_view/renderer/partial_renderer.rb:339→ render_partial
actionview-4.2.5.2/lib/action_view/renderer/partial_renderer.rb:310→ block in render
actionview-4.2.5.2/lib/action_view/renderer/abstract_renderer.rb:39→ block in instrument
...

**Comment by stevecrozz** [comment]
@blackghost1987 Can you add the version number and sha1 for the Errbit version with this error?

**Comment by blackghost1987** [comment]
Error detected on v0.6.0, the latest master with SHA1: 0edf36b594b1ec585f02f4bfcc674a8b8c8b01b7

**Comment by stevecrozz** [comment]
I'm fine with supporting empty backtraces. I think we should go ahead and add notices even with empty backtraces. Thanks for the report.

**Comment by blackghost1987** [comment]
Great! In the meantime I've checked the JSON schema definition and it looks like a required list can be empty. The Airbrake schema doesn't specify anything about the number of items as far as I know, so it probably should be accepted.
And just to clarify again: The notice is already added, it's showing up in the problems list, the error is happening only when the problem details page is opened.
