### ISSUE TITLE
Can't view errors

### ISSUE THREAD

**Issue by trueinviso** [errbit/errbit#1112]
I can't view any errors in errbit.  The errors come through but they all have the same generic location that looks something like this: `/apps/56ccccc3ababa000c00004f/problems/577777717aab222c00002c`.  When I click on this link to view the error I get the following error:

![image](https://cloud.githubusercontent.com/assets/5495092/17040556/3f5ae1fc-4f55-11e6-8de2-eb2487e994b4.png)

Every error shows up like this in my project and in the Self.errbit project folder.

**Comment by stevecrozz** [comment]
oh my. since you can't see the error in errbit, we'll need to collect information about the error from your log files. can you search through there and see if you can find one and paste it here?

**Comment by trueinviso** [comment]
This is the error I am getting: `Mongo::Error::OperationFailure (quota exceeded (12501))`.  But I'm a little confused because in the mLab control panel (using heroku) it looks like this:

![image](https://cloud.githubusercontent.com/assets/5495092/17042075/a3f87566-4f5f-11e6-9b65-c212d8678f8a.png)

They all say capped false.  Am I missing something?

**Comment by stevecrozz** [comment]
That all looks fine, but it does seem like you must be hitting some limit with mlab. I found a suggestion here that might help: https://twitter.com/bradezone/status/413355049805709312

**Comment by trueinviso** [comment]
That fixed it, thanks a lot!
