### ISSUE TITLE
Airbrake doesn't like -1 for project_id

### ISSUE THREAD

**Issue by dsandstrom** [errbit/errbit#1119]
I received an error when deploying my app:
```
Airbrake::Error: :project_id is required
```

airbrake-ruby-1.5.0
airbrake-5.4.5.

I was using `-1` as the configuration instructions show.  I changed the `project_id` to `1234` and that seemed to work.

**Comment by stevecrozz** [comment]
Yeah. I think new versions of airbrake-ruby added more unnecessary validations in the client. I'll need to update the docs.

**Comment by stevecrozz** [comment]
Pushed a change to the instructions to solve this issue. For the curious, here's the new validation airbrake provides that broke the instructions:
https://github.com/airbrake/airbrake-ruby/blob/107dd2adb1227700baa1f75a2fe6719fb85a66fb/lib/airbrake-ruby/config/validator.rb#L46
