### ISSUE TITLE
ArgumentError: Malformed version number string Rails/4.2.6

### ISSUE THREAD

**Issue by JulienFontaine** [errbit/errbit#1122]
Hi,

I configured an Errbit server on Heroku using the "deploy to Heroku" button, created an Errbit app and setup my Rails app following the wiki (https://github.com/rotati/wiki/wiki/Add-and-configure-Errbit-on-your-app). The only change I did is to use the airbrake gem in every environment to be able to test it in development before pushing it to staging.

When I try the command `rake airbrake:test`, I get this response:

`E, [2016-10-02T15:18:24.897994 #27125] ERROR -- : **Airbrake: unexpected code (422). Body: Notice for old app version ignored
Error occurred: Notice for old app version ignored
Make sure that your Project ID and Project Key are correct:
https://github.com/airbrake/airbrake-ruby#project_id--project_key`

project_id is a positive integer and project_key is copy pasted from

When I go to the Errbit app index, I now see a Self.Errbit app. From what I read, it seems that an error occured in Errbit, so I'm posting this information here as an issue.

My rails app is configured to use Ruby 2.3.0p0 and Rails 4.2.6, the airbrake gem is 5.5.0.

**Comment by lucianosousa** [comment]
everything looks fine here for me. I just did a fresh install now.

did you update your `config.host` with the heroku URL?

**Comment by JulienFontaine** [comment]
Yes I updated the config.host with heroku URL. I tried different things but none worked.

In the meantime, I started over and installed a fresh copy manually using this tutorial: https://github.com/errbit/errbit/blob/master/docs/deployment/heroku.md -> The Hard Way, and it's working fine now.

It looks that there's a difference between the "manual way" and the "automatic deploy to heroku way".

**Comment by jackdesert** [comment]
I am having this problem as well. 
    ArgumentError: Malformed version number string Rails/4.2.4
shows up as an internal error. 

I have tried with airbrake gem version 5.0, 5.5, and 5.7. They all give the same error. 

Running `rake airbrake:test` gives the following output:

    E, [2017-03-01T11:43:15.614603 #6321] ERROR -- : **Airbrake: unexpected code (422). Body: Notice for old app version ignored
    [ruby]
    description: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

    [rails]
    version: 4.2.4

    [airbrake]
    version: 5.0.0

    [airbrake-ruby]
    version: 1.8.0

    [notifiers]
    default:
      [#<Airbrake::Config:0x0055947ccc2700
      @blacklist_keys=[],
      @endpoint=
       #<URI::HTTPS https://errbit.elitecare.com/api/v3/projects/1/notices?key=62f7d5ae6a7a1550d0a69d0cbe046d5c>,
      @environment="development",
      @host="https://errbit.elitecare.com",
      @ignore_environments=["test"],
      @logger=
       #<Logger:0x0055947ccc2660
        @default_formatter=
         #<Logger::Formatter:0x0055947ccc2638 @datetime_format=nil>,
        @formatter=nil,
        @level=2,
        @logdev=
         #<Logger::LogDevice:0x0055947ccc25c0
          @dev=#<IO:<STDOUT>>,
          @filename=nil,
          @mutex=
           #<Logger::LogDevice::LogDeviceMutex:0x0055947ccc2598
            @mon_count=0,
            @mon_mutex=#<Mutex:0x0055947ccc2548>,
            @mon_owner=nil>,
          @shift_age=nil,
          @shift_size=nil>,
        @progname=nil>,
      @project_id=1,
      @project_key="62f7d5ae6a7a1550d0a69d0cbe046d5c",
      @proxy={},
      @queue_size=100,
      @root_directory=#<Pathname:/home/jd/r/elitecarerails>,
      @timeout=nil,
      @validator=
       #<Airbrake::Config::Validator:0x0055947ccc26b0
        @config=#<Airbrake::Config:0x0055947ccc2700 ...>,
        @error_message=nil>,
      @whitelist_keys=[],
      @workers=1>,
     #<Airbrake::FilterChain:0x0055947ccc21d8
      @filters=
       [#<Proc:0x005594776adc98@/home/jd/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/airbrake-ruby-1.8.0/lib/airbrake-ruby/filter_chain.rb:40>,
        #<Proc:0x005594776add10@/home/jd/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/airbrake-ruby-1.8.0/lib/airbrake-ruby/filter_chain.rb:13>,
        #<Proc:0x0055947ccc2110@/home/jd/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/airbrake-ruby-1.8.0/lib/airbrake-ruby/filter_chain.rb:84>],
      @keys_filters=[]>]


    The output above contains useful information about your environment. Our support
    team may request this information if you have problems using the Airbrake gem;
    we would be really grateful if you could attach the output to your message.

    The test exception was sent. Find it here:


Here is my config:

    Airbrake.configure do |config|
      config.host = 'https://errbit.elitecare.com'
      config.project_id = 1 # required, but any positive integer works
      config.project_key = '[secret]'

      # Uncomment for Rails apps
      config.environment = Rails.env
      config.ignore_environments = %w(test)
    end

**Comment by stevecrozz** [comment]
Hey @jackdesert. This error is part of an errbit feature that rejects errors when the version of your own application (the one sending an error notification to errbit) is older than the version you've configured for the application in Errbit.

I believe you can work around it by visiting the Errbit UI and navigating to the application's configuration and removing the info in the field 'Latest App Version'.

If that solves things for you, then I'll close this ticket, but I'd like to start a new discussion on the utility of this feature which seems to be causing confusion.

**Comment by stevecrozz** [comment]
Anyone interested in discussing the 'latest app version' feature is welcome to join me in #1172.

**Comment by jackdesert** [comment]
@stevecrozz Yes, that fixes it for me. Thanks!

**Comment by stevecrozz** [comment]
Great. I'm going to close this issue then, and we'll figure out a way to smooth out this rough edge in #1172.
