### ISSUE TITLE
Notify on deploy and link to notification service

### ISSUE THREAD

**Issue by halida** [errbit/errbit#1132]
Hi, errbit have deploy log, I'm thinking about it should have notify service for it ( like link to slack ), so every member in the team knows which application is deployed.

**Comment by stevecrozz** [comment]
It is important to know which application versions have errors, but there could be many versions of an application that are deployed. There might not be a single version deployed, but I think there is still some work we could do to help users understand which versions of their applications are having problems. More advanced searching would help I think or maybe a way to group errors by application version. There's a lot of good stuff we could explore in this area.
