### ISSUE TITLE
Deploy track feature needed

### ISSUE THREAD

**Issue by halida** [errbit/errbit#1133]
I found deploy list is missing for the 0.6.0 version, after that, I found you remove it: https://github.com/errbit/errbit/issues/913

It is an good feature to track when and which version is deployed for an app, if you really want delete this feature, can you suggest an alternative? Thanks.

**Comment by stevecrozz** [comment]
Hi @halida, I suppose it depends on your use case. At one point, I was working on a project that I was deploying with Capistrano and I wanted notifications in slack, so I used https://github.com/phallstrom/slackistrano. That's a very specific use case and may not suit your needs even if its just sending an email to yourself or adding an entry to keen.io.

As far as Errbit goes. It should know something about the version of code deployed, but only within the context of an error notification. We are already storing that information whenever apps are sending it, but Errbit could use some nicer UI for helping people identify which app versions have which problems.

Specifically for deployment tracking, there are no plans to bring it back. Errbit aims only to solve the problem of tracking errors.

**Comment by halida** [comment]
@stevecrozz Thanks, I will check it out.
