### ISSUE TITLE
uninitialized constant DecentExposure::StrongParametersStrategy

### ISSUE THREAD

**Issue by CR4567** [errbit/errbit#1146]
Hi,
after upgrading from errbit v0.6.0 to current master, I'm getting the following error when trying to start the application. But decent_exposure gem is installed and has the newest version. I'm running ruby 2.3.1, before everything worked fine. Any ideas?

NameError: uninitialized constant DecentExposure::StrongParametersStrategy
/var/www/errbit/app/controllers/application_controller.rb:10:in `<class:ApplicationController>'
/var/www/errbit/app/controllers/application_controller.rb:1:in `<top (required)>'
/var/www/errbit/app/controllers/api/v1/notices_controller.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/engine.rb:471:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/engine.rb:471:in `block in eager_load!'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/engine.rb:469:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/engine.rb:469:in `eager_load!'
/usr/local/rvm/gems/ruby-2.3.1/gems/mongoid-5.0.2/lib/mongoid/railties/database.rake:70:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by stevecrozz** [comment]
So far I haven't been able to reproduce this. You ran `bundle install` and then `bundle exec puma` to start the app and it crashes with NameError? Could you post the whole CLI output from:
~~~bash
ruby -v
bundler -v
bundle install
bundle exec puma
~~~

Mine is attached here:
[init.txt](https://github.com/errbit/errbit/files/652575/init.txt)

**Comment by CR4567** [comment]
thanks for the quick reply.
Actually I didn't run the server. I tried the upgrade process and got the error when trying
`rake db:mongoid:remove_undefined_indexes
`
But it occurs also when trying to start the server. In detail:

 Log:
[log.txt](https://github.com/errbit/errbit/files/654200/log.txt)

**Comment by stevecrozz** [comment]
@CR4567 Just to be sure, can you try `bundle exec rake ...`

**Comment by CR4567** [comment]
hm... throws also an error.
[log.txt](https://github.com/errbit/errbit/files/655351/log.txt)

**Comment by stevecrozz** [comment]
@CR4567 Well this is very strange. It seems like there's something wrong with the bundle. decent_exposure is in the Gemfile and for whatever reason it can't be autoloaded. Could be a problem with the autoloader, a problem with the load path, or maybe somehow the gem really isn't there.

Can you do this without seeing any errors?
~~~ruby
~/Projects/errbit/errbit (master $=)$ bundle exec irb
irb(main):001:0> require 'decent_exposure/strong_parameters_strategy'
=> true
irb(main):002:0> DecentExposure::StrongParametersStrategy
=> DecentExposure::StrongParametersStrategy
~~~

**Comment by CR4567** [comment]
Again error.... looks like the gem is not correctly installed, but I already uninstalled and it, and tried bundle install again.... 
[log.txt](https://github.com/errbit/errbit/files/655446/log.txt)

**Comment by stevecrozz** [comment]
Might have to. You could take Errbit entirely out of the equation by creating a brand new project folder and putting a Gemfile in it with only `gem 'decent_exposure'` and see if you can load the gem just as above (bundle exec irb). If that still fails, then there's something fundamentally broken or misconfigured about your ruby or environment.

**Comment by CR4567** [comment]
ok... I didn't get it running. I removed my complete rvm installation with all gems and reinstalled everything. But no effect.
For now I removed the parts about decent_expsure in /app/controllers/application.rb and got it working  again. Maybe I find some time later to investigate the real issue....

Thanks a lot for your help and support.

**Comment by dmitry-fedyuk** [comment]
I have the same issue too.  
The `lib/decent_exposure/strong_parameters_strategy.rb` file was removed from the 3.x branch of the `decent_exposure`:
https://github.com/hashrocket/decent_exposure/tree/v3.0.2/lib/decent_exposure
https://github.com/hashrocket/decent_exposure/blob/v2.3.3/lib/decent_exposure/strong_parameters_strategy.rb

**Comment by stevecrozz** [comment]
Nice catch. I was thinking the Gemfile.lock would prevent this:
https://github.com/errbit/errbit/blob/v0.6.1/Gemfile.lock#L103

I've apparently got a misunderstanding of how the Gemfile.lock works. I'll look into this.

**Comment by CR4567** [comment]
ah nice one. Thanks @dmitry-fedyuk . Helps me a lot... was really struggling what I did wrong :-)

**Comment by stevecrozz** [comment]
I don't understand how this can be happening actually. Even in a fresh environment, bundle install installs the correct version of decent_exposure. Have you folks run a `bundle update` by chance? That could definitely change the gem versions...

**Comment by stevecrozz** [comment]
Still haven't seen this happen, but I figure we may as well upgrade to the latest decent_exposure anyway. So I put together #1153 for that. You're welcome to give it a whirl.

**Comment by rud** [comment]
Time to close this issue?

**Comment by stevecrozz** [comment]
Agreed.
