### ISSUE TITLE
NoMethodError in Apps#show

### ISSUE THREAD

**Issue by z-matth** [errbit/errbit#1159]
NoMethodError in Apps#show
See attached screenshot or full text below. Reproduces when clicking on an App name. Or clicking on a red Error count button on the main Apps tab. 

I ran the following to make sure I'm up to date. No change in symptom.
git pull origin master
bundle install
rake db:migrate
rake db:mongoid:remove_undefined_indexes
rake db:mongoid:create_indexes
rake assets:precompile

Errbit was working previously, but unfortunately i forgot to tie my git checkout to a branch other than master and a chef run likely upgraded me.

Mongo 3.2.9
AWS EC2 Ubuntu 14.04
Ruby 2.3.1p112

app/views/apps/show.html.haml:1:in `_app_views_apps_show_html_haml___1424480621227634094_69868529840400'
actionview (4.2.5.2) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.5.2) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.5.2) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.5.2) lib/action_view/template.rb:143:in `render'
actionview (4.2.5.2) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (4.2.5.2) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.5.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.5.2) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.5.2) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (4.2.5.2) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (4.2.5.2) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (4.2.5.2) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (4.2.5.2) lib/action_view/renderer/renderer.rb:46:in `render_template'
actionview (4.2.5.2) lib/action_view/renderer/renderer.rb:27:in `render'
actionview (4.2.5.2) lib/action_view/rendering.rb:100:in `_render_template'
actionpack (4.2.5.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.2.5.2) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (4.2.5.2) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.2.5.2) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
actionpack (4.2.5.2) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.2.5.2) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (4.2.5.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (4.2.5.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (4.2.5.2) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (4.2.5.2) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (4.2.5.2) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.5.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.5.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.5.2) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.5.2) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.5.2) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.5.2) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.5.2) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.5.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.5.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.5.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.5.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.5.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
actionpack (4.2.5.2) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.5.2) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.5.2) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.5.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.5.2) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:815:in `call'
omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
hoptoad_notifier (2.4.11) lib/hoptoad_notifier/rack.rb:27:in `call'
warden (1.2.4) lib/warden/manager.rb:35:in `block in call'
warden (1.2.4) lib/warden/manager.rb:34:in `catch'
warden (1.2.4) lib/warden/manager.rb:34:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.5.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.5.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.5.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
actionpack (4.2.5.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.5.2) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.5.2) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.5.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.5.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.5.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.5.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
better_errors (2.1.1) lib/better_errors/middleware.rb:59:in `call'
rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
actionpack (4.2.5.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.5.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.5.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.5.2) lib/rails/rack/logger.rb:22:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
actionpack (4.2.5.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.5.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.5.2) lib/action_dispatch/middleware/static.rb:116:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
hoptoad_notifier (2.4.11) lib/hoptoad_notifier/user_informer.rb:12:in `call'
railties (4.2.5.2) lib/rails/engine.rb:518:in `call'
railties (4.2.5.2) lib/rails/application.rb:165:in `call'
rack (1.6.4) lib/rack/deflater.rb:35:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
puma (3.4.0) lib/puma/configuration.rb:224:in `call'
puma (3.4.0) lib/puma/server.rb:569:in `handle_request'
puma (3.4.0) lib/puma/server.rb:406:in `process_client'
puma (3.4.0) lib/puma/server.rb:271:in `block in run'
puma (3.4.0) lib/puma/thread_pool.rb:114:in `block in spawn_thread'

![screen shot 2017-01-12 at 2 04 30 pm](https://cloud.githubusercontent.com/assets/17790786/21910750/431021d4-d8d2-11e6-995f-2d757666ff9c.png)

**Comment by stevecrozz** [comment]
hrm. i bet this is related to the changes I just merged to support the new version of decent_exposure. will have a look soon. thanks for the report!

**Comment by z-matth** [comment]
holly bajeezus you're fast. thanks for looking into it. huge errbit fan.

**Comment by stevecrozz** [comment]
Hey thanks @z-matth. I just sat down to try to repro this error and I'm not seeing it yet. Any chance we could look at your app together? I could join you at https://gitter.im/errbit/errbit tomorrow if you're available.

**Comment by rud** [comment]
Closing this du to inactivity, sorry.
