### ISSUE TITLE
Empty Environment Tab

### ISSUE THREAD

**Issue by davidlesches** [errbit/errbit#1165]
My environment tab is empty. It only shows HTTP_USER_AGENT. All the other fields, like ip and request referrer, are gone. Is there a way for me to fix this? Thanks

**Comment by 2called-chaos** [comment]
@davidlesches Have you found a solution yet? I experience the same issue :(

**Comment by caseyohara** [comment]
I am having this same issue, the environment tab is empty except for `HTTP_USER_AGENT` and `PROGRAM_NAME`.

Errbit 0.7.0-dev
Client is Airbrake 7.2.1 / Rails 5.2

**Comment by 2called-chaos** [comment]
I don't know if anything changed recently (I'm on airbrake 6.3 still) but after quite a bit of work I managed to get what I had before + some goodies. This is our config, maybe it can help out

https://gist.github.com/2called-chaos/eb2dabbafc6ea6d801e32dfe884f4758

**Comment by caseyohara** [comment]
Thanks @2called-chaos, this points me in the right direction. I'm upgrading from a very old version of Airbrake (4.3.1) and I have to say I'm disappointed with where they've taken it. You are right, it used to have sane defaults and now it has no defaults at all. Requiring this level of configuration is absurd. Airbrake just seems so over-engineered now.

**Comment by davidlesches** [comment]
@caseyohara It's what always happens unfortunately. A sass product becomes popular precisely bc it comes with great defaults out of the box and "just works". Then all the feature requests come in and instead of being selective, they try to make everyone happy. The result is always that the product is re-engineered into a hassle to deal with. It's a good reminder to us devs too, bc we tend to do that too with client requests for our own products, *sigh*

**Comment by rud** [comment]
Sounds like you have a way forward @davidlesches. I'm closing this issue out as it sounds fixed to me.

Any necessary documentation update would be most welcome!
