### ISSUE TITLE
Slack posts use "errbit.example.com" url

### ISSUE THREAD

**Issue by jackdesert** [errbit/errbit#1173]
errbit is posting to a slack channel, but when I click the link in slack it takes me to errbit.example.com instead of errbit.elitecare.com. Is this a bug, or do I have something misconfigured? I've already checked my configuration on slack.com and in config/initializers/errbit.rb

**Comment by stevecrozz** [comment]
You should be able to set that using the ERRBIT_HOST environment variable:
http://errbit.com/docs/master/configuration.html#configuration-parameters

**Comment by jackdesert** [comment]
Docs---great! I went to the wiki and it was pretty bare so I assumed the README was all the docs that existed...

**Comment by smddzcy** [comment]
I have this same issue on Javascript, and setting `ERRBIT_HOST` parameter doesn't change anything.

```javascript
process.env.ERRBIT_HOST = 'errbit.asklisa.ai';
process.env.ERRBIT_PROTOCOL = 'https';
const airbrake = new AirbrakeClient({
  host: 'someHost',
  projectId: 1,
  projectKey: 'someKey',
  environment: process.env.NODE_ENV,
});
...
airbrake.notify(someError);
```

I get a URL that starts with `http://errbit.example.com/apps/...`. What can I do about this?
