### ISSUE TITLE
Dockerfile: variable PORT has two different and incompatible default variables

### ISSUE THREAD

**Issue by giorgian** [errbit/errbit#1177]
Running the docker container without specifying the `PORT` variable (and without using docker-compose) results in a container that keeps failing its health check.
This is because `config/puma.default.rb` contains:

    port ENV['PORT'] || 8080

while `Dockerfile` contains:

    HEALTHCHECK CMD curl --fail http://localhost:$PORT/users/sign_in || exit 1

So the server will start at port 8080 but will be checked at port 80.

**Comment by rud** [comment]
Patches are most welcome

**Comment by tjnet** [comment]
PORT variable in Dockerfile is not present now.
Does problem still remain?

**Comment by giorgian** [comment]
Hi, thank you, yes, now it can be closed as the port is fixed.

**Comment by rud** [comment]
Thanks
