### ISSUE TITLE
NoMethodError: undefined method `match' for nil:NilClass

### ISSUE THREAD

**Issue by daedeloth** [errbit/errbit#1185]
This error keeps to pop up when trying to open the detail view of an issue.

Full stack trace:
[PROJECT_ROOT]/decorators/backtrace_line_decorator.rb:5→ in_app?
[PROJECT_ROOT]/decorators/backtrace_decorator.rb:9→ block in grouped_lines
[PROJECT_ROOT]/views/notices/_backtrace.html.haml:6→ call
[PROJECT_ROOT]/views/notices/_backtrace.html.haml:6→ each
[PROJECT_ROOT]/views/notices/_backtrace.html.haml:6→ each
[PROJECT_ROOT]/views/notices/_backtrace.html.haml:6→ each
[PROJECT_ROOT]/views/notices/_backtrace.html.haml:6→ _app_views_notices__backtrace_html_haml__727298276981401253_70247310584760
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/template.rb:145→ block in render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/template.rb:333→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/template.rb:143→ render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:339→ render_partial
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:310→ block in render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39→ block in instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164→ block in instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:309→ render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:51→ render_partial
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/helpers/rendering_helper.rb:35→ render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/haml-4.0.7/lib/haml/helpers/action_view_mods.rb:10→ block in render_with_haml
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/haml-4.0.7/lib/haml/helpers.rb:89→ non_haml
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/haml-4.0.7/lib/haml/helpers/action_view_mods.rb:10→ render_with_haml
[PROJECT_ROOT]/views/problems/show.html.haml:73→ _app_views_problems_show_html_haml___3416615042966813914_70247326662900
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/template.rb:145→ block in render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/template.rb:333→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/template.rb:143→ render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:54→ block (2 levels) in render_template
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39→ block in instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164→ block in instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:53→ block in render_template
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:61→ render_with_layout
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:52→ render_template
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:14→ render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:46→ render_template
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:27→ render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:100→ _render_template
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/streaming.rb:217→ _render_template
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:83→ render_to_body
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:32→ render_to_body
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/renderers.rb:37→ render_to_body
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/abstract_controller/rendering.rb:25→ render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:16→ render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44→ block (2 levels) in render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12→ block in ms
[PROJECT_ROOT]/vendor/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303→ realtime
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12→ ms
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44→ block in render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:87→ cleanup_view_runtime
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:43→ render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:10→ default_render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:5→ send_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20→ block in process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555→ block (2 levels) in compile
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92→ __run_callbacks__
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778→ _run_process_action_callbacks
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81→ run_callbacks
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32→ block in process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164→ block in instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137→ process
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:30→ process
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196→ dispatch
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13→ dispatch
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237→ block in action
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74→ dispatch
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43→ serve
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43→ block in serve
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30→ each
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30→ serve
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186→ call!
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186→ call!
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-ssl-enforcer-0.2.8/lib/rack/ssl-enforcer.rb:52→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/warden-1.2.4/lib/warden/manager.rb:35→ block in call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/warden-1.2.4/lib/warden/manager.rb:34→ catch
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/warden-1.2.4/lib/warden/manager.rb:34→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/etag.rb:24→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:25→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/head.rb:13→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/params_parser.rb:27→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/flash.rb:260→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225→ context
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/cookies.rb:560→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:29→ block in call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:88→ __run_callbacks__
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778→ _run_call_callbacks
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81→ run_callbacks
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:27→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:78→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:17→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:38→ call_app
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:22→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/runtime.rb:18→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/static.rb:120→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:518→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/railties-4.2.8/lib/rails[PROJECT_ROOT]lication.rb:165→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/deflater.rb:35→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/puma-3.8.2/lib/puma/configuration.rb:224→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/puma-3.8.2/lib/puma/server.rb:600→ handle_request
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/puma-3.8.2/lib/puma/server.rb:435→ process_client
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/puma-3.8.2/lib/puma/server.rb:299→ block in run
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120→ block in spawn_thread

**Comment by tartinesKiller** [comment]
Same here, it seems it happens when an entry of a backtrace have it's file_name set to null. 
This field is set to null by the SharpBrake Notifier [https://github.com/airbrake/sharpbrake](url) for example. 
Unfortunately, I don't known Ruby, so I can't really provide a fix... but I hope I've helped a bit nevertheless. I hope a Ruby-lover will fix this, thanks in advance!

**Comment by tartinesKiller** [comment]
I've created a quick n' dirty fork from Sharpbrake, which replace empty filenames (in case of lambda for example) with "<lambda>"; errbit is now showing the issue correctly. This is a temporary fix, but I hope it can help.
[https://github.com/tartinesKiller/sharpbrake](url)

**Comment by daedeloth** [comment]
I feel like it should be fixed in errbit itself.

Either it is changed to a required field and it doesn't accept any input without file_name (ignoring errors = not cool), OR the view method is fixed and no error is thrown when file_name is null.

**Comment by tartinesKiller** [comment]
It's what I think too, but right now I don't have the time to dive into ruby.

Errbit is "Airbrake API compliant", and in Airbrake null file_name might be correct (I don't think such an error exists in the official c# notifier). So I think the best thing to do is changing the notice view logic in order to allow null file_name.

**Comment by tartinesKiller** [comment]
I just found this pull request: [https://github.com/errbit/errbit/pull/1135](url)

**Comment by tartinesKiller** [comment]
Any news on this issue? 
Thanks

**Comment by rbazinet** [comment]
I see the pull request mentioned above is no longer available. What's the status of this issue? It happens a lot and looked to be fixed but yet it's not.

**Comment by stevecrozz** [comment]
Looks like the link may have been malformed above. Working link: https://github.com/errbit/errbit/pull/1135

**Comment by daedeloth** [comment]
It boggles my mind this fix still hasn't been merged yet.

**Comment by stevecrozz** [comment]
The code looks right to me, but it doesn't have any tests to prove it works (and to ensure it doesn't break again). I suppose I could relax our standards here in this one case if its causing a lot of grief for people... but at the same time it seems like it shouldn't be hard to whip up a test or two. Anyone feel up to it?

**Comment by daedeloth** [comment]
You're absolutely right but I don't have any ruby experience :)

Putting a validator that forces the filename to be set will break some notifiers (I have it with PHP, but apparently the C# notifier also does this). So I'd fix the decorator, not the validation.

The code submitted seems straight forward, but I understand your requirements too :) Sadly I can't help though, and the bug remains.

**Comment by stevecrozz** [comment]
It has been a long time and I know you're not the only one dealing with this issue, so I'm going to add the tests momentarily and get this fix merged.

**Comment by daedeloth** [comment]
You are a hero :+1: :crown:
