### ISSUE TITLE
Question: Can errbit be installed in a windows server?

### ISSUE THREAD

**Issue by Payetus** [errbit/errbit#1186]
By company policy, most servers should be windows OS (Trust me I fought it). Could I install errbit in a Windows server, even if thr ruby version is not possible. Maybe errbit-PHP?

**Comment by stevecrozz** [comment]
First thing that comes to mind is docker. If you can run docker containers, you can run errbit: https://hub.docker.com/r/errbit/errbit/

Another idea is the linux subsystem feature which I've never used: https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

As far as running natively, I've never tried it and I'd be surprised if it works, but in theory it should...

**Comment by kohenkatz** [comment]
It does work, but the performance of Ruby on Windows is absolutely terrible. Don't do it.
