### ISSUE TITLE
High memory consumption during clear_old_resolved task

### ISSUE THREAD

**Issue by ilchanka** [errbit/errbit#1187]
Hi

I have a problem when running clear_old_resolved rake task, I repeated this in console an this is what I got
```ruby
Problem.resolved.where(:resolved_at.lte => Time.now.advance(weeks: -4)).count
=> 341
Problem.resolved.where(:resolved_at.lte => Time.now.advance(weeks: -4)).each(&:destroy)
Ctrl+C after 20 mins
Problem.resolved.where(:resolved_at.lte => Time.now.advance(weeks: -4)).count
=> 341
```
And this is result after 20 mins in newrelic
http://prntscr.com/ethkri

First ```Problem``` that is tried to be deleted had around 50k ```notices```. Looks like the throuble here in running ```problem_recache``` callback after destroying ```Notice```. Maybe we can set in ```Err``` model 
```ruby
has_many :notices, inverse_of: :err, dependent: :delete
``` 
and call recache on ```Err``` model. What do you think about this solution?

Errbit master, Ruby 2.1

**Comment by stevecrozz** [comment]
It would be good to see how well that works.

There is also an 'interactor' for this procedure that you can try:
https://github.com/errbit/errbit/blob/master/app/interactors/problem_destroy.rb

If it works, then maybe the solution is to add better documentation :)

**Comment by ilchanka** [comment]
@stevecrozz nice, I will try this interactor and will change code in task if it works
