### ISSUE TITLE
Feature Request: Support snoozing notifications

### ISSUE THREAD

**Issue by MohamedBassem** [errbit/errbit#1190]
I have an errbit app with slack notifications enabled. Whenever a cronjob fails, it gets restarted and I get a slack notification from errbit which is nice. When the job is restarted and fails again, I get another slack message. The channel is then spammed with the same error happening over and over again even when I'm actually fixing the bug. My feature request is adding the ability to snooze/silence the notifications of a certain error for a period of time (while the issue is being fixed for example). The only workaround I found was to disable the notifications of the whole app, which is not optimal.

**Comment by rud** [comment]
Closing this as #1218 was closed. Have a look at `ERRBIT_NOTIFY_AT_NOTICES` to see if that would help you stem the flow.
