### ISSUE TITLE
Creating new user has no email vaildation

### ISSUE THREAD

**Issue by Starkmann** [errbit/errbit#1191]
You can create accounts with email addresses that are already existing.

And the last created account is the only one you can lock in with.

Example:

Admin user:
peter
pe@ter.de
[x] is admin

New user:
heinz
pe@ter.de
[] is admin

Login works now just for heinz, peter can not login anymore. So admin account is lost!

**Comment by stevecrozz** [comment]
Thanks for the report. Looks like a good one!

**Comment by Starkmann** [comment]
Sorry this was my mistake. This bug doesn't exist.

Validation works as expected.
```
Dang. The following errors are keeping this from being a success.
    Email is already taken
```

**Comment by stevecrozz** [comment]
No prob. Thanks for taking the time anyway.
