### ISSUE TITLE
support mentioning users as part of hipchat room notification

### ISSUE THREAD

**Issue by sahglie** [errbit/errbit#1198]
When notifications are sent to hipchat rooms, developers can't receive a push notification unless they are @mentioned. Getting a push notification when an error happens seems like a fairly useful feature: it definitely is for my team.

Here is a pull request that implements this functionality: https://github.com/errbit/errbit/pull/1189

**Comment by sahglie** [comment]
Hi,

Just wanted to follow up on this issue as I've heard nothing for over a month.  Would definitely appreciate some feedback.

Thanks.

**Comment by stevecrozz** [comment]
Thank you for following up @sahglie. I'll have a look today.

**Comment by rud** [comment]
Mentioned PR was merged, so closing this
