### ISSUE TITLE
Invalid  HTTP verb for curl command

### ISSUE THREAD

**Issue by jonathantribouharet** [errbit/errbit#1205]
Hi,
for some of my errors, I have in the tab Environment the value "HEAD" for HTTPMETHOD, but for the curl command I have a GET, so when I copy / paste the curl I was enable to reproduce the error (due to a check on the HTTP verb in my application).

Thanks.

**Comment by stevecrozz** [comment]
Hello @jonathantribouharet. Can you add more to your description and ideally steps to reproduce the problem you see including 1) what you did, 2)what you expect, and 3) what you see instead?

**Comment by jonathantribouharet** [comment]
Ok,
for reproduce the problem you need to have an exception that happen because of a HEAD request.
My app is in Ruby On Rails 4.2.7.1 with Ruby MRI 2.2.3.

You can try in a simple Rails project with a method like this:
```
def index
  raise "Test" if request.head?
end
```

in the tab Environment I have this:
<img width="934" alt="screen shot 2017-07-03 at 19 34 10" src="https://user-images.githubusercontent.com/188946/27802868-b40ccbb8-6026-11e7-9fe3-02bc17b1abc4.png">

And in the tab Summary I have this:
<img width="913" alt="screen shot 2017-07-03 at 19 34 31" src="https://user-images.githubusercontent.com/188946/27802883-cb41e7aa-6026-11e7-936d-e17b4139dfcc.png">

What I expect is to have a curl command starting by `curl -X HEAD` and not `curl -X GET`.

**Comment by stevecrozz** [comment]
Thanks for the report. I understand what you're seeing now. This is the logic we have for figuring out the "curl" command:
https://github.com/errbit/errbit/blob/v0.6.1/app/models/notice.rb#L98

It looks like it is expected that there will be a `REQUEST_METHOD` in the reported environment, but I see that you have a different env variable called `HTTPMETHOD`.

I suppose we can add HTTPMETHOD as a fallback to fix the issue for you, but this has me wondering if there's really value in this feature. It seems clear that its only designed to work with Rack servers and this seems like a pretty brittle implementation. It wouldn't work for any of the applications that I administer, except for maybe Errbit.

Do you get value out of this feature @jonathantribouharet?

**Comment by jonathantribouharet** [comment]
I don't need it, now I know the problem but I supposed I'm not the only one who may have this problem, and I don't understood why I had a crash because I was trying with a GET. It's a Rails app, without fancy configuration, and i only have the problem with head request. I don't know why the REQUEST_METHOD is not set and why the browser make this requests, it's only for some of my users.

**Comment by stevecrozz** [comment]
Thanks for pointing this out. I'm going to get rid of this feature because I don't see a way to make this reliable/maintainable. It would be really handy if it worked, but every server is so dramatically different there's just no way we can do this well on Errbit's side.
