### ISSUE TITLE
With updated gems, 'kaminari-mongoid' is required

### ISSUE THREAD

**Issue by zedalaye** [errbit/errbit#1208]
I just upgraded my Errbit instance to current master, run `bundle update` (that updated tons of gems like kaminari...) and I run into this error:

```
NoMethodError: undefined method `page' for #<Mongoid::Criteria:0x007fd80e7ac478>
```

I found at StackOverflow that the solution to this problem was to install 'kaminari-mongoid' (https://stackoverflow.com/a/43573106/258622) . I simply added that gem to UserGemfile and I got my Errbit back.

**Comment by stevecrozz** [comment]
This is good to know about for whenever we upgrade gems. But I don't plan on making a change here as we don't need to support arbitrary `bundle update`. The Gemfile.lock to defines exactly the gem versions that are known to work with Errbit and that should be all we need.
