### ISSUE TITLE
any reason why mongoid is locked down to a 2y old version?

### ISSUE THREAD

**Issue by darix** [errbit/errbit#1212]
just wondering

**Comment by darix** [comment]
jquery-rails is even older

**Comment by stevecrozz** [comment]
There's no good reason too keep using these old versions other than this hasn't yet made it onto my list of priorities. Are you volunteering? I'd appreciate the help :) If you are, I'd recommend tackling these two items separately.

**Comment by rud** [comment]
We're past this now, thankfully
