### ISSUE TITLE
ERRBIT_PORT not used when generating redirect_uri for GitHub auth

### ISSUE THREAD

**Issue by jhelwig** [errbit/errbit#1220]
It looks like GitHub recently started being more strict about checking the `redirect_uri` against the configured OAuth app settings, since we started getting the following when trying to log in to Errbit using GitHub auth:

```
Could not authenticate you from GitHub because "The redirect uri must match the registered callback url for this application.".
```

We already set `ERRBIT_PORT` to `443`, but the `redirect_uri` that ends up in the GitHub login URL is for `https://<our-host>:8080/users/auth/github/callback`.

**Comment by jimmycuadra** [comment]
I think this could be fixed with something along these lines being called at the appropriate time during application start up:

``` ruby
OmniAuth.config.full_host = "#{Errbit.config.protocol}://#{Errbit.config.host}:#{Errbit.config.port}" if Errbit.config.protocol && Errbit.config.host && Errbit.config.port
```

**Comment by jhelwig** [comment]
More specifically, the problem appears to be that when running the official Errbit Docker container in Kubernetes, the default host detection logic sees the port that Kubernetes is using to talk with Docker, and not the port that users use to talk with Errbit. Respecting `ERRBIT_PORT` (and the related `ERRBIT_*` settings to set `OmniAuth.config.full_host`would fix this.

**Comment by jklimke** [comment]
The above solution will probably break oauth authentication for errbit instances that are deployed as a docker container behind a HTTP server handling the SSL encryption - errbit is usually running not on the same port within the container as its public endpoint (e.g. public port 443, docker instance port 8080).

Probably there needs to be another configuration parameter to switch this

**Comment by jhelwig** [comment]
The above is actually to handle exactly that scenario. Errbit is running in a docker container on 8080, while there's an HTTP reverse proxy in front of it handling SSL termination.

**Comment by rud** [comment]
Anyone willing to make this a PR with a short test?
