### ISSUE TITLE
Support the X-Airbrake-Token header

### ISSUE THREAD

**Issue by boris-petrov** [errbit/errbit#1225]
I've been trying the [new Java airbrake notifier](https://github.com/airbrake/javabrake) however they are sending the API key via a `X-Airbrake-Token` header instead of as a query parameter (see [here](https://github.com/airbrake/javabrake/blob/9953317c70fe2307d91b8573a7588b6ea5db8611/src/main/java/OkSender.java#L53)). Errbit doesn't seem to support that. Is this a difficult one to implement? :)

**Comment by stevecrozz** [comment]
It should be easy to add support for this, but something doesn't make sense to me and I've raised an issue with javabrake. Hopefully they'll clarify: https://github.com/airbrake/javabrake/issues/17

**Comment by boris-petrov** [comment]
@stevecrozz - well, I already did open something like this: https://github.com/airbrake/javabrake/issues/16 - there they explain why they do it. :)

**Comment by stevecrozz** [comment]
Thanks. I didn't see that. I guess this may be an undocumented feature of the Airbrake API. Either that, or I didn't spot the place where this feature is described.
