### ISSUE TITLE
NPE in notice.rb

### ISSUE THREAD

**Issue by boris-petrov** [errbit/errbit#1229]
Sending a v3 notice without a `message` parameter causes the following exception:

```
NoMethodError (undefined method `gsub' for nil:NilClass):
  app/models/notice.rb:117:in `filtered_message'
  app/models/notice_fingerprinter.rb:19:in `generate'
  app/models/error_report.rb:136:in `fingerprint'
  app/models/error_report.rb:119:in `error'
  app/models/error_report.rb:55:in `generate_notice!'
  app/controllers/api/v3/notices_controller.rb:22:in `create'
```

According to the [documentation](https://airbrake.io/docs/api/#create-notice-v3), `message` is not a mandatory field.

**Comment by rud** [comment]
Reading the backtrace, https://github.com/errbit/errbit/blob/61fee89a7ea77f30ba205f284899a506a2959f02/app/models/notice_fingerprinter.rb#L19 no longer calls `filtered_message` when the message is `nil`, so this issue is fixed in `master`.

Thank you for reporting it @boris-petrov! 🥇
