### ISSUE TITLE
Deployment on now.sh

### ISSUE THREAD

**Issue by ProGM** [errbit/errbit#1230]
Dear maintainers,
I've been using errbit for a while in my projects. Recently I discovered a new deployment platform, [`now`](http://now.sh).

It can easily deploy dockerized projects and it's free for small environments.

I've written a guide to deploy there:

https://github.com/ProGM/errbit/blob/deploy-on-now/docs/deployment/now.md

Would you accept a Pull request?

I have a small concern about my guide:
Since it's impossible to run sh commands in the `now` environment, running `rake errbit:bootstrap` is a big problem.
I've proposed two solutions, but I don't like them very much. If you have better solutions, I'm open to any suggestion.

Thank you

**Comment by stevecrozz** [comment]
I'm not too keen on maintaining support / documentation for new strategies, but I wouldn't mind linking to yours if you plan to maintain it. We could include a link on the deployment strategies page if you'd like to add a pull request: https://github.com/errbit/errbit/blob/master/docs/deployment.md

I would just want to make sure its clear that this strategy is not maintained by errbit. Eventually, I'd like to remove capistrano and heroku as supported strategies also.

**Comment by rud** [comment]
Please feel free to open a pull-request @ProGM if you want to maintain the installation guide going forward. Thanks!
