### ISSUE TITLE
How to set component, action, and environment name in notices?

### ISSUE THREAD

**Issue by activeshadow** [errbit/errbit#1231]
I'm using both the `airbrake-ruby` and the `gobrake` client libraries in my code, and I'm wondering how I go about setting the notice fields that map to the `component`, `action`, and `environment name` fields available in the **Notice Fingerprinter** configuration.

Can someone point me in the right direction?

**Comment by stevecrozz** [comment]
Should be these fields:
https://airbrake.io/docs/api/#create-notice-v3

context.component, context.action and context.environment. Are they not working as expected?

**Comment by activeshadow** [comment]
Ah... OK, thanks @stevecrozz. I wasn't aware of those and will try them now. Thanks!

I'll close this once I've tried and confirmed your suggestion.

**Comment by rud** [comment]
Closing out this old issue
