### ISSUE TITLE
Errbit fails to start on OpenShift

### ISSUE THREAD

**Issue by SuhailParmar** [errbit/errbit#1232]
Hi,

```
`/` is not writable.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
Could not locate Gemfile or .bundle/ directory
``` 

This error is thrown when I run errbit on openshift. I believe the problem is due to OpenShift controlling which user the applciation runs as. A possible cause could be these lines in the Dockerfile.

```
RUN mkdir -p /app \
  && chown -R errbit:errbit /app \
&& chmod 700 /app/
```

Would you accept a pull request where I keep the files readable by all users? 

Thanks,

Suhail

**Comment by stevecrozz** [comment]
It wouldn't bother met to change to a world readable app folder (755 or even 775). But if possible I'd like to understand a little bit about how this works in OpenShift. Do you have a link to any relevant docs that explain why it doesn't work in its current state?

**Comment by SuhailParmar** [comment]
Sure, OpenShift itself has capabilities to allow containers to be run as root but to conform to best security practices containers shouldn't run as root. 
 https://medium.com/bitnami-perspectives/running-containers-in-openshift-629af79945b5
 https://docs.openshift.com/enterprise/3.2/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile

Even if a user is specified in the Dockerfile OpenShift seems to ignore it. Furthermore changing the permissions to 701 && 704 gave the same error, referenced in the issue.

In regards to the change i've tested 705 to be sufficient, just for transparency i've attached the pull request :)

**Comment by stevecrozz** [comment]
I've got no objections. Thanks for the explanation.
