### ISSUE TITLE
Support key passed through Authorization header

### ISSUE THREAD

**Issue by tindron** [errbit/errbit#1236]
As of airbrake-ruby 2.5.1 the project key is passed through the Authorization header instead of as a query param.  (https://github.com/airbrake/airbrake-ruby/pull/278)

**Comment by zealot128** [comment]
Just run into the problem but didn't found this issue. 
I will just add the error message from the Airbrake client here to help further Googler's that run into the problem:

```
# Airbrake.notify(StandardError.new)
# => #<Airbrake::Promise:0x0000000003b62d50 @on_resolved=[], @on_rejected=[], @value={}, @mutex=#<Thread::Mutex:0x0000000003b62c38>>
# E, [2017-12-22T09:39:07.073604 #25052] ERROR -- : **Airbrake: unexpected code (422). Body: Your API key is unknown
```
