### ISSUE TITLE
Errbit display "We're sorry, but something went wrong. We've been notified about this issue and we'll take a look at it shortly."

### ISSUE THREAD

**Issue by sumi-kumar** [errbit/errbit#1243]
While hitting errbit url it display:

We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.

**Comment by stevecrozz** [comment]
Thanks for the report. In order to troubleshoot, I'll need to take a look at the logs from the time of the error. Can you recover the relevant log information?

**Comment by sumi-kumar** [comment]
Sorry, but don't have logs. Could you please suggest me what to do as I am in great trouble!!!!

**Comment by stevecrozz** [comment]
Unfortunately not. The application logs are the only place where we can spot the error. There's really no other way to find the problem. Please reopen this if you can get the logs and need help understanding them.
