### ISSUE TITLE
Document ERRBIT_ADMIN_USER, ERRBIT_ADMIN_EMAIL and ERRBIT_ADMIN_PASSWORD

### ISSUE THREAD

**Issue by tmaier** [errbit/errbit#1245]
https://github.com/errbit/errbit/blob/master/db/seeds.rb

ERRBIT_ADMIN_USER, ERRBIT_ADMIN_EMAIL and ERRBIT_ADMIN_PASSWORD can be set to help define the admin user

They are missing at https://github.com/errbit/errbit/blob/master/docs/configuration.md

This is related to Pull Request #1221

**Comment by rud** [comment]
Thanks for reporting this issue. Would you be willing to add a quick PR fixing this?
