### ISSUE TITLE
While accessing errbit url I am getting something went wrong error

### ISSUE THREAD

**Issue by sumi-kumar** [errbit/errbit#1246]
We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.

On google console:

Failed to load resource: the server responded with a status of 502 (Bad Gateway

**Comment by stevecrozz** [comment]
I'm afraid we can't look into this without some information from the application logs. Apologies for taking so very long to answer. If you want to try again, please do and if you have any application errors from the logs, we'll look into them.
