### ISSUE TITLE
Remove support for outdated versions of mongodb

### ISSUE THREAD

**Issue by stevecrozz** [errbit/errbit#1253]
Update readme files, docker-compose, travis config and anything else to point to currently supported versions of mongodb. Apprently, there is at least one reason we can't yet support v3.6 as discovered by @rud in https://github.com/errbit/errbit/pull/1250#issuecomment-355765369. Relevant links below:

https://www.mongodb.com/support-policy
https://docs.mongodb.com/v3.2/reference/operator/update/pushAll/#up._S_pushAll

**Comment by rud** [comment]
So, turns out the `mongoid` gem does not support mongodb 3.6-series yet. One of the issues is this: https://jira.mongodb.org/projects/MONGOID/issues/MONGOID-4499

Version 3.4 of mongodb seems reasonable maximum to aim for for now.
