### ISSUE TITLE
Empty environment variable crashes Configurator

### ISSUE THREAD

**Issue by psukys** [errbit/errbit#1261]
If there's an empty environment variable, `YAML.parse` returns `false`, which does not have `to_ruby` method.

Related https://github.com/errbit/errbit/blob/8024da5761a2cf069255957633e03dae129f8118/lib/configurator.rb#L60

For verification:
```
YAML.parse('').to_ruby
```
Generates the error as well.

**Comment by rud** [comment]
If you are at all able to provide a test and a fix we can get this fixed in no time. 🙏thanks!
