### ISSUE TITLE
Suggestion: setup depfu (free) to keep up with gem updates easily

### ISSUE THREAD

**Issue by rud** [errbit/errbit#1265]
See more at https://depfu.com

**Comment by rud** [comment]
I'll add merge-requests for minor and major dependency updates, so CI can automatically verify what'll work. Should make maintenance a bit easier. Thoughts?

**Comment by rud** [comment]
Ping @stevecrozz, would love your input on this - think it's a good simplification on having bots to make the PRs that only change Gemfile/Gemfile.lock

**Comment by stevecrozz** [comment]
I'm down to try it. Are you familiar with this system already? Would it mean we get nagged for every minor release of every gem? Or are there some settings to keep it more reasonable?

**Comment by rud** [comment]
I think it'll drip in PRs at a rate matching when gems are updated. I think it's a low effort thing to try out - and I know there are other similar projects available. 

I've seen this one be helpful in the past.

**Comment by stevecrozz** [comment]
Ok @rud. I have enabled this gem. First PR is open: https://github.com/errbit/errbit/pull/1285 so I'll close this issue.

**Comment by rud** [comment]
Awesome. The upgrade backlog is now visible - seems there is some work to do :)
