### ISSUE TITLE
Setup Heroku Pipeline to auto-create review apps from PRs

### ISSUE THREAD

**Issue by rud** [errbit/errbit#1280]
It should take a few minutes only to setup - [steps here](https://devcenter.heroku.com/articles/github-integration-review-apps). 

With that in place, a Heroku app will be spawned for each PR that comes in, for easier testing.

**Comment by stevecrozz** [comment]
I think I enabled review apps on new PRs. I can't remember if we still autogenerate username/password, but we may need to adjust that if we want to be able to log in to these review apps.

**Comment by rud** [comment]
This is now enabled. We just need to debug it so it's actually possible to login and check stuff. Maybe adding some demo data as well would be nice. That's all in the future. 

Thanks for this @stevecrozz !

**Comment by stevecrozz** [comment]
Excellent. No prob!
