### ISSUE TITLE
Feature request: add/remove ignores on specified exceptions

### ISSUE THREAD

**Issue by alsor** [errbit/errbit#133]
There are cases, when application periodically reports some exceptions, that are not critical and rather treated as "normal behavior". Maybe those are exceptions that can't be fixed right now, or exceptions from libraries, but everybody knows that application can live OK with them for now.

It would be great to have the ability to dynamically add and remove ignores on such exceptions through the web interface (not config). Maybe by regexp pattern or something else that can be suitable.

**Comment by raddrick** [comment]
Heroku gives a SIGTERM error everytime a dyno shuts down, its not an issue and is normal behaviour.

**Comment by sasharevzin** [comment]
Here is Heroku's exception:
![Slack___fiu-behaviortracking___Blue_Whale_Apps](https://user-images.githubusercontent.com/232392/69167442-fd6e0300-0ac2-11ea-8231-8cb133c232ad.png)

**Comment by goetzc** [comment]
@sasharevzin, add this to the Airbrake initializer:

```ruby
Airbrake.add_filter do |notice|
  notice.ignore! if notice[:errors].any? do |error|
    error[:type] == 'SignalException' && error[:message] == 'SIGTERM'
  end
end
```
