### ISSUE TITLE
NoMethodError: undefined method `include?' for 0:Integer

### ISSUE THREAD

**Issue by kirylpl** [errbit/errbit#1338]
### Step 2: Describe your environment

  * Errbit version: 0.8.0 dev
  * OS: Heroku environment

### Step 3: Describe the problem:

NoMethodError: undefined method `include?' for 0:Integer on Self.Errbit while catching 3rd party apllication error

#### Steps to reproduce:

  1. Install errbit on heroku, ruby 2.5
  2. Catch the error from 3rd party app (for example non existing template in my case) with Airbrake 5.8 or 5.6
  3. Catch both Self.Errbit and 3rd party app errors as well

#### Application Logs:

`
[PROJECT_ROOT]/models/error_report.rb:84→ should_email?
--
[PROJECT_ROOT]/models/error_report.rb:90→ email_notification
[PROJECT_ROOT]/models/error_report.rb:59→ generate_notice!
[PROJECT_ROOT]/controllers/api/v3/notices_controller.rb:24→ create
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/implicit_render.rb:4→ send_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/abstract_controller/base.rb:198→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/rendering.rb:10→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/abstract_controller/callbacks.rb:20→ block in process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:117→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:555→ block (2 levels) in compile
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92→ __run_callbacks__
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778→ _run_process_action_callbacks
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:81→ run_callbacks
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/abstract_controller/callbacks.rb:19→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/rescue.rb:29→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:32→ block in process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164→ block in instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:30→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/params_wrapper.rb:250→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/abstract_controller/base.rb:137→ process
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionview-4.2.10/lib/action_view/rendering.rb:30→ process
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal.rb:196→ dispatch
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal/rack_delegation.rb:13→ dispatch
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_controller/metal.rb:237→ block in action
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:74→ dispatch
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:43→ serve
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:43→ block in serve
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:30→ each
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:30→ serve
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:817→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:190→ call!
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:190→ call!
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/rack-ssl-enforcer-0.2.9/lib/rack/ssl-enforcer.rb:52→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:36→ block in call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35→ catch
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/rack-1.6.10/lib/rack/etag.rb:24→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/rack-1.6.10/lib/rack/conditionalget.rb:38→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/rack-1.6.10/lib/rack/head.rb:13→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/params_parser.rb:27→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/flash.rb:260→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/rack-1.6.10/lib/rack/session/abstract/id.rb:225→ context
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/rack-1.6.10/lib/rack/session/abstract/id.rb:220→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/cookies.rb:560→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/callbacks.rb:29→ block in call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:88→ __run_callbacks__
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778→ _run_call_callbacks
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:81→ run_callbacks
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/callbacks.rb:27→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/remote_ip.rb:78→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:17→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38→ call_app
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:22→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/rack-1.6.10/lib/rack/methodoverride.rb:22→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/rack-1.6.10/lib/rack/runtime.rb:18→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/static.rb:120→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/rack-1.6.10/lib/rack/sendfile.rb:113→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails[PROJECT_ROOT]lication.rb:165→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/rack-1.6.10/lib/rack/deflater.rb:35→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:225→ call

[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:658→ handle_request
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:472→ process_client
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:332→ block in run
[PROJECT_ROOT]/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133→ block in spawn_thread

`

**Comment by kirylpl** [comment]
Well, I got the reason. I had 0 instead [0]  in email configuration.

**Comment by rud** [comment]
Ah, thank you for the extra detail. What would be the preferable way of reporting such a configuration issue in the future? An explicit exception at this location, insisting that an array must be given in the config?

**Comment by kirylpl** [comment]
@rud On your taste. Explicit exception will be absolutely acceptable protection from the fools :)
