### ISSUE TITLE
No route matches errors with problems#*_several actions

### ISSUE THREAD

**Issue by kyamaguchi** [errbit/errbit#1341]
* Errbit version: a291aa9
  * Tested on heroku

#### Steps to reproduce:

  1. Go to /problems
  2. Select errors
  3. click Resolve

#### Observed Results:

  * Gets 404 error (No route matches)

#### Expected Results:

  * Resolve errors

Application Logs:

```
heroku[router]: at=info method=POST path="/apps/5b66858b4edac90006873674" host=errbit-a291aa9.herokuapp.com request_id=8714e2ae-3b35-4565-a8e0-c5d4bbe26726 fwd="203.140.149.93" dyno=web.1 connect=0ms service=41ms status=404 bytes=692 protocol=https

Started POST "/apps/5b66858b4edac90006873674" for 203.140.149.93 at 2018-08-05 05:13:01 +0000

ActionController::RoutingError (No route matches [POST] "/apps/5b66858b4edac90006873674"):
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
```

#### Screenshots:

<img width="903" alt="select_errors" src="https://user-images.githubusercontent.com/275284/43682854-cfa19cdc-98ba-11e8-8880-eb78060f44b8.png">
<img width="732" alt="resolve_issues" src="https://user-images.githubusercontent.com/275284/43682856-d3009c20-98ba-11e8-91a0-bc199f414c7a.png">
<img width="685" alt="404error" src="https://user-images.githubusercontent.com/275284/43682858-d713bb08-98ba-11e8-9147-d046b5b8cbab.png">

-----

It was OK to resolve issues individually.

<img width="745" alt="resolve_individually" src="https://user-images.githubusercontent.com/275284/43682860-db154352-98ba-11e8-8d7f-837c32bd0f19.png">

**Comment by stevecrozz** [comment]
Thanks very much for the report @kyamaguchi. I have a fix started at https://github.com/errbit/errbit/pull/1342.

The javascript environment is a gap in our automated testing right now.

**Comment by stevecrozz** [comment]
Should be fixed now.
