### ISSUE TITLE
Some of the errors are not logged and gives 500 errors

### ISSUE THREAD

**Issue by djdon11** [errbit/errbit#1352]
I have installed errbit on heroku and point my rails application there(with airbrake gem) now I am able to my rails application errors to errrbit but not all issues, some of the issues gives me internal server errors(500) but when I tried to install errbit at my local then I am able to log all errors.
I am not sure why that is failing on production mode on heroku server.

This is the error:
Reporting to: https://rpm.newrelic.com/accounts/1365745/applications/25376613
E, [2018-08-07T13:57:46.112534 #4] ERROR -- : **Airbrake: unexpected code (500). Body: <!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <style t...
E, [2018-08-07T13:57:46.193827 #4] ERROR -- : **Airbrake: unexpected code (500). Body: <!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <style t...
rake aborted!

**Comment by rud** [comment]
Would you mind taking a look at the logs in Heroku, see if anything interesting is there?

**Comment by djdon11** [comment]
Yes I have tried to see heroku logs but there is nothing helpful related to error

**Comment by djdon11** [comment]
I have found the issue that is due to mongo db table size, thats why it was returning 500

**Comment by rud** [comment]
Thank you for reporting back on this. Was there an error you saw somewhere we could have caught and reported on? I mean, it would be super helpful not to have to play Sherlock Holmes the next time this kind of thing happens to someone 🍎

**Comment by apanzerj** [comment]
Sigh. Same issue here and sadly, they aren't coming back.
