### ISSUE TITLE
Can't merge errors after search

### ISSUE THREAD

**Issue by keithlayne** [errbit/errbit#1385]
### Step 1: Are you in the right place?

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged with errbit.

### Step 2: Describe your environment

  * Errbit version: 0.8.0-dev (via docker image)
  * OS: linux

### Step 3: Describe the problem:

Merging selected issues after search generates a routing error.

#### Steps to reproduce:

  1. Go to an app page
  2. Use the search field to search for a term
  3. Select some errors via checkboxes
  4. Click 'merge'

#### Observed Results:

  * What happened?  This could be a description, log output, etc.

Generic 404 error page.

#### Expected Results:

  * What did you expect to happen?

Successful merge - this used to work, unfortunately I don't have version details for that.

#### Application Logs:

  * Please include any relevant logs, especially if you encountered an
    application error.

```
Started POST "/problems/search" for 100.96.12.30 at 2018-11-05 18:46:05 +0000

ActionController::RoutingError (No route matches [POST] "/problems/search"):
  actionpack (4.2.10) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.10) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.10) lib/rails/rack/logger.rb:22:in `call'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.10) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.10) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.10) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.10) lib/rack/sendfile.rb:113:in `call'
  hoptoad_notifier (2.4.11) lib/hoptoad_notifier/user_informer.rb:12:in `call'
  railties (4.2.10) lib/rails/engine.rb:518:in `call'
  railties (4.2.10) lib/rails/application.rb:165:in `call'
  rack (1.6.10) lib/rack/deflater.rb:35:in `call'
  puma (3.12.0) lib/puma/configuration.rb:225:in `call'
  puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
  puma (3.12.0) lib/puma/server.rb:472:in `process_client'
  puma (3.12.0) lib/puma/server.rb:332:in `block in run'
  puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by glampr** [comment]
The same things happens when trying to mass delete errors after searching.

**Comment by sasharevzin** [comment]
Closing the issue?

**Comment by stevecrozz** [comment]
Good call @sasharevzin
