### ISSUE TITLE
Are there plans for a v0.8.0 release?

### ISSUE THREAD

**Issue by floehopper** [errbit/errbit#1428]
Thanks for all your work on the project. It looks as if there have been [quite a few changes since v0.7.0](https://github.com/errbit/errbit/compare/v0.7.0...master) which was released in June last year. Are there any plans to for a new release any time soon?

**Comment by stevecrozz** [comment]
I made a v0.9.0 release today

**Comment by floehopper** [comment]
Great - many thanks! 😄
