### ISSUE TITLE
NoMethodError: `dig' for BSON::Document

### ISSUE THREAD

**Issue by espen** [errbit/errbit#1433]
* Errbit version: 0.7.0 from master
  * OS: Heroku

1. Show problem.

2. Error is logged:

> NoMethodError: undefined method `dig' for {"_id"=>{"year"=>2019, "day"=>94}, "count"=>19}:BSON::Document

Controller: problems#xhr_sparkline

Error at /models/problem.rb:263

**Comment by stevecrozz** [comment]
Which version of Ruby are you using @espen ? I haven't dug in too deep yet, but I see that there is a test that covers this method and it is passing under Ruby 2.5.1 when I run it.

**Comment by espen** [comment]
2.6.2p47

**Comment by espen** [comment]
Sorry my fault - I was running 2.3.2 🤦‍♂️
Turns out errbit doesn't use .ruby-version but instead uses ENV['GEMFILE_RUBY_VERSION']
