### ISSUE TITLE
Issue Trackers - Poll for comments/status changes on created issues

### ISSUE THREAD

**Issue by ndbroadbent** [errbit/errbit#145]
Periodically fetch issue data over the issue tracker's API. Cache and display any external comments, and automatically resolve the error if the issue ticket is closed.
In this case, perhaps Errbit's internal comments should either be disabled, or pushed to the issue tracker.

Will only be implemented for Github Issues and Mingle, unless other developers can help for the other trackers.

**Comment by arthurnn** [comment]
This will probably add a big chunk of complexity to the issue tracker code.. as nobody picked this in almost 3 years I will close this. Fell free to send a PR with you have the code ready.
