### ISSUE TITLE
How to explore a list of errbit plugins

### ISSUE THREAD

**Issue by kalashnikovisme** [errbit/errbit#1488]
Hi, everyone!

Can't find a list of available errbit plugins. Could you please post something about it.

Or maybe if it does exist, we should create this.

**Comment by stevecrozz** [comment]
That seems like a good idea. Back when I used to spend more time working on Errbit, I had big dreams for plugins, including notifiers etc, but the only type of plugin we currently have is issue trackers. The ones I know about are the ones we created to support users who had previously been using the core issue trackers when they were part of errbit. At the time, the of plugins we created was:

- errbit_bitbucket_plugin
- errbit_fogbugz_plugin
- errbit_github_plugin
- errbit_gitlab_plugin
- errbit_jira_plugin
- errbit_lighthouse_plugin
- errbit_pivotal_plugin
- errbit_redmine_plugin
- errbit_unfuddle_plugin

There are probably more, but these are the ones I'm already aware of. If you'd like to start a wiki page to catalog these, that would be great.

**Comment by stevecrozz** [comment]
I'm going to close this one. If you'd like to make a wiki entry, you are welcome to do it. I think you should have permission, but let me know if you're not able.

**Comment by kalashnikovisme** [comment]
@stevecrozz I do not prefer wiki because it's not copying to forks, as I know. Maybe, we can add the list of plugins to README. This list should not overload it. In time when the list of plugins will be bigger and we'll have process to manage them, we'll move this list to another place.

What do you think about it?

**Comment by stevecrozz** [comment]
I'm fine with this. You're welcome to propose the change via pull request
and I can merge it.
