### ISSUE TITLE
XSS in user attributes

### ISSUE THREAD

**Issue by 2called-chaos** [errbit/errbit#1489]
* Errbit version: master
  * OS: Ubuntu 18.04

#### Steps to reproduce:

  1. Create a user with malicious name/username in your app
  2. Cause an exception while logged in with that user
  3. Errbit's `notices/_user_attributes` partial executes XSS

#### Observed Results:

  * XSS through `.html_safe`-ing attributes (because of Rinku auto link)

#### Expected Results:

  * No XSS :)

#### Cause

https://github.com/errbit/errbit/blob/e9ca15b842521d2ae536590c57c3db61fef19a3e/app/views/notices/_user_attributes.html.haml#L10

I'm not sure how to easily fix this but also keeping autolinking

#### Example

The thankfully friendly attacker delivered an example. The user caused the exception due to a missing length validation but every exception caused by a user might send untrusted data that shouldn't be blindly html_safe'd by errbit

```
"user" => {
    "name" => "\"><img src=x onerror=alert('1');> \"/><img src=x onerror=prompt(navigator.userAgent)>  \"><img/src=\"x\"/onmouseover=prompt(document.domain);>  \"/><svg/onload=prompt(document.domain)>   \"><svg/onload=prompt(document.cookie);>  “-prompt`1`-”//  \"><svg/onload=alert(document.domain);>  \"><svg/onload=prompt(123);>  \"><img src=x onerror=prompt(\"XSS-Vulnerability\");>  /?regionConfirm=alert(document.cookie)});}}%3C/script%3E  \"--></style></scRipt><scRipt>alert(\"shaniXss\")</scRipt>  \"></code><svg/onload=prompt(1)>"
}
```

<img width="783" alt="Errbit — Mysql2::Error: Data too long for column 'name' at row 1 2021-02-13 15-53-36" src="https://user-images.githubusercontent.com/218011/107852942-bb418780-6e13-11eb-9ccb-e4dc3296ebe1.png">

**Comment by stevecrozz** [comment]
Thanks for the report! Probably the solution here is to simply not autolink and not mark this as html_safe. I'm fine with losing the autolink email address feature if that's all it was.

**Comment by 2called-chaos** [comment]
I'm not sure if users currently using intentional HTML there but what do you think about #1490?

Keeps autolinking which is frankly handy for something like the admin-hotlink for users but escapes the input beforehand.

![Errbit — Mysql2__Error_ Data too long for column 'name' at row 1 - Google Chrome 2021-02-19 15 20 55](https://user-images.githubusercontent.com/218011/108516286-53cd8100-72c6-11eb-8896-c05574e6a461.png)

**Comment by stevecrozz** [comment]
That works for me. Nice going.
