### ISSUE TITLE
Remove Hipchat (discontinued service)

### ISSUE THREAD

**Issue by 2called-chaos** [errbit/errbit#1499]
Hipchat depends on mimemagic which had license issues and got all it's legacy versions yanked. The new version (via #1498), despite being a patch version increase, [introduces a new system dependency](https://github.com/mimemagicrb/mimemagic#dependencies).

We should either add notes to the installation instructions or drop Hipchat entirely. Hipchat is discontinued (basically became Slack) but was also available as a self-hosted enterprise solution and I don't know if these still operate somewhere.

I think linux should be unaffected but Mac/Windows and ~~potentially~~ Docker requires the system dependency to be fulfilled specifically.

**Comment by stevecrozz** [comment]
I've never used it and I think you're right. It doesn't look like we need to support this notifier any longer.
