### ISSUE TITLE
User can't login after restore from old db to new db on docker machine

### ISSUE THREAD

**Issue by leminhphap2607** [errbit/errbit#1501]
I just finished creating an errbit using docker and the db that I restore from localhost. Currently I can see all information about the app and users, however I can't login these users, it shows invalid username or password. Can someone tell me what's going on?

**Comment by stevecrozz** [comment]
Seems like the most likely explanation is that the new errbit instance is not finding your restored db. To verify, see if you can access your data using the mongo cli from this or another docker container launched with the same parameters. Your data should be reachable using whatever connection string you provided to errbit in the MONGO_URL environment variable. My best guess is the database you are expecting is not available using the connection string provided in MONGO_URL. Hope this helps!

**Comment by leminhphap2607** [comment]
Hi Stevecrozz,
I updated connection string of db to .env file in docker, and i fixed this issue, in file devise.db i uncomment confid.pepper and it's work. You can close this ticket now.
Thanks

**Comment by stevecrozz** [comment]
Glad you're up and running!
