### ISSUE TITLE
docker image errbit/errbit:latest

### ISSUE THREAD

**Issue by nijikon** [errbit/errbit#1512]
Can we update `errbit/errbit:latest` docker image on docker hub (https://hub.docker.com/r/errbit/errbit)? What is the procedure for that? The last update was 10 months ago.

**Comment by stevecrozz** [comment]
We used to get this on every commit with the dockerhub GitHub integration
and trusted builds. Dockerhub no longer provides this public service for
free. They do have an open source account and I have applied on behalf of
errbit, but haven't heard back yet. If anyone at @docker is listening, can
you bump us up the queue a bit? I can push builds but trust-wise seems a
little iffy for folks to be deploying builds I generate with no paper
trail. Maybe there's other options? Does GitHub provide anything for this
use case now?

**Comment by nijikon** [comment]
@stevecrozz let me know if there is anything I can help you with in regards to this issue.

**Comment by stevecrozz** [comment]
Do you want to see if GitHub actions can be used to build and publish
images to dockerhub? It seems like that should work and if you can get it
working I'd be happy to accept a PR

**Comment by nijikon** [comment]
@stevecrozz sounds good, will give it a shot this week.

**Comment by shreve** [comment]
There is now an action in place that will update `:latest` from main, as well as create semver images whenever a new tag is pushed.

https://github.com/errbit/errbit/actions/workflows/publish.yml

**Comment by stevecrozz** [comment]
Thanks @shreve !

**Comment by xxz3** [comment]
I have a problem with `errbit:latest` image from dockerhub. When building image it can't find puma gem:

```
errbit_1  | bundler: command not found: puma
errbit_1  | Install missing gem executables with `bundle install`
errbit_errbit_1 exited with code 127
```

`errbit:v0.9.0` works fine. Do you have any hint on how to build the latest version?

**Comment by shreve** [comment]
@xxz3 I'm not able to reproduce this issue, but whatever is going on its not tied to this issue. `errbit:latest` is now updated based on the main branch automatically, so if there really is a problem, it's a new issue.
