### ISSUE TITLE
Add to notification services the option to send notifications only for specific environment 

### ISSUE THREAD

**Issue by joshdvir** [errbit/errbit#269]
I will give this example from my workflow, when I work on a project I have 3 environments, development staging and production like most developers / companies this is very common but when I work for example on a project with other developers I like telling them to open Errbit error reporting also to there development environment so that I can see the errors they are having so I can help them quickly.
So for this reason I think that some notification services should only be sent for specific environment like production, for example I don't want to receive SMS notifications for development or staging errors.

**Comment by lucianosousa** [comment]
Update. I just create one project for each env.
Works better in the end.

Cheers
