### ISSUE TITLE
Could not authorize you from Github because "Invalid credentials".

### ISSUE THREAD

**Issue by talyric** [errbit/errbit#276]
I believe I have followed all the instructions for setting up the application on Heroku and using GitHub for sign in, but I only receive the above error.  GitHub shows that users are being added to the "Developer Applications" section for the app and users are showing the the app is authorized.  I've done a bunch of searching, but have not found a solution.  Not sure where to start troubleshooting.  Any ideas?

**Comment by NaveenAmbulapodi** [comment]
please Post a relevent answer
