### ISSUE TITLE
Split README into wiki pages, add crossorigin="anonymous" info for js notifier

### ISSUE THREAD

**Issue by ndbroadbent** [errbit/errbit#380]
Add notes about javascript notifier not sending full error reports unless external script tags have crossorigin="anonymous" attribute. (Only affects scripts loaded from a different domain, e.g. on a CDN.)

**Comment by stevecrozz** [comment]
We have been splitting the readme file into chunks in the ./doc folder so that's at least partly solved. We also got rid of our javascript notifier, so the second part no longer applies :)
