### ISSUE TITLE
Better support for JS errors

### ISSUE THREAD

**Issue by ndbroadbent** [errbit/errbit#385]
I've been spending a bit of time trying to get JavaScript errors working properly. Here's some notes:

* `notifier.js` should be able to filter errors that happen in our own code. I'm currently doing this by checking if the file matches `assets/`
* `notifier.js` should ignore errors with message `Script error.` (Happens a lot from user-scripts, extensions, etc.)
* We should mention that airbrake supports `config.js_api_key`, if you want to set up a separate app for javascript errors.
* We could add support for tagging errors by source, and allow filtering by tags. i.e. Ruby, JavaScript, iOS. Or maybe it's just better to create separate apps for each source.

**Comment by ronin** [comment]
This can be closed now (https://github.com/errbit/errbit/pull/808)
