### ISSUE TITLE
Respecting Airbrake's Ignored Error Types

### ISSUE THREAD

**Issue by jerodsanto** [errbit/errbit#420]
I'm not sure if this is an Errbit issue, an Airbrake issue, Or perhaps just a Jerod issue :)

Airbrake is configured out of the box to ignore certain errors. On my server I have:

``` ruby
Airbrake.configuration.ignore
 => ["ActiveRecord::RecordNotFound", 
  "ActionController::RoutingError", 
  "ActionController::InvalidAuthenticityToken",
  "CGI::Session::CookieStore::TamperedWithCookie",
  "ActionController::UnknownAction",
  "AbstractController::ActionNotFound",
  "Mongoid::Errors::DocumentNotFound"]
```

However, my app still reports `ActionController::RoutingError`s to Errbit and Errbit still reports them to me. Is this expected behavior from Errbit?

**Comment by mdpatrick** [comment]
It seems that a lot of these exceptions might be nice to outline in a wiki article or in the docs somewhere. I expect most people don't care to have 404s (whatever their exception type) reported!
