### ISSUE TITLE
heroku asset compilation and mongoid

### ISSUE THREAD

**Issue by dommmel** [errbit/errbit#461]
Just updated my old installation and run into an issue.
Since ``config.assets.initialize_on_precompile`` is now set to ``true`` asset compilation on heroku fails when using mongoid with ``Failed to connect to a master node at localhost:27017``

the solution is to precompile assets locally - with the known drawbacks.
Since only one asset seems to require initialize_on_precompile to be true - maybe it is an option to remove that requirement and make heroku+mongoid run smoothly again?

cheers! Thanks for a great piece of software btw.

**Comment by arthurnn** [comment]
Docs already updated? closing this for now.thanks all
