### ISSUE TITLE
Document API

### ISSUE THREAD

**Issue by domurtag** [errbit/errbit#479]
According to this [Google Groups post](https://groups.google.com/forum/?fromgroups=#!topic/errbit/LpXab5JFPPY), Errbit has an [API](https://github.com/errbit/errbit/tree/master/app/controllers/api/v1) for reading data back out of Errbit.

There are no docs for this API, and apparently it's not the same as the Airbrake API, so the only way to figure out how to use it is to read the source code.

**Comment by tjnet** [comment]
I want to contribute this issue.
