### ISSUE TITLE
errbit.com expiring

### ISSUE THREAD

**Issue by sgrove** [errbit/errbit#496]
We have errbit.com, might be nice to point it at http://errbit.github.io/errbit/. Happy to renew and transfer to someone on this project (perhaps @ndbroadbent ?)

**Comment by stevecrozz** [comment]
The domain expired and is now registered to Deckers Outdoor Corporation. I'm going to attempt to contact them and see if we can get it back.

**Comment by stevecrozz** [comment]
I did manage to recover errbit.com from Deckers. They were quite helpful about doing this for us and I stood up the old github pages site for now.
