### ISSUE TITLE
Deploy Message via Airbrake Gem?

### ISSUE THREAD

**Issue by tresacton** [errbit/errbit#553]
Can somebody please advise whether or not it is possible to set a deploy message? If it is possible, please explain how.

If you need clarification for what I am asking for, please do the following: 
1. Navigate to the index page for apps
2. Notice the message column? For me this is always empty.

I want to fill this value in my other application's deploy.rb script, with the result of "git log --oneline -1" for the app being deployed.

**Comment by stevecrozz** [comment]
Added some documentation with #800

**Comment by tresacton** [comment]
Thanks. This is a very late reply, but that's exactly what I ended up doing.
