### ISSUE TITLE
Allow a user to see Errors without be a watcher

### ISSUE THREAD

**Issue by shingara** [errbit/errbit#561]
To see exception from an application, the user need to be admin or a watcher of this application.

It can be better to allow see exceptions without being a watcher of this application.

**Comment by mattclements** [comment]
I agree with you all on this - we make everybody Admin's so they can see everything.

Perhaps we have Watchers (notifications), and Access (pure access)?

**Comment by stevecrozz** [comment]
All users can now see all apps and follow / unfollow whichever apps they want. We may choose to add app-level access controls in the future, but if we do, the concept will no longer be conflated with 'following' an app.
