### ISSUE TITLE
Redmine issue integration should ask for tracker_id

### ISSUE THREAD

**Issue by brodock** [errbit/errbit#585]
Hello,

I would like to ask to have Redmine issue tracker_id as an option when setting up integration support.

tracker_id as can be seen on the API documentation: http://www.redmine.org/projects/redmine/wiki/Rest_Issues#Creating-an-issue is what makes possible to have a "Bug" issue type among "Features", or anything else. Without this option, it will always use the first issue type which is not always what people want.

I'm happy to do a merge request if someone could give me some guidance.

**Comment by arthurnn** [comment]
Closing this, fell free to create a errbit_redmine_plugin .. Thats how external issue trackers are suppose to be handled now.
thanks

**Comment by brodock** [comment]
I've sent a patch to them and it's already integrated. Thanks
