### ISSUE TITLE
Notify on marking an issue resolved

### ISSUE THREAD

**Issue by brendonrapp** [errbit/errbit#650]
My team enjoys the HipChat notifications when issues occur, but it would be very helpful to also get notifications when those issues are marked as resolved.

**Comment by mfrederickson** [comment]
@stevecrozz are you envisioning two new methods (`resolve_notification`and `unresolve_notification`) on each notification service, called from the problems_controller from the respective actions?

**Comment by stevecrozz** [comment]
I have doubts about whether or not this is important or even useful, although I may use Errbit differently from the way others use it. Personally, I never 'resolve' issues in Errbit and I'm not clear on what the value is in doing that. Maybe its worth a bit of discussion though. @mfrederickson do you think this feature would have some value?

On the other side of the equation, I do see value in keeping the codebase small and focused. So if all things are equal, I'd rather have less code than more.

**Comment by mfrederickson** [comment]
I would not use this feature either.  Small, focused sounds good to me.  Just trying to work off some open issues for you.

**Comment by stevecrozz** [comment]
Let's get rid of this, then. We did get a few users asking for it, but I'd like to hear more from them about why this would be useful before we add to the issue resolution components.
