### ISSUE TITLE
Issue ID could get lost

### ISSUE THREAD

**Issue by tmaier** [errbit/errbit#665]
Given I have two Errors.
I created for (the last one) of the two Errors a Github issue.
When I then select the two Errors and merge them, the Issue ID gets lost and is not present in the remaining Error.

**Comment by arthurnn** [comment]
The merged is suppose to merge only the errs and comments, https://github.com/errbit/errbit/blob/master/app/interactors/problem_merge.rb#L14-L15, and keep all the info from the main problem. So the issue link should be in the main problem. 

I just added a regression test https://github.com/errbit/errbit/commit/5ca251c58447226cd0390161282768f84cbcdecc to make sure this works.
