### ISSUE TITLE
LDAP authentication broken

### ISSUE THREAD

**Issue by luuse** [errbit/errbit#677]
Currently the LDAP authentication is broken. Gemfile.lock specifies devise 3.1.1 but the version of devise_ldap_authenticatable (0.7.x) that is compatible with Rails 3 requires devise ~> 2.0.

**Comment by felixbuenemann** [comment]
Is this still an issue? I'm running current master + ldap using devise_ldap_authenticatable (0.8.1) and it is working fine. I'm authenticating against an ActiveDirectory.

**Comment by arthurnn** [comment]
Thanks @felixbuenemann , I will close this until we find that it is not working.
