### ISSUE TITLE
Javascript errors cannot reach default handler

### ISSUE THREAD

**Issue by chpill** [errbit/errbit#678]
If there is no `window.onerror` function specified before the initialization of the notifier.js script, the notifier returns `true` (see https://github.com/errbit/errbit/blob/master/public/javascripts/notifier.js#L1191)... This prevents the use of the browser dev tools to inspect the error.

As the notifier script is often included before any javascript on a page (in order to catch syntax errors and so on...), it is not really convenient to append a `window.onerror` before it to avoid this behavior...

So my question is: is there really a reason not to return `false` by default at the end of the custom `window.onerror`?

**Comment by shivanibhanwal** [comment]
Hi @stevecrozz, I have just started with airbrake-js and errbit.
After making setting for Host, Project_id and Project_key issue which I ran into is 
API V3.
api/v3/projects/0/notices?key=dXXXXXXXX

**Comment by stevecrozz** [comment]
@shivanibhanwal I created a new issue to track API v3 support. If you want to help, you can start discussing a plan to support v3 in #803

**Comment by stevecrozz** [comment]
#808 adds api v3 support and documentation for using the airbrake-js notifier
