### ISSUE TITLE
Fingerprinting is broken

### ISSUE THREAD

**Issue by snikch** [errbit/errbit#681]
I see that there have been some updates made to the fingerprinting. Unfortunately this is a regression for me. I've just installed a new instance of errbit, whereas we've been using an old install for a while, so I'm immediately noticing a difference in the grouping.

Even just running a simple notify from our app `Airbrake.notify(Exception.new("test"))` doesn't result in a match, creating two separate errs. When I tell my app to use the legacy fingerprint method it starts to work again.

Note: the docs should explain you'll need to manually require the legacy fingerprint file since it doesn't follow Rails naming conventions.

**Comment by arthurnn** [comment]
is this still a problem? can I close his?

**Comment by danielbeardsley** [comment]
For what it's worth, we now monkey-patch the fingerprinting in a rails initializer so we can still have it group by first-line-of-stack-trace instead of whole-stack-trace.

```ruby
# The models aren't loaded yet so we have to load the one
# we're monkey patching.
require_relative '../../app/models/backtrace'
require_relative '../../app/models/fingerprint/sha1'

class Backtrace
  # This is a new method. The main fingerprint method is what's used to
  # associate a reported problem with its stack trace and we don't wanna screw
  # with that.
  def grouping_fingerprint
    our_lines = lines.select {|l| l.in_app? }
    # Find the first backtrace line with a file and line number.
    line = our_lines.detect {|l| l.number.present? && l.file.present? } ||
           our_lines.first ||
           lines.first

    Digest::SHA1.hexdigest("#{line.file}:#{line.number}")
  end
end

module Fingerprint
  class Sha1
    # The original method used notice.backtrace.fingerprint which includes
    # *all* lines, now exceptions should be grouped by the first line of their
    # stack traces
    def file_or_message
      @file_or_message ||= unified_message + notice.backtrace.grouping_fingerprint
    end
  end
end
```
