### ISSUE TITLE
Github Oauth

### ISSUE THREAD

**Issue by the-swerve** [errbit/errbit#686]
Use github oauth instead of userpass. I'll try to tackle this.

**Comment by alex-handley** [comment]
After looking at this properly I think this feature might be duplicated. If you don't setup the issue tracker under the project#edit and use OAuth to sign in via Github you can still create issues on a problems page.

Do you think we need both methods?

**Comment by arthurnn** [comment]
the issue creation already will use the GH OAuth token if the login was using that... so I think this can be closed.
