### ISSUE TITLE
/apps/new throwing error with undefined method _type

### ISSUE THREAD

**Issue by andywenk** [errbit/errbit#694]
Hi,

we have a fresh install from dev 0.3.0 and have not been able to create a new app. 

    request: /apps/new

NoMethodError at /apps/new
undefined method `_type' for #<IssueTracker:0x0000000b99d918>

     # Allows us to set the issue tracker class from a single form.
     def type; self._type; end
     def type=(t); self._type=t; end

After a quick check, we changed the code snippet to

     # Allows us to set the issue tracker class from a single form.
     def type; self.issue_type; end
     def type=(t); self.issue_type=t; end

and it works. But we are not sure if this is a bug and the correct fix.

Cheers

Andy

**Comment by stevecrozz** [comment]
This strikes me as a possible mismatch between migration version and application code. I'm not sure how it happened, but it doesn't seem to be affecting anyone today so I'm going to close this issue.
