### ISSUE TITLE
Add change log in errbit deploy email notification

### ISSUE THREAD

**Issue by mohitjain** [errbit/errbit#700]
Hey,

Is it possible to send change log in email deploy notification in errbit?

What I want to do:

I have enabled the deploy notification for my apps to all the users. So when developers deploy code. All the concern team members get notification. But I really want to send the change via that email. So every body get notified what exact has been deployed.

**Comment by stevecrozz** [comment]
The deployment tracking feature is on the chopping block with #913, so I'm going to close this feature and we can consider deployment tracking to be deprecated at this point. Please get in touch with me if you're really attached to this feature because there's still some time to discuss it.
