### ISSUE TITLE
Support json notifications from airbrake-js

### ISSUE THREAD

**Issue by xdmx** [errbit/errbit#701]
The new airbrake gem release has removed the js client, instead the [airbrake-js](https://github.com/airbrake/airbrake-js) should be used airbrake/airbrake-js#85 which sends data in JSON

Errbit should be updated in order to support the new api format

**Comment by steveyken** [comment]
Hi there, just wondering if there is any movement on this issue? Would love to use this in my ember application.

**Comment by stevecrozz** [comment]
I have looked a bit more into airbrake-js. Last time I looked, the URL for the API endpoint was hard-coded in an inaccessible closure so it could not be easily pointed to a new URL. But we are formulating plans to support the V3 airbrake API:
https://github.com/errbit/errbit/wiki/Road-Map-2015

**Comment by steveyken** [comment]
Thanks, good to see the roadmap. I discovered recently that the URL for API endpoint is no longer hardcoded - see https://github.com/airbrake/airbrake-js/pull/108

**Comment by ronin** [comment]
This can be closed now (https://github.com/errbit/errbit/pull/808)

**Comment by stevecrozz** [comment]
Right. Support for the v3 api is now here and we have some docs on how to use airbrake-js with errbit. Thanks again @ronin.
