### ISSUE TITLE
can't run the ldap auth.

### ISSUE THREAD

**Issue by ChrisWesterfield** [errbit/errbit#726]
Hi,
I followed the how to for ldap authentication so far.
But I can't really get it to work.

In the logs I see this:

LDAP: LDAP dn lookup: uid=johnDoe
LDAP: LDAP search for login: uid=johnDoe
LDAP: LDAP search yielded 0 matches
LDAP: Authorizing user uid=johnDoe,ou=People,dc=ldap,dc=example,dc=org
LDAP: LDAP dn lookup: uid=johnDoe
LDAP: LDAP search for login: uid=johnDoe
LDAP: LDAP search yielded 0 matches
LDAP: Not authorized because not authenticated.

What I can tell it simply can't find the user.
But when I query the system for uid=johnDoe I find an entry (querying phpldapadmin)

heres my ldap.yml

authorizations: &AUTHORIZATIONS
  group_base: ou=group,dc=ldap,dc=example,dc=org
  required_groups:
    - ["moreMembers", "ou=People,dc=ldap,dc=example,dc=org"]
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: postsAdmin
production:
  host: localhost
  port: 389
  attribute: uid
  base: ou=People,dc=ldap,dc=example,dc=org
  admin_user: cn=admin,dc=ldap,dc=example,dc=org
  admin_password: PASSWORD
  ssl: false

My initializers/devise.rb

Devise.setup do |config|
  config.ldap_logger = true
  config.ldap_create_user = true
  config.ldap_update_password = true
  config.ldap_config = "#{Rails.root}/config/ldap.yml"
  config.ldap_check_group_membership = false
  config.ldap_check_attributes = false
  config.ldap_use_admin_to_bind = true
  config.ldap_ad_group_check = false
...
  config.authentication_keys = [ :email ] 
...

I don't know where I'm mistaking.
I stuck to the howto on how to set it up.
What am I missing?

**Comment by arthurnn** [comment]
I believe this is a dup of #677
