### ISSUE TITLE
Add support for Mandrill's Heroku addon?

### ISSUE THREAD

**Issue by jimeh** [errbit/errbit#738]
Any plans for adding support for the [Mandrill](https://devcenter.heroku.com/articles/mandrill) Heroku addon?

Or maybe some basic details in the readme how to manually configure it?

**Comment by arthurnn** [comment]
You mean to add as a notification support? 
The way to go with this , would be to add a notification plugin for this, once we have #769 done.

For now, I will close this, and will let you know when #769 is done, so you, or someone else can create a plugin for it.
cheers

**Comment by jimeh** [comment]
Yes, as in an alternative to SendGrid. And cool :)
