### ISSUE TITLE
Workaround to big disk usage by MongoDB

### ISSUE THREAD

**Issue by brodock** [errbit/errbit#742]
I've seen some people advocating migrating from MongoDB to other databases solution because of the way MongoDB deal with disk usage.

I've read an article from AppSignal, and how they managed to reduce MongoDB disk growth by using a smart solution: Compact everything that will not be queried, before send to MongoDB.

The full details are here: http://blog.appsignal.com/blog/2013/07/30/taming-mongodb-disk-usage.html and I think it's pretty reasonable.

It will please  #458, #614, #623

**Comment by arthurnn** [comment]
Sure, we can work on something like that. Mainly MongoDB is probably addressing these in the latest versions. We could start using aliases on errbit, to make documents smaller. But we need to make sure things still work for people that are migrating. 
Anyways, I will close this, as there is no action on this for a while. Fell free to send PRs with suggestions to fix this.
thanks

**Comment by brodock** [comment]
I've read about MongoDB 2.8 and their improvements on a new storage system, and the introduction of document based compression. I believe that it will be a lot better to invest time on that than the suggested workaround.

Thanks :)
