### ISSUE TITLE
Migrating to Twitter Bootstrap UI

### ISSUE THREAD

**Issue by Funfun** [errbit/errbit#746]
What do you think about it? 

Mainly because all benefits of mobile support from box.

Possible for Milestone 1.0 after upgrading jQuery and i'm ready to implement it )
## Update:

Hi, i finally found some time and  currently working on it in my fork.
Here is  https://github.com/Funfun/errbit/tree/twitter_bootstrap

And i think i need help.

If you want to help, here is  TODO list of app/views/ folders:

status -- folder -- developer
- [x] apps
- [x] devise (WIP @Funfun )
- [x] kaminari
- [x] mailer ( remains old style ) 
- [ ] problems (WIP @Funfun)
- [x] users (@14113 )
- [ ] deploys  
- [ ] issue_trackers  
- [x] layouts
- [ ] notices 
- [ ] shared (WIP @Funfun )

Totally is  15 directories, 77 files. 

How to help:
1. Fork it my branch, 
2. Pick some item from TODO
3. Notify here in comments that you start working on it. (it could be just one page, its up to you).
4. Make some progress using Bootstrap v3.3.0 css only. (i don't wanna deal now with JS part).
5. If you are finish then PR.

Current goal is only to apply new CSS, but if you want UI improvement, probably it should be done in different PR.

Any questions related to working item, please post it here in comments.

Cheers,
@Funfun
## Update 2.0

After proceeding with new CSS, we can discuss sketches for new UI.

my idea is basically like that
main layout:
![personal_apps___heroku](https://cloud.githubusercontent.com/assets/15877/4982107/e8b26d5c-690f-11e4-8586-908504a32bdb.png)

i will keep posting my ideas here.

**Comment by nofxx** [comment]
+ 1 for fluid use all my screen please. Ty, waiting.

**Comment by Funfun** [comment]
@arthurnn Sorry for late answer, just have to start work on after my holidays. As i remember, i stopped on "problems" entity show, had some issues for table layout, may be we need just to conclude to support just a bit different style for now, until we moved fully to new design.

I will post my progress, suggestions and questions as soon as i will have a time.

**Comment by arthurnn** [comment]
Ok @Funfun thanks, let me know any help you need, and if you get blocked in anything.

**Comment by benjaminsigidi** [comment]
I would like to help too. :+1:

**Comment by stevecrozz** [comment]
Any updates @Funfun ? Looks like there's plenty of willing volunteers if you need help.

**Comment by pablocrivella** [comment]
+1

**Comment by Funfun** [comment]
Hey @stevecrozz  i definitely need a some help, lacking of some free time, please check out views/problems/, the rest is fine.

**Comment by benjaminsigidi** [comment]
@Funfun  and @stevecrozz  i'm ready when you are

**Comment by stevecrozz** [comment]
Looks like @Funfun could use some help here. Do we have any volunteers who'd like to continue this effort?

**Comment by Funfun** [comment]
@abner Many thanks.

**Comment by tomkr** [comment]
I noticed there's some more recent discussion on this in #903. Is this still something you are interested in and if so what are the current plans? I'd be happy to help out if there's anything I can do.

**Comment by stevecrozz** [comment]
Definitely still interested. @rjhancock has been working on a third attempt, but I'm not sure what the status of that effort is. I know he hangs out on https://gitter.im/errbit/errbit sometimes, we may be able to get an update there.

From my perspective, prior efforts have been a bit too ambitious. Let's see where @rjhancock is and see if he'd like some help or if we can scope the task down to smaller, more easily-deliverable chunks.

**Comment by rjhancock** [comment]
Right now it looks like needing to tweak a few more screens and finishing updating the JS for bootstrap. Will try to get more done this weekend on it and take screenshots to post.

**Comment by quexpl** [comment]
Where can i found latest sources and recent discussion about bootstrap in errbit? There are several places talking about that. I want to work on this.

**Comment by GBH** [comment]
Bootstrap 4 beta is a thing now.
