### ISSUE TITLE
POSSIBLE BUG: Slack integration not working

### ISSUE THREAD

**Issue by henry74** [errbit/errbit#756]
I think Slack may have changed the url for incoming webhooks.  I created a incoming webhook on slack and the webhook URL is: https://hooks.slack.com/services/T05Z3C4KT/B02V6Z0NN/randomcharactershere

If you click on the Slack icon on the Apps page it takes you to:
https://yoursubdomain.slack.com/services/hooks/incoming-webhook?token=token123here

Thoughts?

**Comment by micred** [comment]
It doesn't work, even setting the token as the last characters of the webhook.
Any ideas?
