### ISSUE TITLE
Airbrake v. 4.1.0: airbrake_javascript_notifier is "undefined"

### ISSUE THREAD

**Issue by john-999** [errbit/errbit#757]
When using gem Airbrake v.4.1.0 in Rails applications, `<%= airbrake_javascript_notifier %>` throws:

```
undefined local variable or method `airbrake_javascript_notifier' for #<#<Class:0xb00e578>:0xaff530c>
```

With Airbrake at v.3.1.14 the error vanishes.

**Comment by lnr91** [comment]
Hi @john-999 , were you able to fix this issue ? I have the same problem.

**Comment by john-999** [comment]
@lnr91 sorry, no (I remember commenting it out...).
