### ISSUE TITLE
Question: How are feature pull requests handled?

### ISSUE THREAD

**Issue by robinboening** [errbit/errbit#762]
Hey there

few weeks ago I built a feature for errbit and sent a pull request but I didn't get a response on that yet.
I noticed other long living open PRs containing new features while another pull request of mine which only enhanced the tests was merged within few hours. So, I was wondering what is your policy with these pull requests containing features?

Thanks
Robin

**Comment by arthurnn** [comment]
closing this as it was answered already.

**Comment by robinboening** [comment]
Hey Steve,

sorry for the late reply. I want to thank for your openness. I was really pleased reading such a long explanation and I fully understand your position and respect your acting.

Unfortunately the link to the owners is not available anymore. Seems like github (re)moved that resource. But anyway... Have you talked to one of them about future plans lately or before you got into this maintaining position?

In my holy opinion: If there was no conversation between you and the owners about not pushing the software forward, I don't see any reason to not filling their position now (of course only if you like to).

If you like to discuss some more with me you can ping me on twitter (@robinboening) and we can setup a chat or something.

Thanks for your great work!

**Comment by stevecrozz** [comment]
I think it is about time, and @arthurnn has been a great help in driving things forward. We're putting together a road map right now and I think I'll be sending it out to the mailing list for some feedback soon. I'm reaching out to the current owners now. I'd also invite you to come hang out in #errbit on freenode if you want to chat more. I'm usually there during the week.
