### ISSUE TITLE
extract notifications to errbit_plugin

### ISSUE THREAD

**Issue by arthurnn** [errbit/errbit#769]

**Comment by mfrederickson** [comment]
I don't see how the errbit_plugin can be used for this without refactoring it some, placing the tracker code into an intermediate layer.  Is that what you envisioned?

![image](https://cloud.githubusercontent.com/assets/473165/13447459/206d40ac-dfc8-11e5-8867-fefed7867e0e.png)

**Comment by stevecrozz** [comment]
ErrbitPlugin is a module and I had imagined it as a container for some base classes that can be extended by plugins. Currently we have ErrbitPlugin::IssueTracker (https://github.com/errbit/errbit_plugin/blob/master/lib/errbit_plugin/issue_tracker.rb). It seems natural to have an ErrbitPlugin::Notifier or something along those lines. But the two base classes themselves wouldn't necessarily need to have a common ancestor.

The way I see it we can have `class MyTracker < ErrbitPlugin::IssueTracker` as we do now and then `class MyNotifier < ErrbitPlugin::Notifier`

**Comment by mfrederickson** [comment]
I was looking at the Registry and how it might need to change.  Makes sense.

**Comment by stevecrozz** [comment]
I'm finally getting around to this. Are you interested in helping convert some plugins @mfrederickson or integrating the new plugin notifier system with errbit core? Here's what I've got so far on the plugin side: https://github.com/errbit/errbit_plugin/pull/8

**Comment by mfrederickson** [comment]
No, I'm rather busy with a bunch of other stuff at the moment, sorry.

**Comment by stevecrozz** [comment]
No prob at all. I'm gonna try to plow through the core integration parts next. In case anyone is watching this and wants to adopt a notifier, let me know!

**Comment by rud** [comment]
This extract effort has to be driven by an explicit need, I think. Going to close this out for now
