### ISSUE TITLE
[production][errs#create_issue] ArgumentError: invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by ndbroadbent** [errbit/errbit#77]
[See this exception on Errbit](http://errbit-central.heroku.com:80/apps/c0eefc4c89aa624218feb7450a3f2aac/errs/4e5f1e5ee160860001000005)
# ArgumentError: invalid byte sequence in US-ASCII
### URL

[http://errbit-central.heroku.com/apps/c0eefc4c89aa624218feb7450a3f2aac/errs/4e5a4580f5a46d0001000006/create_issue](http://errbit-central.heroku.com/apps/c0eefc4c89aa624218feb7450a3f2aac/errs/4e5a4580f5a46d0001000006/create_issue)"
### Where

errs#create_issue
### Occured

Aug 31 10:55pm
### Similar

0
## Params

```
{
  "_method" => "post",
  "action" => "create_issue",
  "app_id" => "c0eefc4c89aa624218feb7450a3f2aac",
  "authenticity_token" => "o/F6a3V8gsrHn6oKmQ7vd05ZFt9q2HPRH3lfRh2X0UI=",
  "controller" => "errs",
  "id" => "4e5a4580f5a46d0001000006"
}
```
## Session

```
{
  "_csrf_token" => "o/F6a3V8gsrHn6oKmQ7vd05ZFt9q2HPRH3lfRh2X0UI=",
  "session_id" => "0261fee573ae65a853b991a0fe3c9144",
  "warden&#46;user&#46;user&#46;key" => "[\"User\", [\"4e48afc1d8895b0001000003\"], \"$2a$10$K6wZ4FxC5mOme8LLdwvNV.\"]"
}
```
## Backtrace

```
70:  /.bundle/gems/ruby/1.9.1/gems/faraday-0.6.1/lib/faraday/utils.rb -> **gsub**
70:  /.bundle/gems/ruby/1.9.1/gems/faraday-0.6.1/lib/faraday/utils.rb -> **escape**
63:  /.bundle/gems/ruby/1.9.1/gems/faraday-0.6.1/lib/faraday/utils.rb -> **build_nested_query**
57:  /.bundle/gems/ruby/1.9.1/gems/faraday-0.6.1/lib/faraday/utils.rb -> **block in build_nested_query**
56:  /.bundle/gems/ruby/1.9.1/gems/faraday-0.6.1/lib/faraday/utils.rb -> **each**
56:  /.bundle/gems/ruby/1.9.1/gems/faraday-0.6.1/lib/faraday/utils.rb -> **map**
56:  /.bundle/gems/ruby/1.9.1/gems/faraday-0.6.1/lib/faraday/utils.rb -> **build_nested_query**
12:  /.bundle/gems/ruby/1.9.1/gems/faraday-0.6.1/lib/faraday/request/url_encoded.rb -> **block in call**
22:  /.bundle/gems/ruby/1.9.1/gems/faraday-0.6.1/lib/faraday/request/url_encoded.rb -> **match_content_type**
11:  /.bundle/gems/ruby/1.9.1/gems/faraday-0.6.1/lib/faraday/request/url_encoded.rb -> **call**
88:  /.bundle/gems/ruby/1.9.1/gems/faraday-0.6.1/lib/faraday/request.rb -> **run**
28:  /.bundle/gems/ruby/1.9.1/gems/faraday-0.6.1/lib/faraday/request.rb -> **run**
170:  /.bundle/gems/ruby/1.9.1/gems/faraday-0.6.1/lib/faraday/connection.rb -> **run_request**
69:  /.bundle/gems/ruby/1.9.1/gems/faraday-0.6.1/lib/faraday/connection.rb -> **post**
28:  /.bundle/gems/ruby/1.9.1/gems/octokit-0.6.3/lib/octokit/client/request.rb -> **request**
9:  /.bundle/gems/ruby/1.9.1/gems/octokit-0.6.3/lib/octokit/client/request.rb -> **post**
19:  /.bundle/gems/ruby/1.9.1/gems/octokit-0.6.3/lib/octokit/client/issues.rb -> **create_issue**
24:  [PROJECT_ROOT]/models/issue_trackers/github_issues_tracker.rb -> **create_issue**
112:  /.bundle/gems/ruby/1.9.1/gems/mongoid-2.1.2/lib/mongoid/relations/proxy.rb -> **method_missing**
34:  [PROJECT_ROOT]/controllers/errs_controller.rb -> **create_issue**
4:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_controller/metal/implicit_render.rb -> **send_action**
150:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/abstract_controller/base.rb -> **process_action**
11:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_controller/metal/rendering.rb -> **process_action**
18:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/abstract_controller/callbacks.rb -> **block in process_action**
450:  /.bundle/gems/ruby/1.9.1/gems/activesupport-3.0.5/lib/active_support/callbacks.rb -> **_run__1175228217613722863__process_action__743419639143723096__callbacks**
409:  /.bundle/gems/ruby/1.9.1/gems/activesupport-3.0.5/lib/active_support/callbacks.rb -> **_run_process_action_callbacks**
93:  /.bundle/gems/ruby/1.9.1/gems/activesupport-3.0.5/lib/active_support/callbacks.rb -> **run_callbacks**
17:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/abstract_controller/callbacks.rb -> **process_action**
30:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
52:  /.bundle/gems/ruby/1.9.1/gems/activesupport-3.0.5/lib/active_support/notifications.rb -> **block in instrument**
21:  /.bundle/gems/ruby/1.9.1/gems/activesupport-3.0.5/lib/active_support/notifications/instrumenter.rb -> **instrument**
52:  /.bundle/gems/ruby/1.9.1/gems/activesupport-3.0.5/lib/active_support/notifications.rb -> **instrument**
29:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_controller/metal/instrumentation.rb -> **process_action**
17:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_controller/metal/rescue.rb -> **process_action**
119:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/abstract_controller/base.rb -> **process**
41:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/abstract_controller/rendering.rb -> **process**
138:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_controller/metal.rb -> **dispatch**
14:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_controller/metal/rack_delegation.rb -> **dispatch**
178:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_controller/metal.rb -> **block in action**
62:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/routing/route_set.rb -> **call**
62:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/routing/route_set.rb -> **dispatch**
27:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/routing/route_set.rb -> **call**
148:  /.bundle/gems/ruby/1.9.1/gems/rack-mount-0.6.14/lib/rack/mount/route_set.rb -> **block in call**
93:  /.bundle/gems/ruby/1.9.1/gems/rack-mount-0.6.14/lib/rack/mount/code_generation.rb -> **block in recognize**
75:  /.bundle/gems/ruby/1.9.1/gems/rack-mount-0.6.14/lib/rack/mount/code_generation.rb -> **optimized_each**
92:  /.bundle/gems/ruby/1.9.1/gems/rack-mount-0.6.14/lib/rack/mount/code_generation.rb -> **recognize**
139:  /.bundle/gems/ruby/1.9.1/gems/rack-mount-0.6.14/lib/rack/mount/route_set.rb -> **call**
492:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/routing/route_set.rb -> **call**
33:  /.bundle/gems/ruby/1.9.1/gems/mongoid-2.1.2/lib/rack/mongoid/middleware/identity_map.rb -> **block in call**
130:  /.bundle/gems/ruby/1.9.1/gems/mongoid-2.1.2/lib/mongoid.rb -> **unit_of_work**
33:  /.bundle/gems/ruby/1.9.1/gems/mongoid-2.1.2/lib/rack/mongoid/middleware/identity_map.rb -> **call**
41:  /.bundle/gems/ruby/1.9.1/gems/haml-3.0.25/lib/sass/plugin/rack.rb -> **call**
35:  /.bundle/gems/ruby/1.9.1/gems/warden-1.0.5/lib/warden/manager.rb -> **block in call**
34:  /.bundle/gems/ruby/1.9.1/gems/warden-1.0.5/lib/warden/manager.rb -> **catch**
34:  /.bundle/gems/ruby/1.9.1/gems/warden-1.0.5/lib/warden/manager.rb -> **call**
17:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/middleware/best_standards_support.rb -> **call**
14:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/middleware/head.rb -> **call**
24:  /.bundle/gems/ruby/1.9.1/gems/rack-1.2.2/lib/rack/methodoverride.rb -> **call**
21:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/middleware/params_parser.rb -> **call**
182:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/middleware/flash.rb -> **call**
149:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/middleware/session/abstract_store.rb -> **call**
302:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/middleware/cookies.rb -> **call**
46:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
415:  /.bundle/gems/ruby/1.9.1/gems/activesupport-3.0.5/lib/active_support/callbacks.rb -> **_run_call_callbacks**
44:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/middleware/callbacks.rb -> **call**
107:  /.bundle/gems/ruby/1.9.1/gems/rack-1.2.2/lib/rack/sendfile.rb -> **call**
48:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/middleware/remote_ip.rb -> **call**
47:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
13:  /.bundle/gems/ruby/1.9.1/gems/railties-3.0.5/lib/rails/rack/logger.rb -> **call**
17:  /.bundle/gems/ruby/1.9.1/gems/rack-1.2.2/lib/rack/runtime.rb -> **call**
11:  /.bundle/gems/ruby/1.9.1/gems/rack-1.2.2/lib/rack/lock.rb -> **block in call**
:  [unknown source] -> ****
11:  /.bundle/gems/ruby/1.9.1/gems/rack-1.2.2/lib/rack/lock.rb -> **call**
30:  /.bundle/gems/ruby/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/middleware/static.rb -> **call**
168:  /.bundle/gems/ruby/1.9.1/gems/railties-3.0.5/lib/rails[PROJECT_ROOT]lication.rb -> **call**
77:  /.bundle/gems/ruby/1.9.1/gems/railties-3.0.5/lib/rails[PROJECT_ROOT]lication.rb -> **method_missing**
9:  /home/heroku_rack/lib/static_assets.rb -> **call**
15:  /home/heroku_rack/lib/last_access.rb -> **call**
47:  /.bundle/gems/ruby/1.9.1/gems/rack-1.2.2/lib/rack/urlmap.rb -> **block in call**
41:  /.bundle/gems/ruby/1.9.1/gems/rack-1.2.2/lib/rack/urlmap.rb -> **each**
41:  /.bundle/gems/ruby/1.9.1/gems/rack-1.2.2/lib/rack/urlmap.rb -> **call**
14:  /home/heroku_rack/lib/date_header.rb -> **call**
77:  /.bundle/gems/ruby/1.9.1/gems/rack-1.2.2/lib/rack/builder.rb -> **call**
84:  /.bundle/gems/ruby/1.9.1/gems/thin-1.2.11/lib/thin/connection.rb -> **block in pre_process**
82:  /.bundle/gems/ruby/1.9.1/gems/thin-1.2.11/lib/thin/connection.rb -> **catch**
82:  /.bundle/gems/ruby/1.9.1/gems/thin-1.2.11/lib/thin/connection.rb -> **pre_process**
57:  /.bundle/gems/ruby/1.9.1/gems/thin-1.2.11/lib/thin/connection.rb -> **process**
42:  /.bundle/gems/ruby/1.9.1/gems/thin-1.2.11/lib/thin/connection.rb -> **receive_data**
256:  /.bundle/gems/ruby/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb -> **run_machine**
256:  /.bundle/gems/ruby/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb -> **run**
61:  /.bundle/gems/ruby/1.9.1/gems/thin-1.2.11/lib/thin/backends/base.rb -> **start**
159:  /.bundle/gems/ruby/1.9.1/gems/thin-1.2.11/lib/thin/server.rb -> **start**
86:  /.bundle/gems/ruby/1.9.1/gems/thin-1.2.11/lib/thin/controllers/controller.rb -> **start**
185:  /.bundle/gems/ruby/1.9.1/gems/thin-1.2.11/lib/thin/runner.rb -> **run_command**
151:  /.bundle/gems/ruby/1.9.1/gems/thin-1.2.11/lib/thin/runner.rb -> **run!**
6:  /.bundle/gems/ruby/1.9.1/gems/thin-1.2.11/bin/thin -> **<top (required)>**
19:  /usr/ruby1.9.2/bin/thin -> **load**
19:  /usr/ruby1.9.2/bin/thin -> **<main>**

```
## Environment

<table>

<tr>
<td>SERVER_SOFTWARE:</td>
<td>thin 1.2.11 codename Bat-Shit Crazy</td>
</tr>

<tr>
<td>SERVER_NAME:</td>
<td>errbit-central.heroku.com</td>
</tr>

<tr>
<td>rack&#46;input:</td>
<td>#<StringIO:0x00000005c218c0></td>
</tr>

<tr>
<td>rack&#46;version:</td>
<td>["1", "0"]</td>
</tr>

<tr>
<td>rack&#46;errors:</td>
<td>#<IO:0x00000000d66578></td>
</tr>

<tr>
<td>rack&#46;multithread:</td>
<td>false</td>
</tr>

<tr>
<td>rack&#46;multiprocess:</td>
<td>false</td>
</tr>

<tr>
<td>rack&#46;run_once:</td>
<td>false</td>
</tr>

<tr>
<td>REQUEST_METHOD:</td>
<td>POST</td>
</tr>

<tr>
<td>REQUEST_PATH:</td>
<td>/apps/c0eefc4c89aa624218feb7450a3f2aac/errs/4e5a4580f5a46d0001000006/create_issue</td>
</tr>

<tr>
<td>PATH_INFO:</td>
<td>/apps/c0eefc4c89aa624218feb7450a3f2aac/errs/4e5a4580f5a46d0001000006/create_issue</td>
</tr>

<tr>
<td>REQUEST_URI:</td>
<td>/apps/c0eefc4c89aa624218feb7450a3f2aac/errs/4e5a4580f5a46d0001000006/create_issue</td>
</tr>

<tr>
<td>HTTP_VERSION:</td>
<td>HTTP/1.0</td>
</tr>

<tr>
<td>HTTP_X_REAL_IP:</td>
<td>218.103.67.113</td>
</tr>

<tr>
<td>HTTP_X_FORWARDED_FOR:</td>
<td>218.103.67.113</td>
</tr>

<tr>
<td>HTTP_USER_AGENT:</td>
<td>Mozilla/5.0 (X11; Linux x86_64; rv:5.0) Gecko/20100101 Firefox/5.0</td>
</tr>

<tr>
<td>HTTP_REFERER:</td>
<td>http://errbit-central.heroku.com/apps/c0eefc4c89aa624218feb7450a3f2aac/errs/4e5a4580f5a46d0001000006</td>
</tr>

<tr>
<td>HTTP_HOST:</td>
<td>errbit-central.heroku.com</td>
</tr>

<tr>
<td>HTTP_COOKIE:</td>
<td>__utma=111815579.571265825.1313382146.1313409011.1314589759.6; __utmz=111815579.1314589759.6.6.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=heroku%20push%20from%20different%20branch; LOOPFUSE=fcf4f480-4f16-4071-a81c-89b1d65d5f25; km_dbg=0; km_ai=Dz5d92TB8o6Nz%2FCvUI%2BElbkkt%2BY%3D; _errbit_session=BAh7CEkiEF9jc3JmX3Rva2VuBjoGRUZJIjFvL0Y2YTNWOGdzckhuNm9LbVE3dmQwNVpGdDlxMkhQUkgzbGZSaDJYMFVJPQY7AEZJIhl3YXJkZW4udXNlci51c2VyLmtleQY7AFRbCEkiCVVzZXIGOwBGWwZvOhNCU09OOjpPYmplY3RJZAY6CkBkYXRhWxFpU2lNaQGvaQHBaQHYaQGJaWBpAGkGaQBpAGkISSIiJDJhJDEwJEs2d1o0RnhDNW1PbWU4TExkd3ZOVi4GOwBUSSIPc2Vzc2lvbl9pZAY7AEYiJTAyNjFmZWU1NzNhZTY1YTg1M2I5OTFhMGZlM2M5MTQ0--4f03754a7d0b9c6370c4432757d32eaac3f38d83; remember_user_token=BAhbB1sGbzoTQlNPTjo6T2JqZWN0SWQGOgpAZGF0YVsRaVNpTWkBr2kBwWkB2GkBiWlgaQBpBmkAaQBpCEkiGXB0ZzJXUFE2cnBRNmtlNlZScWp5BjoGRVQ%3D--5216324044eb5c5bf06efcf1bfcd708c2b4c434e</td>
</tr>

<tr>
<td>HTTP_CONNECTION:</td>
<td>close</td>
</tr>

<tr>
<td>HTTP_ACCEPT_LANGUAGE:</td>
<td>en-us,en;q=0.5</td>
</tr>

<tr>
<td>HTTP_ACCEPT_ENCODING:</td>
<td>gzip, deflate</td>
</tr>

<tr>
<td>HTTP_ACCEPT_CHARSET:</td>
<td>ISO-8859-1,utf-8;q=0.7,*;q=0.7</td>
</tr>

<tr>
<td>HTTP_ACCEPT:</td>
<td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td>
</tr>

<tr>
<td>HTTP_X_HEROKU_QUEUE_WAIT_TIME:</td>
<td>1</td>
</tr>

<tr>
<td>HTTP_X_HEROKU_QUEUE_DEPTH:</td>
<td>0</td>
</tr>

<tr>
<td>HTTP_X_HEROKU_DYNOS_IN_USE:</td>
<td>1</td>
</tr>

<tr>
<td>HTTP_X_REQUEST_START:</td>
<td>1314856537709</td>
</tr>

<tr>
<td>CONTENT_LENGTH:</td>
<td>80</td>
</tr>

<tr>
<td>CONTENT_TYPE:</td>
<td>application/x-www-form-urlencoded</td>
</tr>

<tr>
<td>GATEWAY_INTERFACE:</td>
<td>CGI/1.2</td>
</tr>

<tr>
<td>SERVER_PORT:</td>
<td>80</td>
</tr>

<tr>
<td>key:</td>
<td>action_dispatch.request.query_parameters</td>
</tr>

<tr>
<td>SERVER_PROTOCOL:</td>
<td>HTTP/1.1</td>
</tr>

<tr>
<td>rack&#46;url_scheme:</td>
<td>http</td>
</tr>

<tr>
<td>REMOTE_ADDR:</td>
<td>10.94.70.11</td>
</tr>

<tr>
<td>async&#46;callback:</td>
<td>#<Method: Thin::Connection#post_process></td>
</tr>

<tr>
<td>async&#46;close:</td>
<td>#<EventMachine::DefaultDeferrable:0x00000005c15228></td>
</tr>

<tr>
<td>action_dispatch&#46;parameter_filter:</td>
<td>["password"]</td>
</tr>

<tr>
<td>action_dispatch&#46;secret_token:</td>
<td>6b74778101638fa9c156b3928c9492fb2481ab842538bea838d21f9c9993f649f5806449584266d413d0b2f1104162b3066a86512ed71ededd627cd41f939614</td>
</tr>

<tr>
<td>action_dispatch&#46;remote_ip:</td>
<td>218.103.67.113</td>
</tr>

<tr>
<td>rack&#46;session:</td>
<td>{"_csrf_token"=>"o/F6a3V8gsrHn6oKmQ7vd05ZFt9q2HPRH3lfRh2X0UI=", "warden&#46;user&#46;user&#46;key"=>"[\"User\", [\"4e48afc1d8895b0001000003\"], \"$2a$10$K6wZ4FxC5mOme8LLdwvNV.\"]", "session_id"=>"0261fee573ae65a853b991a0fe3c9144"}</td>
</tr>

<tr>
<td>rack&#46;session&#46;options:</td>
<td>{"path"=>"/", "key"=>"expire_after", "secure"=>"false", "httponly"=>"true", "id"=>"0261fee573ae65a853b991a0fe3c9144"}</td>
</tr>

<tr>
<td>rack&#46;request&#46;cookie_string:</td>
<td>__utma=111815579.571265825.1313382146.1313409011.1314589759.6; __utmz=111815579.1314589759.6.6.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=heroku%20push%20from%20different%20branch; LOOPFUSE=fcf4f480-4f16-4071-a81c-89b1d65d5f25; km_dbg=0; km_ai=Dz5d92TB8o6Nz%2FCvUI%2BElbkkt%2BY%3D; _errbit_session=BAh7CEkiEF9jc3JmX3Rva2VuBjoGRUZJIjFvL0Y2YTNWOGdzckhuNm9LbVE3dmQwNVpGdDlxMkhQUkgzbGZSaDJYMFVJPQY7AEZJIhl3YXJkZW4udXNlci51c2VyLmtleQY7AFRbCEkiCVVzZXIGOwBGWwZvOhNCU09OOjpPYmplY3RJZAY6CkBkYXRhWxFpU2lNaQGvaQHBaQHYaQGJaWBpAGkGaQBpAGkISSIiJDJhJDEwJEs2d1o0RnhDNW1PbWU4TExkd3ZOVi4GOwBUSSIPc2Vzc2lvbl9pZAY7AEYiJTAyNjFmZWU1NzNhZTY1YTg1M2I5OTFhMGZlM2M5MTQ0--4f03754a7d0b9c6370c4432757d32eaac3f38d83; remember_user_token=BAhbB1sGbzoTQlNPTjo6T2JqZWN0SWQGOgpAZGF0YVsRaVNpTWkBr2kBwWkB2GkBiWlgaQBpBmkAaQBpCEkiGXB0ZzJXUFE2cnBRNmtlNlZScWp5BjoGRVQ%3D--5216324044eb5c5bf06efcf1bfcd708c2b4c434e</td>
</tr>

<tr>
<td>rack&#46;request&#46;cookie_hash:</td>
<td>{"__utma"=>"111815579.571265825.1313382146.1313409011.1314589759.6", "__utmz"=>"111815579.1314589759.6.6.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=heroku push from different branch", "LOOPFUSE"=>"fcf4f480-4f16-4071-a81c-89b1d65d5f25", "km_dbg"=>"0", "km_ai"=>"Dz5d92TB8o6Nz/CvUI+Elbkkt+Y=", "_errbit_session"=>"BAh7CEkiEF9jc3JmX3Rva2VuBjoGRUZJIjFvL0Y2YTNWOGdzckhuNm9LbVE3dmQwNVpGdDlxMkhQUkgzbGZSaDJYMFVJPQY7AEZJIhl3YXJkZW4udXNlci51c2VyLmtleQY7AFRbCEkiCVVzZXIGOwBGWwZvOhNCU09OOjpPYmplY3RJZAY6CkBkYXRhWxFpU2lNaQGvaQHBaQHYaQGJaWBpAGkGaQBpAGkISSIiJDJhJDEwJEs2d1o0RnhDNW1PbWU4TExkd3ZOVi4GOwBUSSIPc2Vzc2lvbl9pZAY7AEYiJTAyNjFmZWU1NzNhZTY1YTg1M2I5OTFhMGZlM2M5MTQ0--4f03754a7d0b9c6370c4432757d32eaac3f38d83", "remember_user_token"=>"BAhbB1sGbzoTQlNPTjo6T2JqZWN0SWQGOgpAZGF0YVsRaVNpTWkBr2kBwWkB2GkBiWlgaQBpBmkAaQBpCEkiGXB0ZzJXUFE2cnBRNmtlNlZScWp5BjoGRVQ=--5216324044eb5c5bf06efcf1bfcd708c2b4c434e"}</td>
</tr>

<tr>
<td>action_dispatch&#46;cookies:</td>
<td>{"__utma"=>"111815579.571265825.1313382146.1313409011.1314589759.6", "__utmz"=>"111815579.1314589759.6.6.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=heroku push from different branch", "LOOPFUSE"=>"fcf4f480-4f16-4071-a81c-89b1d65d5f25", "km_dbg"=>"0", "km_ai"=>"Dz5d92TB8o6Nz/CvUI+Elbkkt+Y=", "_errbit_session"=>"BAh7CEkiEF9jc3JmX3Rva2VuBjoGRUZJIjFvL0Y2YTNWOGdzckhuNm9LbVE3dmQwNVpGdDlxMkhQUkgzbGZSaDJYMFVJPQY7AEZJIhl3YXJkZW4udXNlci51c2VyLmtleQY7AFRbCEkiCVVzZXIGOwBGWwZvOhNCU09OOjpPYmplY3RJZAY6CkBkYXRhWxFpU2lNaQGvaQHBaQHYaQGJaWBpAGkGaQBpAGkISSIiJDJhJDEwJEs2d1o0RnhDNW1PbWU4TExkd3ZOVi4GOwBUSSIPc2Vzc2lvbl9pZAY7AEYiJTAyNjFmZWU1NzNhZTY1YTg1M2I5OTFhMGZlM2M5MTQ0--4f03754a7d0b9c6370c4432757d32eaac3f38d83", "remember_user_token"=>"BAhbB1sGbzoTQlNPTjo6T2JqZWN0SWQGOgpAZGF0YVsRaVNpTWkBr2kBwWkB2GkBiWlgaQBpBmkAaQBpCEkiGXB0ZzJXUFE2cnBRNmtlNlZScWp5BjoGRVQ=--5216324044eb5c5bf06efcf1bfcd708c2b4c434e"}</td>
</tr>

<tr>
<td>action_dispatch&#46;request&#46;unsigned_session_cookie:</td>
<td>{"_csrf_token"=>"o/F6a3V8gsrHn6oKmQ7vd05ZFt9q2HPRH3lfRh2X0UI=", "warden&#46;user&#46;user&#46;key"=>"[\"User\", [\"4e48afc1d8895b0001000003\"], \"$2a$10$K6wZ4FxC5mOme8LLdwvNV.\"]", "session_id"=>"0261fee573ae65a853b991a0fe3c9144"}</td>
</tr>

<tr>
<td>action_dispatch&#46;request&#46;content_type:</td>
<td>application/x-www-form-urlencoded</td>
</tr>

<tr>
<td>rack&#46;request&#46;form_input:</td>
<td>#<StringIO:0x00000005c218c0></td>
</tr>

<tr>
<td>rack&#46;request&#46;form_hash:</td>
<td>{"_method"=>"post", "authenticity_token"=>"o/F6a3V8gsrHn6oKmQ7vd05ZFt9q2HPRH3lfRh2X0UI="}</td>
</tr>

<tr>
<td>rack&#46;methodoverride&#46;original_method:</td>
<td>POST</td>
</tr>

<tr>
<td>warden:</td>
<td>Warden::Proxy:47933200 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:rememberable, :token_authenticatable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>Devise::FailureApp}</td>
</tr>

<tr>
<td>action_dispatch&#46;request&#46;path_parameters:</td>
<td>{"action"=>"create_issue", "controller"=>"errs", "app_id"=>"c0eefc4c89aa624218feb7450a3f2aac", "id"=>"4e5a4580f5a46d0001000006"}</td>
</tr>

<tr>
<td>action_controller&#46;instance:</td>
<td>#<ErrsController:0x00000005b65ee0></td>
</tr>

<tr>
<td>action_dispatch&#46;request&#46;request_parameters:</td>
<td>{"_method"=>"post", "authenticity_token"=>"o/F6a3V8gsrHn6oKmQ7vd05ZFt9q2HPRH3lfRh2X0UI="}</td>
</tr>

<tr>
<td>action_dispatch&#46;request&#46;parameters:</td>
<td>{"_method"=>"post", "authenticity_token"=>"o/F6a3V8gsrHn6oKmQ7vd05ZFt9q2HPRH3lfRh2X0UI=", "action"=>"create_issue", "controller"=>"errs", "app_id"=>"c0eefc4c89aa624218feb7450a3f2aac", "id"=>"4e5a4580f5a46d0001000006"}</td>
</tr>

<tr>
<td>action_dispatch&#46;request&#46;formats:</td>
<td>["text/html"]</td>
</tr>

</table>

**Comment by 1c7** [comment]
Ah. I am getting the same error but in Ruby on Rails Puma server.

![image](https://user-images.githubusercontent.com/1804755/43567632-e55cf646-9664-11e8-95ed-ba7d36912534.png)

I am looking for solution now
