### ISSUE TITLE
Document Issue Trackers move

### ISSUE THREAD

**Issue by nofxx** [errbit/errbit#780]
Lost some time on this one, looks like issue trackers are now independent gems.

Look for errbit_foo_plugin,  e.g. errbit_gitlab_plugin . (O/T for the records: that's against gem naming best practices, should be errbit-gitlab_plugin , why not errbit-gitlab?  http://guides.rubygems.org/name-your-gem/)

Was trying to write some docs, but didn't figured out what's the intended way to work custom Gemfiles.

**Comment by stevecrozz** [comment]
Hi @nofxx : can you tell me a bit more about what you mean regarding custom Gemfiles?

**Comment by nofxx** [comment]
Hi @stevecrozz ! I mean, how do I add the plugins I want? For now I've created a fork to have a custom Gemfile. Guess an option might be capistrano scp.

**Comment by stevecrozz** [comment]
Right. Adding issue trackers basically requires a fork in order to use bundler the way it was intended. I haven't thought of a better way to handle this.

**Comment by nofxx** [comment]
Yeah, scp is kinda ugly.  
Maybe parse config.yml in Gemfile, like plugins: [:gitlab, :foo].map { |g| gem "errbit_#{g}_plugin" }
Too hackish?

**Comment by stevecrozz** [comment]
You can do it, but unless you run bundle install locally and check in the resulting Gemfile.lock with the same config.yml you won't be able to use bundle install --deployment which is typically what people want to do in production.

**Comment by arthurnn** [comment]
You could use a different Gemfile and just ask bundler to install and run using that (via ENV var).

We could also do, is something like what spree does https://github.com/spree/spree/blob/master/Gemfile#L1 , and have a default .rb file with out gems, and people could edit the main Gemfile, not sure what is best tho..

**Comment by stevecrozz** [comment]
I suppose if the requirement is to support third-party plugins without making changes to the Gemfile, then you'd have to supply your own Gemfile and Gemfile.lock at deploy time through some other means. But this is not how I would document it. I think we should recommend the more straightforward approach of fork and commit a new Gemfile and Gemfile.lock.

But as it happens, better docs on how to implement issue trackers is already on the road map for v0.4.0: #782, so we can continue discussing there.
