### ISSUE TITLE
drop support for ruby 1.9

### ISSUE THREAD

**Issue by stevecrozz** [errbit/errbit#781]
Ruby 1.9.3 has reached the end of its life and [support will not continue beyond February 23, 2015](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/). Errbit should drop support for Ruby 1.9 including documentation claims and CI.

**Comment by arthurnn** [comment]
Already dropped on CI, we need to review docs tho.

**Comment by stevecrozz** [comment]
Docs look good to me actually. I guess @arthurnn already updated the README.md so we should be god to go.
