### ISSUE TITLE
document method for adding issue trackers

### ISSUE THREAD

**Issue by stevecrozz-** [errbit/errbit#782]
Expand plugin documentation especially around issue trackers. This should include details with examples at errbit/errbit_plugin and a summary in the README file at errbit/errbit with a pointer to errbit/errbit_plugin

**Comment by arthurnn** [comment]
How about adding all these to the WIKI? I think errbit core README is already out of hand... We should start moving things outside of it, WDYT?

**Comment by stevecrozz** [comment]
Yeah, we could definitely use a cleanup in the errbit/errbit README. I think we just need a note about plugins that says something like: 'Errbit can be extended with new functionality including third-party integrations using plugins' with a link to 'errbit/plugin' where the details are explained.

**Comment by stevecrozz** [comment]
From #780, include information on how to update the errbit Gemfile to include plugins.

**Comment by nofxx** [comment]
@arthurnn great to know I'm not the only one with some evals on Gemfile's hehe.

errbit doesn't try to be user friendly (on install), as it put plainly on the Readme,
so the fork looks the simplest solution.

Just to discuss this bundle feature called 'lock' with you guys:

Say or point me to whatever I still think the (Gemfile) lock shouldn't even exist.
If you need something in version X, the Gemfile will handle that. 
If you don't lock it should work up to the latest version.
Locking what's not locked in my Gemfile just creates confusion and possibly lost of my time.
So a add plugins in config.yml, eval to gem and create the lock at deploy time... what can go wrong? 
Heh.

**Comment by arthurnn** [comment]
what we could do, so people can add their own plugins, is kinda what readmine does https://github.com/edavis10/redmine/blob/master/Gemfile#L106-L109 .  with a plugins folder.

**Comment by stevecrozz** [comment]
It's true. I've been mulling over all the ideas I can think of. I think the ideal and most safe solution would be one where the plugins live in an entirely separate runtime like a separate web service, an embedded and isolated runtime like therubyracer, or just a separate worker process. But all of those solutions suffer from increased complexity.

Embedding plugins within the main errbit process provides the ultimate flexibility and doesn't complicate deployment. So it seems like the right tradeoff. But it also kind of stinks that plugins can bring in their own possibly conflicting dependencies. It removes our ability to do consistent, repeatable deploys and we can kiss our Gemfile.lock goodbye along with `bundle install --deployment` when users can arbitrarily add gem dependencies at runtime.

Let me know if you have any other ideas, but so far something along the lines of redmine's approach seems best.

**Comment by stevecrozz** [comment]
But if we expect our users to fork errbit, run bundle install, commit, then deploy so they can get back to consistent, repeatable deployment, then it seems like we may as well just ask them to put their plugins right into the Gemfile and there wouldn't be any advantage that I can see to Redmine's approach.

@arthurnn do you see this process being a fork, add plugins, bundle install, commit, deploy, type thing? Or is it more of a deploy from the main errbit/errbit repo and inject plugins somehow as part of the deployment process? (which keeps us from doing repeatable deploys as far as I can tell)

**Comment by arthurnn** [comment]
I think the fork process is the way to go for people that wants to add plugins.
The good thing about the readmine pluginGemfile, is that people can still rebase from latest master, and they wont lose their changes on the plugin folder, as we are not suppose to add anything to there.

**Comment by stevecrozz** [comment]
Would this be a good approach?
```ruby
eval_gemfile "UserGemfile" if File.exist "UserGemfile"
```

The idea is similar, but it might encourage users to write plugins as gems, rather than embedding them into the errbit repo.

**Comment by arthurnn** [comment]
Maybe `UserGemfile` should be a path, that is added using a ENV var?

**Comment by stevecrozz** [comment]
That sounds like a pretty good idea. I think we should go with it.

**Comment by stevecrozz** [comment]
Just merged my fix. I think we're good to go on v0.4.0
