### ISSUE TITLE
plugin icon improvements

### ISSUE THREAD

**Issue by stevecrozz-** [errbit/errbit#784]
Currently, plugins provide icons (images) for remote services by virtue of some rails engine/asset pipeline magic and forcing errbit the application to serve up a dynamically generated CSS file with directives that set background images. When plugins are changed, the css file that references them doesn't and that can cause stale cache issues. Moreover, this is an overcomplication.

Plugins should have a much more straightforward way of providing images to errbit for use as icons. Something like a method called 'icon' on the plugin itself that returns the image's binary data seems like a good way to go. This will have to change here and in errbit/errbit_plugin

**Comment by stevecrozz** [comment]
@arthurnn I noticed you assigned this to yourself. Do you have everything you need on this?

**Comment by arthurnn** [comment]
Yes, I do... just need time to finish it.

**Comment by stevecrozz** [comment]
Here's my attempt at it:
https://github.com/errbit/errbit/compare/master...stevecrozz:new_icon_interface
https://github.com/errbit/errbit_plugin/compare/master...stevecrozz:new_icon_interface
https://github.com/errbit/errbit_github_plugin/compare/master...stevecrozz:new_icon_interface

**Comment by arthurnn** [comment]
wanna send PRs on the plugin projects first..

**Comment by stevecrozz** [comment]
Sure. Here's the upstream PRs:
https://github.com/errbit/errbit_plugin/pull/3
https://github.com/errbit/errbit_github_plugin/pull/5

**Comment by arthurnn** [comment]
:cocktail: :cool:

**Comment by stevecrozz** [comment]
Fixed in #859
