### ISSUE TITLE
better default issue body template

### ISSUE THREAD

**Issue by stevecrozz-** [errbit/errbit#785]
The current template at app/views/issue_trackers/issue.txt.erb is not a great default template because it contains a mix of mardown and html which is not a very sane default for an issue tracker body. This should probably just be a simple, plain-text template instead, at least to start with. We can add others later.

**Comment by arthurnn** [comment]
:+1: ,

In the future we potentially could have multiple types of templates, things like
app/views/issue_trackers/issue.txt.erb
app/views/issue_trackers/issue.html.erb
app/views/issue_trackers/issue.md.erb

And the issue tracker could leverage the rails render format to render the right issue body.

**Comment by stevecrozz** [comment]
I think that's a nice idea. I think its more than what we need for 0.4.0, but I'd be happy to have these.

**Comment by stevecrozz** [comment]
@arthurnn I added a PR #785 which has a txt and md issue tracker template. I made the default md since that's what we'll use for github.

This is on the 0.4.0 milestone: https://github.com/errbit/errbit/milestones/0.4.0

**Comment by stevecrozz** [comment]
Fixed with #783
