### ISSUE TITLE
upgrade to rails 4.2

### ISSUE THREAD

**Issue by stevecrozz-** [errbit/errbit#786]

**Comment by arthurnn** [comment]
need to make mongoid work with 4.2 first... will let you know when is done.

**Comment by stevecrozz** [comment]
Is mongoid tracking this issue? And do you have any knowledge of the timetable for this one?

If its going to be a while, we could kick this issue into 0.5.0 so we don't hold up the release train.

**Comment by arthurnn** [comment]
I would kick this to 0.5.0 !

**Comment by stevecrozz** [comment]
Ok. Off it goes to 0.5.0

**Comment by stevecrozz** [comment]
Fixed in #931
