### ISSUE TITLE
WebSocket push error notification

### ISSUE THREAD

**Issue by arthurnn** [errbit/errbit#793]
at Shopify, we cannot use the email or the chat notifications to send errors as they pollute the chat and email.
The idea would be to have a WebScoket API implementation for notification, so people can implement their own clients to consume that information( anything like chrome extension, MacOS client, etc ).

cc @jstorimer @thibaut

After we have #769 done, this might be just a extra plugin.

**Comment by stevecrozz** [comment]
I can't tell quite what you mean. Are you wanting errbit to be a web socket server, streaming events to clients who ask? Or are you wanting errbit to be a web socket client, pushing events to a remote endpoint? I think the former makes some sense, but the latter is probably better suited for regular HTTP callbacks which would be more flexible and just as timely.

**Comment by arthurnn** [comment]
I want errbit to have a socket API for errors, something you can pipe a socket to it, and receive pushes from errbit(server) on new errors.

**Comment by stevecrozz** [comment]
If I understand right, it sounds like you basically want a streaming API? So clients who want to receive events can connect from outside via web socket and receive the live event stream of new errors.

I think that's a nice idea. Let's talk over some design ideas on #errbit whenever you're ready.

**Comment by arthurnn** [comment]
:+1:

**Comment by stevecrozz** [comment]
ActionCable? :)

**Comment by rud** [comment]
ActionCable would be an awesome way to build a more dynamic UI. Rails 5.0 first, though :)
