### ISSUE TITLE
Email URLs point to localhost instead of config host

### ISSUE THREAD

**Issue by shaneneuerburg** [errbit/errbit#796]
First off, I'm a complete novice rails user and this is more of a "what did I screw up" issue rather than "you've got a bug" issue :)

I've updated config/config.yml to have the following line (& restarted the server):
`host: example.com`

When emails are received, all URLs that point to the Errbit installation are generated with `localhost` instead of `example.com`. 

I've done a manual installation (not using capistrano) on a random Ubuntu box. Errbit is being served behind an Apache proxy.

**Comment by stevecrozz** [comment]
What value of RAILS_ENV do you have in this environment? You may just need to set it to 'production'

**Comment by stevecrozz** [comment]
@shaneneuerburg I just finished putting together a new configuration system for Errbit and documented all the parameters here: https://github.com/errbit/errbit/blob/master/docs/configuration.md

I think you'll find what you need.

**Comment by shaneneuerburg** [comment]
Thanks @stevecrozz. Sorry for not replying sooner. It ended up getting floated in my inbox.
