### ISSUE TITLE
EMAIL_DELIVERY_METHOD string compared to symbol

### ISSUE THREAD

**Issue by wordsandwriting** [errbit/errbit#824]
So I set `ENV['EMAIL_DELIVERY_METHOD']` to `'smtp'` but `ActionMailer::Base.smtp_settings` was still not picking up the right settings. I've traced the problem to https://github.com/errbit/errbit/blob/0d02c7cc787de684940b0ccc79cc48417f4b13b4/config/initializers/action_mailer.rb#L2. It seems  `ActionMailer::Base.smtp_settings` is only set if `ENV['EMAIL_DELIVERY_METHOD']` is the symbol `:smtp` - but using Foreman or Heroku this is impossible as all env vars are strings.

Should I submit a PR? Or am I missing something?

**Comment by stevecrozz** [comment]
Looks like I need to update the docs, but you can pass EMAIL_DELIVERY_METHOD=:smtp (the string ':smtp') and by the time it gets to the initializer it will be coerced into a symbol so the comparison will work.

**Comment by stevecrozz** [comment]
I updated the docs and added a test in #825 to show how this works.

**Comment by wordsandwriting** [comment]
Thanks for the swift reply!
