### ISSUE TITLE
Error in Api v3 NoticeParser when backtrace is nil

### ISSUE THREAD

**Issue by steveyken** [errbit/errbit#828]
https://github.com/errbit/errbit/blob/master/lib/airbrake_api/v3/notice_parser.rb#L35

When submitting over the v3 API (airbrake-js) Errbit raises an error if the backtrace is nil.

    undefined method `map' for nil:NilClass

An error without a backtrace isn't very helpful in the first place, so I'll be fixing the main problem in my client system that is sending an empty backtrace. However, I thought it worth raising an issue here for Errbit to gracefully handle bad input like this.

As a side note, really appreciate the work that was done on the v3 API recently. It's made a real difference for us and I know the paint is still drying.

**Comment by ronin** [comment]
I'll take care of this. Do you think errbit should add notice without backtrace or just skip it?

**Comment by stevecrozz** [comment]
I think we can probably just use a `(error['backtrace'] || []).map` here. The backtrace relationship must exist, but it doesn't have to contain any lines.

**Comment by steveyken** [comment]
Thanks all.
