### ISSUE TITLE
Asset images wrong

### ISSUE THREAD

**Issue by davidsteinsland** [errbit/errbit#836]
I've setup errbit, but I'm having troubles loading the images from stylesheets.

For example, a stylesheet references the `briefcase.png` icon, but in public/assets/ it is stored as `briefcase-<HASH>.png`.

Is there something I have done wrong here, or is this a fault?

**Comment by arthurnn** [comment]
on the stylesheet file, we need to use the rails asset helpers (http://api.rubyonrails.org/classes/ActionView/Helpers/AssetUrlHelper.html) , so when it compiles the css file it will use the digested version of the asset.
is this `briefcase.png` a new asset you are using, or something that exists already?

**Comment by davidsteinsland** [comment]
If I run:
`rake assets:clean && rake assets:clobber && rake assets:precompile`.
And reload the page/server, it is still trying to access icons *without* the hash.

**Comment by arthurnn** [comment]
@davidsteinsland is that on development environment or production? In development sprockets fallback the digest lookups to the undigested file. In production it doesnt! make sure the manifest.json file is there, and also if the stylesheet file is using the rails helper!

**Comment by davidsteinsland** [comment]
I have my configuration in `.env`, and I don't see any references to which environment gets loaded.. Is the development loaded by default?

**Comment by stevecrozz** [comment]
It sounds like you're troubleshooting a production environment, right? If so, you'll want to make sure your RAILS_ENV is set to production. You could try just setting the environment by setting RAILS_ENV=production as part of your environment, or putting it in your .env file.

**Comment by danielbeardsley** [comment]
Had the same issue, and yes, you just need to set the env var.

`RAILS_ENV=production rake assets:precompile`
