### ISSUE TITLE
uninitialized constant IssueTrackers

### ISSUE THREAD

**Issue by YOUConsulting** [errbit/errbit#837]
Hi!

I just upgraded Errbit after 2 years, when I click on the Apps I get the following error:

**NameError: uninitialized constant IssueTrackers**

**This is the possible error location:**

[PROJECT_ROOT]/models[PROJECT_ROOT].rb:123→ issue_tracker_configured?
[PROJECT_ROOT]/helpers[PROJECT_ROOT]s_helper.rb:47→ block in detect_any_apps_with_attributes
[PROJECT_ROOT]/helpers[PROJECT_ROOT]s_helper.rb:44→ each
[PROJECT_ROOT]/helpers[PROJECT_ROOT]s_helper.rb:44→ detect_any_apps_with_attributes
[PROJECT_ROOT]/helpers[PROJECT_ROOT]s_helper.rb:15→ any_github_repos?
[PROJECT_ROOT]/views[PROJECT_ROOT]s/index.html.haml:9→ _app_views_apps_index_html_haml__FRAGMENT__

**Trace:**
activesupport-4.1.8/lib/active_support/inflector/methods.rb:238→ const_get
activesupport-4.1.8/lib/active_support/inflector/methods.rb:238→ block in constantize
activesupport-4.1.8/lib/active_support/inflector/methods.rb:236→ each
activesupport-4.1.8/lib/active_support/inflector/methods.rb:236→ inject
activesupport-4.1.8/lib/active_support/inflector/methods.rb:236→ constantize
activesupport-4.1.8/lib/active_support/core_ext/string/inflections.rb:66→ constantize
mongoid-4.0.0/lib/mongoid/factory.rb:44→ from_db
mongoid-4.0.0/lib/mongoid/relations/builders/embedded/one.rb:21→ build
mongoid-4.0.0/lib/mongoid/relations/accessors.rb:43→ create_relation
mongoid-4.0.0/lib/mongoid/relations/accessors.rb:26→ __build__
mongoid-4.0.0/lib/mongoid/relations/accessors.rb:104→ block (2 levels) in get_relation
mongoid-4.0.0/lib/mongoid/threaded/lifecycle.rb:125→ _loading
mongoid-4.0.0/lib/mongoid/relations/accessors.rb:100→ block in get_relation
mongoid-4.0.0/lib/mongoid/threaded/lifecycle.rb:84→ _building
mongoid-4.0.0/lib/mongoid/relations/accessors.rb:99→ get_relation
mongoid-4.0.0/lib/mongoid/relations/accessors.rb:187→ block in getter
[PROJECT_ROOT]/models[PROJECT_ROOT].rb:123→ issue_tracker_configured?
[PROJECT_ROOT]/helpers[PROJECT_ROOT]s_helper.rb:47→ block in detect_any_apps_with_attributes
[PROJECT_ROOT]/helpers[PROJECT_ROOT]s_helper.rb:44→ each
[PROJECT_ROOT]/helpers[PROJECT_ROOT]s_helper.rb:44→ detect_any_apps_with_attributes
[PROJECT_ROOT]/helpers[PROJECT_ROOT]s_helper.rb:15→ any_github_repos?
[PROJECT_ROOT]/views[PROJECT_ROOT]s/index.html.haml:9→ _app_views_apps_index_html_haml__FRAGMENT__
actionview-4.1.8/lib/action_view/template.rb:145→ block in render
activesupport-4.1.8/lib/active_support/notifications.rb:161→ instrument
actionview-4.1.8/lib/action_view/template.rb:339→ instrument
actionview-4.1.8/lib/action_view/template.rb:143→ render
actionview-4.1.8/lib/action_view/renderer/template_renderer.rb:55→ block (2 levels) in render_template
actionview-4.1.8/lib/action_view/renderer/abstract_renderer.rb:38→ block in instrument
activesupport-4.1.8/lib/active_support/notifications.rb:159→ block in instrument
activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20→ instrument
activesupport-4.1.8/lib/active_support/notifications.rb:159→ instrument
actionview-4.1.8/lib/action_view/renderer/abstract_renderer.rb:38→ instrument
actionview-4.1.8/lib/action_view/renderer/template_renderer.rb:54→ block in render_template
actionview-4.1.8/lib/action_view/renderer/template_renderer.rb:62→ render_with_layout
actionview-4.1.8/lib/action_view/renderer/template_renderer.rb:53→ render_template
actionview-4.1.8/lib/action_view/renderer/template_renderer.rb:17→ render
actionview-4.1.8/lib/action_view/renderer/renderer.rb:42→ render_template
actionview-4.1.8/lib/action_view/renderer/renderer.rb:23→ render
actionview-4.1.8/lib/action_view/rendering.rb:99→ _render_template
actionpack-4.1.8/lib/action_controller/metal/streaming.rb:217→ _render_template
actionview-4.1.8/lib/action_view/rendering.rb:82→ render_to_body
actionpack-4.1.8/lib/action_controller/metal/rendering.rb:32→ render_to_body
actionpack-4.1.8/lib/action_controller/metal/renderers.rb:32→ render_to_body
actionpack-4.1.8/lib/abstract_controller/rendering.rb:25→ render
actionpack-4.1.8/lib/action_controller/metal/rendering.rb:16→ render
actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:41→ block (2 levels) in render
activesupport-4.1.8/lib/active_support/core_ext/benchmark.rb:12→ block in ms
[PROJECT_ROOT]/vendor/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294→ realtime
activesupport-4.1.8/lib/active_support/core_ext/benchmark.rb:12→ ms
actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:41→ block in render
actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:84→ cleanup_view_runtime
actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:40→ render
actionpack-4.1.8/lib/action_controller/metal/implicit_render.rb:10→ default_render
actionpack-4.1.8/lib/action_controller/metal/implicit_render.rb:5→ send_action
actionpack-4.1.8/lib/abstract_controller/base.rb:189→ process_action
actionpack-4.1.8/lib/action_controller/metal/rendering.rb:10→ process_action
actionpack-4.1.8/lib/abstract_controller/callbacks.rb:20→ block in process_action
activesupport-4.1.8/lib/active_support/callbacks.rb:113→ call
activesupport-4.1.8/lib/active_support/callbacks.rb:113→ call
activesupport-4.1.8/lib/active_support/callbacks.rb:149→ block in halting_and_conditional
activesupport-4.1.8/lib/active_support/callbacks.rb:149→ call
activesupport-4.1.8/lib/active_support/callbacks.rb:149→ block in halting_and_conditional
activesupport-4.1.8/lib/active_support/callbacks.rb:149→ call
activesupport-4.1.8/lib/active_support/callbacks.rb:149→ block in halting_and_conditional
activesupport-4.1.8/lib/active_support/callbacks.rb:149→ call
activesupport-4.1.8/lib/active_support/callbacks.rb:149→ block in halting_and_conditional
activesupport-4.1.8/lib/active_support/callbacks.rb:149→ call
activesupport-4.1.8/lib/active_support/callbacks.rb:149→ block in halting_and_conditional
activesupport-4.1.8/lib/active_support/callbacks.rb:166→ call
activesupport-4.1.8/lib/active_support/callbacks.rb:166→ block in halting
activesupport-4.1.8/lib/active_support/callbacks.rb:166→ call
activesupport-4.1.8/lib/active_support/callbacks.rb:166→ block in halting
activesupport-4.1.8/lib/active_support/callbacks.rb:166→ call
activesupport-4.1.8/lib/active_support/callbacks.rb:166→ block in halting
activesupport-4.1.8/lib/active_support/callbacks.rb:229→ call
activesupport-4.1.8/lib/active_support/callbacks.rb:229→ block in halting
activesupport-4.1.8/lib/active_support/callbacks.rb:166→ call
activesupport-4.1.8/lib/active_support/callbacks.rb:166→ block in halting
activesupport-4.1.8/lib/active_support/callbacks.rb:166→ call
activesupport-4.1.8/lib/active_support/callbacks.rb:166→ block in halting
activesupport-4.1.8/lib/active_support/callbacks.rb:86→ call
activesupport-4.1.8/lib/active_support/callbacks.rb:86→ run_callbacks
actionpack-4.1.8/lib/abstract_controller/callbacks.rb:19→ process_action
actionpack-4.1.8/lib/action_controller/metal/rescue.rb:29→ process_action
actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:31→ block in process_action
activesupport-4.1.8/lib/active_support/notifications.rb:159→ block in instrument
activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20→ instrument
activesupport-4.1.8/lib/active_support/notifications.rb:159→ instrument
actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:30→ process_action
actionpack-4.1.8/lib/action_controller/metal/params_wrapper.rb:250→ process_action
actionpack-4.1.8/lib/abstract_controller/base.rb:136→ process
actionview-4.1.8/lib/action_view/rendering.rb:30→ process
actionpack-4.1.8/lib/action_controller/metal.rb:196→ dispatch
actionpack-4.1.8/lib/action_controller/metal/rack_delegation.rb:13→ dispatch
actionpack-4.1.8/lib/action_controller/metal.rb:232→ block in action
actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:82→ call
actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:82→ dispatch
actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:50→ call
actionpack-4.1.8/lib/action_dispatch/journey/router.rb:73→ block in call
actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59→ each
actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59→ call
actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:678→ call
omniauth-1.1.4/lib/omniauth/strategy.rb:184→ call!
omniauth-1.1.4/lib/omniauth/strategy.rb:164→ call
warden-1.2.3/lib/warden/manager.rb:35→ block in call
warden-1.2.3/lib/warden/manager.rb:34→ catch
warden-1.2.3/lib/warden/manager.rb:34→ call
rack-1.5.2/lib/rack/etag.rb:23→ call
rack-1.5.2/lib/rack/conditionalget.rb:25→ call
rack-1.5.2/lib/rack/head.rb:11→ call
actionpack-4.1.8/lib/action_dispatch/middleware/params_parser.rb:27→ call
actionpack-4.1.8/lib/action_dispatch/middleware/flash.rb:254→ call
rack-1.5.2/lib/rack/session/abstract/id.rb:225→ context
rack-1.5.2/lib/rack/session/abstract/id.rb:220→ call
actionpack-4.1.8/lib/action_dispatch/middleware/cookies.rb:560→ call
actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:29→ block in call
activesupport-4.1.8/lib/active_support/callbacks.rb:82→ run_callbacks
actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:27→ call
actionpack-4.1.8/lib/action_dispatch/middleware/remote_ip.rb:76→ call
actionpack-4.1.8/lib/action_dispatch/middleware/debug_exceptions.rb:17→ call
actionpack-4.1.8/lib/action_dispatch/middleware/show_exceptions.rb:30→ call
railties-4.1.8/lib/rails/rack/logger.rb:38→ call_app
railties-4.1.8/lib/rails/rack/logger.rb:20→ block in call
activesupport-4.1.8/lib/active_support/tagged_logging.rb:68→ block in tagged
activesupport-4.1.8/lib/active_support/tagged_logging.rb:26→ tagged
activesupport-4.1.8/lib/active_support/tagged_logging.rb:68→ tagged
railties-4.1.8/lib/rails/rack/logger.rb:20→ call
request_store-1.1.0/lib/request_store/middleware.rb:8→ call
actionpack-4.1.8/lib/action_dispatch/middleware/request_id.rb:21→ call
rack-1.5.2/lib/rack/methodoverride.rb:21→ call
rack-1.5.2/lib/rack/runtime.rb:17→ call
activesupport-4.1.8/lib/active_support/cache/strategy/local_cache_middleware.rb:26→ call
actionpack-4.1.8/lib/action_dispatch/middleware/static.rb:84→ call
rack-1.5.2/lib/rack/sendfile.rb:112→ call
railties-4.1.8/lib/rails/engine.rb:514→ call
railties-4.1.8/lib/rails[PROJECT_ROOT]lication.rb:144→ call
rack-1.5.2/lib/rack/deflater.rb:25→ call
unicorn-4.8.3/lib/unicorn/http_server.rb:576→ process_client
unicorn-4.8.3/lib/unicorn/http_server.rb:670→ worker_loop
unicorn-4.8.3/lib/unicorn/http_server.rb:525→ spawn_missing_workers
unicorn-4.8.3/lib/unicorn/http_server.rb:140→ start
unicorn-4.8.3/bin/unicorn:126→ <top (required)>
[PROJECT_ROOT]/vendor/bundle/ruby/2.1.0/bin/unicorn:23→ load
[PROJECT_ROOT]/vendor/bundle/ruby/2.1.0/bin/unicorn:23→ <main>

**Comment by stevecrozz** [comment]
You may just need to run migrations, but in case running migrations removes evidence of a possible bug, can you save the output from these console commands before you run migrations?
```ruby
App.all.map { |a| a.attributes }
and
App.all.map { |a| a.attributes['issue_tracker'] }
```

**Comment by YOUConsulting** [comment]
@stevecrozz  cool indeed I just had to do:

heroku run rake db:migrate
heroku restart

Thanks!
