### ISSUE TITLE
Cannot connect to MongoDB ReplSet

### ISSUE THREAD

**Issue by ginkel** [errbit/errbit#849]
With the current master, when connecting to a MongoDB ReplSet (using MONGO_URL) an exception about a malformed URI is raised.

Example URI triggering the issue: mongodb://host1:27017,host2:27017/errbit_production

The culprit is in config/mongo.rb:4.

**Comment by stevecrozz** [comment]
We're assuming that MONGO_URL is a valid URI, but in your case its got two hosts. Where did you find the idea to put both hosts in the URL?

**Comment by stevecrozz** [comment]
Ah. I see now its in the docs: http://docs.mongodb.org/manual/reference/connection-string/

Thanks for the report.

**Comment by stevecrozz** [comment]
I'm mulling over this fix in #851 which just passes the URI along to Mongoid which seems to handle the multi-host config. Do you want to give it a shot? @ginkel?

**Comment by ginkel** [comment]
That's how we patched it in our fork (except for the db_name magic), so I can confirm this works correctly.

**Comment by arthurnn** [comment]
https://github.com/errbit/errbit/issues/849 should fix this problem.
Thanks @stevecrozz for the fix, and @ginkel for reporting it.
