### ISSUE TITLE
"No route matches GET /api/v3/projects/<key>/notices"

### ISSUE THREAD

**Issue by dts** [errbit/errbit#857]
I'm running a (possibly old) 0.3.0-dev version of errbit, and I hooked up the airbrake-js shim.  However, I am getting a 404 on the route its using to push the errors.  Is the V3 support in a later version of 0.3.0-dev?

**Comment by stevecrozz** [comment]
Errbit v0.3.0 did not include V3 API support. v0.4.0 will, but we haven't released it yet. You would have to switch to Errbit master in order to use it now.
