### ISSUE TITLE
Logging in JSON Format

### ISSUE THREAD

**Issue by andywenk** [errbit/errbit#858]
Hi,

first of all thank's a lot for errbit. It's awesome ;-).

We are using logstash for logging. I created this initializer for errbit:

     if defined?(APP_CONFIG[:errbit_api_key])
      Airbrake.configure do |config|
        config.api_key  = APP_CONFIG[:errbit_api_key]
        config.host     = APP_CONFIG[:errbit_host]
        config.port     = APP_CONFIG[:errbit_port]
        config.secure   = config.port == 443
        config.async do | notice | 
          AirbrakeDeliveryWorker.perform_async(notice.to_xml)
        end
      end
    end

Unfortunately the output from an error looks like this in the logs:

    {"@timestamp":"2015-03-17T09:46:13Z","@fields":{"pid":24850,"tid":"TID-6aoq4","context":" AirbrakeDeliveryWorker JID-7e3d38f19914ca8401954f44","program_name":null,"worker":"AirbrakeDeliveryW
    I, [2015-03-17T10:46:13.110817 #24850]  INFO -- : ** [Airbrake] Success: Net::HTTPOK
    D, [2015-03-17T10:46:13.110994 #24850] DEBUG -- : ** [Airbrake] Environment Info: [Ruby: 2.2.0] [Rails: 4.2.0] [Env: production]
    D, [2015-03-17T10:46:13.111131 #24850] DEBUG -- : ** [Airbrake] Response from Airbrake: 
    UUID: 5507f7e573616321e46f1100
    URL:  http://errbit.server.com:3000/locate/5507f7e573616321e46f1100
    {"@timestamp":"2015-03-17T09:46:13Z","@fields":{"pid":24850,"tid":"TID-6aoq4","context":" AirbrakeDeliveryWorker JID-7e3d38f19914ca8401954f44","program_name":null,"worker":"AirbrakeDeliveryW

Ho can I tell errbit, that the logs should be JSON?

Thanks a lot and all the best

Andy

**Comment by stevecrozz** [comment]
It looks like your question is about airbrake the gem (https://github.com/airbrake/airbrake), an errbit client and not about errbit. Can you confirm?

**Comment by andywenk** [comment]
Hey @stevecrozz,

thanks a lot. Yes you are right. My oversight. Sorry for the flood ;-)

Cheers

Andy

**Comment by stevecrozz** [comment]
No problem, good luck.
