### ISSUE TITLE
Errbit receive error in log, but not save this error in database

### ISSUE THREAD

**Issue by sifrah** [errbit/errbit#862]
Hello everybody,

I've recently download and setup errbit for my rails app.
I've set param of my application in the web interface errbit.

When I provoke an error, i can see the result of this error in errbit log (production.log)

```
I, [2015-03-27T17:21:03.728137 #20956]  INFO -- : Processing by Api::V3::NoticesController#create as JSON
I, [2015-03-27T17:21:03.730843 #20956]  INFO -- :   Parameters: {"notifier"=>{"name"=>"airbrake", "version"=>"4.1.0", "url"=>"https://github.com/airbrake/airbrake"}, "errors"=>[{"type"=>"NameError", "message"=>"NameError: undefined local variable or method `provokerrbitc' for #<StaticPagesController:0x00000009ea4148>",

etc..

...
```

This is my config :

``` ruby
Airbrake.configure do |config|
  config.api_key = 'KEY'
  config.host    = 'myserver.com'
  config.port    = 80
  config.secure  = config.port == 443
  config.project_id = 'KEY'
end

class Airbrake::Sender
  def json_api_enabled?
   true
  end
end
```

So, i c'ant see the error on my errbit dashboard

Do you have an idea ?

Thanks

**Comment by stevecrozz** [comment]
Can you try without json_api_enabled?

**Comment by sifrah** [comment]
When i try with out json_api_enabled, i have this in my errbit log: 

``` 
[2015-03-27T20:06:51.875021 #3343]  INFO -- : Processing by NoticesController#create as XML
W, [2015-03-27T20:06:51.876675 #3343]  WARN -- : Can't verify CSRF token authenticity
I, [2015-03-27T20:06:51.907359 #3343]  INFO -- :   Rendered text template (0.1ms)
I, [2015-03-27T20:06:51.908589 #3343]  INFO -- : Completed 200 OK in 33ms (Views: 2.1ms)
```

**Comment by stevecrozz** [comment]
@sifrah Airbrake recently release a v5 version of their gem which uses the JSON API. I updated the instructions also and tested them to make sure they work: https://github.com/errbit/errbit/commit/ff341e5e5bb20512b7c423ce010d613dcc31fbac

Are you able to give it another shot with airbrake v5?
