### ISSUE TITLE
smtp setting does not working

### ISSUE THREAD

**Issue by orangeetv** [errbit/errbit#863]
Right now email will not sent even if user has configured smtp correctly. The following change has to be made in config/initializers/action_mailer.rb:

-if Errbit::Config.email_delivery_method == :smtp
+if Errbit::Config.email_delivery_method == 'smtp'
  
-if Errbit::Config.email_delivery_method == :sendmail
+if Errbit::Config.email_delivery_method == 'sendmail'

Errbit::Config.email_delivery_method is a String so that comparing it with Symbol will fail.

**Comment by stevecrozz** [comment]
It seems to be working for me. Are you providing this parameter as a yaml-parsable symbol?

```bash
$ EMAIL_DELIVERY_METHOD=:smtp bundle exec rails console

From: /home/stevecrozz/Projects/errbit/errbit/config/initializers/action_mailer.rb @ line 2 :

    1: # Set SMTP settings if given.
 => 2: binding.pry
    3: if Errbit::Config.email_delivery_method == :smtp
    4:   ActionMailer::Base.delivery_method = :smtp
    5:   ActionMailer::Base.smtp_settings = {
    6:     :address        => Errbit::Config.smtp_address,
    7:     :port           => Errbit::Config.smtp_port,

[1] pry(main)> Errbit::Config.email_delivery_method
=> :smtp
[2] pry(main)> Errbit::Config.email_delivery_method.class
=> Symbol
```

**Comment by orangeetv** [comment]
No, I am setting it with env variable. It is always a string in that case.

**Comment by stevecrozz** [comment]
In my example above, I also set it as an environment variable. What I'm saying is, you need to use a colon and it will be parsed by YAML as a symbol.

**Comment by orangeetv** [comment]
Got it. Not intuitive but works. Thanks.

**Comment by stevecrozz** [comment]
Sure, let me know if you have a suggestion for improving the docs in this area.
