### ISSUE TITLE
App Server not in notification email?

### ISSUE THREAD

**Issue by TinajaLabs** [errbit/errbit#870]
I need to filter the notification emails by App Server but that value does not appear to be sent in the notification emails.  Is there a reason this is missing?  

I'm sending alerts to pagerduty but I will need to filter the pagerduty service to only accept input from specific App Servers.

Can someone suggest how to make sure this is included in all notification emails.

Thanks for any advice,
Chris.

**Comment by stevecrozz** [comment]
Should be fixed in master.
