### ISSUE TITLE
Unable to send emails 

### ISSUE THREAD

**Issue by mik3lon** [errbit/errbit#876]
Hi all,

It's impossible for me to send emails through errbit,

I put my configuration like this:

require 'tlsmail'    
  Net::SMTP.enable_tls(OpenSSL::SSL::VERIFY_NONE)

  ActionMailer::Base.delivery_method = :smtp
  ActionMailer::Base.perform_deliveries = true
  ActionMailer::Base.raise_delivery_errors = true
  ActionMailer::Base.smtp_settings = {
    :enable_starttls_auto => true,  
    :address            => 'smtp.gmail.com',
    :port               => "587",
    :tls                  => true,
    :domain             => 'gmail.com', #you can also use google.com
    :authentication     => "plain",
    :user_name          => 'miguelgarciaponce85@gmail.com',
    :password           => 'password'
  }

In console i get:

Mailer#err_notification: processed outbound mail in 156.6ms

Sent mail to miguelgarciaponce85@gmail.com (9.2ms)
Date: Wed, 29 Apr 2015 22:26:24 +0200
From: errbit@example.com
To: miguelgarciaponce85@gmail.com
Message-ID: <55413e7019baf_1da534fed1025711@mike-workstation.mail>
Subject: [errbit_test][development] Exception: AKI
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_55413e70116ac_1da534fed102568f";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
X-Errbit-App: errbit_test
X-Errbit-Environment: development
X-Errbit-Error-Id: 55413e6f6d696b1da5010000
X-Errbit-Host: errbit.example.com
X-Mailer: Errbit
X-Auto-Response-Suppress: OOF, AutoReply
Precedence: bulk
Auto-Submitted: auto-generated

----==_mimepart_55413e70116ac_1da534fed102568f
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

An error has just occurred in development: Exception: AKI

This error has occurred 1 time. You should really look into it here:

  http://errbit.example.com/apps/55410c376d696b4d32010000/problems/55413e6f6d696b1da5000000

ERROR MESSAGE:

Exception: AKI

WHERE:

unknown

URL:

http://localhost/errbit_test/index.php

BROWSER:

Chrome 41.0.2272.101 (Linux x86_64)

BACKTRACE:

  /var/www/html/errbit_test/index.php:19
  [unknown source]:

Your loyal servant,
Errbit

----==_mimepart_55413e70116ac_1da534fed102568f
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    
  </head>
  <body leftmargin="0" marginheight="0" marginwidth="0" offset="0" topmargin="0">
    <center>
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tbody>
          <tr>
            <td class="header" style="height: 70px; background-color: #11112f; text-align: left; border-bottom-width: 1px; border-bottom-color: #ccccee; border-bottom-style: solid; padding: 10px 20px 8px;" align="left" bgcolor="#11112f">
              <a href="http://errbit.example.com/" style="display: block; height: 31px; width: 88px; margin-top: 4px;"><img alt="Errbit" src="http://errbit.example.com/assets/images/logo.png" style="color: #E3E3E3; font-family: helvetica; font-size: 30px; font-weight: bold; min-height: 31px; text-shadow: 0 1px 0 #EEEEFF; border: none;"></a>
            </td>
          </tr>
          <tr>
            <td class="section" style="font-family: Helvetica,Arial,sans-serif; font-size: 14px; text-align: left; border-bottom-width: 1px; border-bottom-color: #dddddd; border-bottom-style: solid; background-color: #ffffff; padding: 0;" align="left" bgcolor="#ffffff">
              <table align="left" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                  <tr>
                    <td class="content" valign="top" style="font-family: Helvetica,Arial,sans-serif; font-size: 14px; text-align: left; line-height: 1.3em; background-color: #ffffff; padding: 20px 20px 10px;" align="left" bgcolor="#ffffff">
                      <div>
                        <p style="margin: 0 0 15px;">
                          An error has just occurred in
                          <a class="bold" href="http://errbit.example.com/apps/55410c376d696b4d32010000" style="font-weight: bold;">errbit_test</a>,
                          on the
                          <span class="bold" style="font-weight: bold;">development</span>
                          environment.
                          <br>
                          This error has occurred 1 time.
                        </p>
                        <p style="margin: 0 0 15px;">
                          <a class="bold" href="http://errbit.example.com/apps/55410c376d696b4d32010000/problems/55413e6f6d696b1da5000000" style="font-weight: bold;">Click here to view the error on Errbit</a>.
                        </p>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
          <tr>
            <td class="section" style="font-family: Helvetica,Arial,sans-serif; font-size: 14px; text-align: left; border-bottom-width: 1px; border-bottom-color: #dddddd; border-bottom-style: solid; background-color: #ffffff; padding: 0;" align="left" bgcolor="#ffffff">
              <table align="left" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                  <tr>
                    <td class="content" valign="top" style="font-family: Helvetica,Arial,sans-serif; font-size: 14px; text-align: left; line-height: 1.3em; background-color: #ffffff; padding: 20px 20px 10px;" align="left" bgcolor="#ffffff">
                      <div>
                        <p class="heading" style="color: #6a6a6a; margin: 0 0 4px;">ERROR MESSAGE:</p>
                        <p style="margin: 0 0 15px;">Exception: AKI</p>
                        <p class="heading" style="color: #6a6a6a; margin: 0 0 4px;">WHERE:</p>
                        <p class="monospace" style="font-family: monospace; margin: 0 0 15px;">
                          unknown
                        </p>
                        <br>
                        <p class="heading" style="color: #6a6a6a; margin: 0 0 4px;">URL:</p>
                        <p class="monospace" style="font-family: monospace; margin: 0 0 15px;">
                          <a href="http://localhost/errbit_test/index.php">http://localhost/errbit_test/index.php</a>
                        </p>
                        <p class="heading" style="color: #6a6a6a; margin: 0 0 4px;">BROWSER:</p>
                        <p class="monospace" style="font-family: monospace; margin: 0 0 15px;">
                          </p>
<div class="head_and_tail">
                            <table class="tally head">
                              <tbody>
                                <tr>
                                  <td class="percent">100.0%</td>
                                  <th class="value">Chrome 41.0.2272.101 (Linux x86_64)</th>
                                </tr>
                              </tbody>
                            </table>
                            <table class="tally tail" style="display: none;">
                              <tbody>
                              </tbody>
                            </table>
                          </div>
                        
                        <br>
                        <br>
                        <p class="heading" style="color: #6a6a6a; margin: 0 0 4px;">FULL BACKTRACE:</p>
                        <p class="backtrace" style="font-family: monospace; margin: 0 0 2px;">
                          /var/www/html/errbit_test/index.php:19
                        </p>
                        <p class="backtrace" style="font-family: monospace; margin: 0 0 2px;">
                          [unknown source]:
                        </p>
                        <br>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
          <tr>
            <td class="footer" style="font-family: Helvetica,Arial,sans-serif; font-size: 11px; text-align: left; font-weight: bold; color: #666666; background-color: #ffffff; padding: 10px 20px 20px;" align="left" bgcolor="#ffffff">
              Your loyal servant,
              <a href="http://errbit.example.com/">Errbit</a>
            </td>
          </tr>
        </tbody>
      </table>
    </center>
  </body>
</html>

----==_mimepart_55413e70116ac_1da534fed102568f--

Completed 200 OK in 297ms (Views: 0.1ms)

but I never receive the email.

Could you help me? Where is the best place to put my config? 

In addition I have :
config.action_mailer.raise_delivery_errors = true
 config.action_mailer.delivery_method = :smtp

So i don't know what i'm doing wrong... 

Thank you!

**Comment by stevecrozz** [comment]
I can't tell where you have made these configuration changes, but the way we do configuration now is through environment variables. Have you tried setting them according to the configuration docs? https://github.com/errbit/errbit/blob/master/docs/configuration.md

You would need to set EMAIL_DELIVERY_METHOD, and the SMTP_* variables in your case.

**Comment by mik3lon** [comment]
i have in .env.default these variables like:

EMAIL_DELIVERY_METHOD= :smtp
SMTP_SERVER='smtp.gmail.com'
SMTP_PORT='587'
SMTP_AUTHENTICATION=:plain
SMTP_USERNAME="miguelgarciaponce85@gmail.com"
SMTP_PASSWORD="password"
SMTP_DOMAIN="gmail.com"
SMTP_STARTTLS_AUTO=true
SMTP_TSL = true


but the same result..

Thank you in advance :)

**Comment by stevecrozz** [comment]
According to the rails docs, these are the required settings:
http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration-for-gmail

You can probably remove SMTP_STARTTLS_AUTO=true and SMTP_TSL=true because those are not configurations that errbit supports. So they don't do anything and the ActionMailer defaults should be fine. You can also put these in a .env file instead of .env.default if you like.

But that won't fix the problem. The only thing I see that could potentially be wrong is SMTP_AUTHENTICATION is supposed to be a string, but you have provided a symbol. Do you want to try putting this in your .env file?

```
EMAIL_DELIVERY_METHOD=:smtp
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_DOMAIN=gmail.com
SMTP_USERNAME="miguelgarciaponce85@gmail.com"
SMTP_PASSWORD="password"
SMTP_AUTHENTICATION=plain
```

**Comment by mik3lon** [comment]
Thank you for your comment,

I tried that and not worked. I'll try with another gmail account, because i have read that you receive an alert by gmail to inform you that that service is in use and you have to allow it. I don't see that alert in my gmail account so, i'll try with another (I used that account for smtp years ago and maybe it's blocked for that purpose). And well, I will try to figure out what's happening here. We see this platform as a good way to manage errors in the job.

Thank you and if I figure out something i'll put here ;)

**Comment by mik3lon** [comment]
Ok so that was the problem. Google blocked my gmail accout to send emails by smtp protocol. So i created a new account and it works like a charm!

Thank you @stevecrozz!
