### ISSUE TITLE
LGPL3 favicon from Oxygen icon theme used without correct licensing/attribution

### ISSUE THREAD

**Issue by wstephenson** [errbit/errbit#879]
Errbit uses an icon taken from the Oxygen icon theme as its favicon. The licensing for the icon is described here: https://techbase.kde.org/Projects/Oxygen/Licensing#Use_in_Applications

Please include the icon sources, a copy of LGPL3, and a note explaining that this part of your source tree is covered by LGPL3 in the errbit sources.

The canonical repository for the SVG source of the icon is here:
http://websvn.kde.org/trunk/kdesupport/oxygen-icons/scalable/apps/kbugbuster.svgz

**Comment by stevecrozz** [comment]
Thanks for reporting this. I didn't realize this icon belonged to someone else. I'm just going to replace the icon to avoid this issue.
