### ISSUE TITLE
Reset admin password

### ISSUE THREAD

**Issue by Firfi** [errbit/errbit#880]
I forgot password generated with rake errbit:bootstrap (actually right after generation, I just didn't noticed it), now any run of rake errbit:bootstrap gives me new password. It doesn't work though for login, 

i.e. 

-- email:    errbit@errbit.example.com
-- password: 9Z0QENekDvOY

gives me 'invalid login details' on login.

**Comment by stevecrozz** [comment]
The db:seed was designed for a one-time run, but I think making it idempotent is a nice idea, so I just merged a change to allow that. If you pull the latest code, you should be able to reset your password this way.
