### ISSUE TITLE
configurable fingerprinting

### ISSUE THREAD

**Issue by stevecrozz** [errbit/errbit#884]
Fingerprinting errors is currently pretty opaque. Errors are fingerprinted based on rules defined in fingerprinting classes. Changing the fingerprinting algorithm is a system-wide change and requires a new initializer in the best case and requires implementing a new class in the worst case. Further, the classes have strange names that have little to do with the factors that determine uniqueness.

I propose we make fingerprinting configurable. In my proposal, there would be a number of possible factors that could be chosen to be part of the fingerprint algorithm such as:
- last line of backtrace
- whole backtrace
- exception name
- exception message
- action name
- etc

~~The default would be made to match the current default algorithm. But in the edit screen for each app, admins could choose the factors that should determine uniqueness of an error for that app. We would store these rules on the app itself, so the performance penalty should be low since we already load the  app when inserting error notifications.~~

Just to descope this story a bit more into the realm of reality, let's start with system-wide configurable fingerprinting and add app-level configuration only if it becomes necessary. This should reduce the complexity considerably and still provide something with plenty of value.

**Comment by bekicot** [comment]
+1

**Comment by stevecrozz** [comment]
Fixed with #946
