### ISSUE TITLE
New installation sign in fail

### ISSUE THREAD

**Issue by lessmind** [errbit/errbit#894]
I started a new installation with tag v0.4.0, followed instructions from this page http://errbit.github.io/errbit/#section-2

All steps executed successfully.

But I can't sign in to this whole new system.
It just keep displaying "Invalid email or password."

I DID used the email / password displayed with this command
```shell
bundle exec rake errbit:bootstrap
```

Which looks like
```shell
Creating an initial admin user:
-- email:    errbit@errbit.example.com
-- password: XXXXXXXXXXXXXX
```

I reinstalled it, empty the database, clicked the forget password link (Which gives me "Email not found"), and nothing works.

I tried to trace the code, but I'm not familiar with rails and full text search doesn't help either.

Is there a bug or I did anything wrong?

Environment details:
```shell
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux

$ bundle -v
Bundler version 1.8.4

$ rake --version
rake, version 10.4.2

$ rails --version
Rails 4.1.8

$ gem -v
2.4.6

$  mongo --version
MongoDB shell version: 3.0.3
```

**Comment by lessmind** [comment]
Seems like I should add RAILS_ENV=production when seeding data base
```shell
bundle exec rake errbit:bootstrap RAILS_ENV=production
```

**Comment by stevecrozz** [comment]
Ah that makes sense. You were bootstrapping your development db but running the app on the production db. I'm glad you figured that out.
