### ISSUE TITLE
Access-Control-Allow-Origin for js error

### ISSUE THREAD

**Issue by Piioo** [errbit/errbit#898]
I have added airbrake-js-client to my project and throw a test exception in JavaScript.
But my browser is thrown this error:

XMLHttpRequest cannot load https://errbit.erbitdomain.de/api/v3/projects/1/create-notice?key=my_key. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.myapp.de' is therefore not allowed access. The response had HTTP status code 404.

Where do I have to configure something to get it work?

**Comment by stevecrozz** [comment]
@Piioo what version or sha1 of errbit are you using? And can you tell me if this error message relates to the actual POST or the preflight OPTIONS request?

**Comment by confiks** [comment]
Airbrake-js is currently not compatible with Errbit. Use 0.4.2 instead. See issue https://github.com/errbit/errbit/issues/900

**Comment by stevecrozz** [comment]
@confiks has identified the problem in #900. So I'll close this issue and we can track progress over there.

**Comment by mfazekas** [comment]
I'm using airbrake-js 0.5.3 and errbit afb42823560d898b0ab19a272705cde03b2a36d9 and i still see this error: 

```
XMLHttpRequest cannot load https://xxx-errbit.herokuapp.com/api/v3/projects/xxx/create-notice?key=xxx. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://xxx.com' is therefore not allowed access.
```
i've added CORS headers which seems to solved the issue. 
```
  def create
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Headers'] = 'origin, content-type, accept'
```

**Comment by stevecrozz** [comment]
Thanks for the report @mfazekas. I raised your issue separately here: https://github.com/errbit/errbit/issues/970
