### ISSUE TITLE
Incompatibility with airbrake-js version 0.4.3

### ISSUE THREAD

**Issue by confiks** [errbit/errbit#900]
In airbrake-js version 0.4.3, a pull request was merged (https://github.com/airbrake/airbrake-js/pull/143) that switches the reporting URL from 'notices' to 'create-notice'. The JSON Content-Type is dropped. Apparently this doesn't send a preflight OPTION HTTP call.

Errbit doesn't support this new URL.

**Comment by stevecrozz** [comment]
Thanks for this report. We should be back in business:
https://github.com/errbit/errbit/commit/6a233224beeb6f7882f488cbfc41a2858f8f00bb

**Comment by rsutphin** [comment]
It's great that errbit could be updated so quickly to match this change in airbrake-js. I'm using errbit in a way that it's not possible to simultaneously update errbit and all my JS clients in one fell swoop. @stevecrozz, would you be willing to have errbit support both v3 API endpoints?
