### ISSUE TITLE
number of backtrace lines?

### ISSUE THREAD

**Issue by FrodeMMeling** [errbit/errbit#902]
Hello
We use Errbit on a CakePHP Application using the Cake plugin Airbreak. Backtrace worked fine on Airbreak servers, but when we switched to Errbit, it seems trace is flipped and does not include enough lines. Is it possible to increase the number of lines shown in backtrace?

**Comment by stevecrozz** [comment]
Thanks for the report @FrodeMMeling . Would you be able to send me a gist or some instructions to reproduce this issue?
