### ISSUE TITLE
Heroku deployment doc outdated + gem incompatibility 

### ISSUE THREAD

**Issue by arnaudpsy** [errbit/errbit#906]
Is omitted in your doc but you need to uncomment Device.secret for deploy on Heroku.

We need to upgrade gem 'uglifier', '~> 2.7'

Problem seemed to be an incompatibility between Sprockets 3.1 and the Uglifier compressor version I was using, 2.1. Upgrading Uglifier by putting this line in my Gemfile resolved the issue:
http://stackoverflow.com/questions/30338860/heroku-push-error-nameerror-uninitialized-constant-uglifierversion-on-rake

**Comment by stevecrozz** [comment]
I updated a bunch of dependencies just now, including uglifier:
https://github.com/errbit/errbit/commit/2d4c3e4bf35ffee6b90e0d8cca6559bb85a6969d

Can you explain what you mean about uncommenting Devise.secret?

**Comment by arnaudpsy** [comment]
For sure.

In your [Heroku documentation deployment](https://github.com/arnaudpsy/errbit/blob/master/docs/deployment/heroku.md) this part is missing. This mean if you leave Devise.secret_key commented your deployment fail miserably.

![capture d ecran 2015-06-30 10 31 24](https://cloud.githubusercontent.com/assets/1267921/8426927/b2ebd82e-1f13-11e5-8bc0-204d43288f2e.png)

**Comment by stevecrozz** [comment]
@arnaudpsy can you verify that you followed these steps, especially setting the SECRET_KEY_BASE environment variable?
https://github.com/arnaudpsy/errbit/blob/master/docs/deployment/heroku.md#create-an-app-on-heroku-and-push-the-source-code

**Comment by stevecrozz** [comment]
It's working for me when I follow the docs, so I'm going to close this for lack of reproducibility.
