### ISSUE TITLE
Version displayed in footer is incorrect

### ISSUE THREAD

**Issue by kohenkatz** [errbit/errbit#908]
I just upgraded from 0.3.0 to 0.4.0, and was very confused when the version in the footer still said "0.3.0.dev".  The [file](https://github.com/errbit/errbit/blob/master/lib/errbit/version.rb) which contains that information hasn't been updated in about 2 years.  This caused me to spend a long time trying to figure out why the old version was still running, only to find that this is the new version which is displaying an old version number.  Perhaps this should be fixed so that no one else wastes time troubleshooting a non-issue.

**Comment by stevecrozz** [comment]
Thanks @kohenkatz. I'll get this prioritized.

**Comment by stevecrozz** [comment]
Unfortunately I can't fix the released version since it's already released, but I updated master and changed the code so I'll find it next time when I'm grepping for version numbers.

**Comment by robinboening** [comment]
@stevecrozz why not delete the current `0.4.0` release and release it with the correct version? Sounds very simple :)
