### ISSUE TITLE
remove the deployment tracking feature

### ISSUE THREAD

**Issue by stevecrozz** [errbit/errbit#913]
The idea of having a way to track which errors belong to which deployed versions is a good one, but application version should be a first class and immutable property of an error, submitted along with all the other error properties to the notifications API. Tracking versions as a property of the error notification is a documented part of the Airbrake v3 api: https://gist.github.com/vmihailenco/14b538ccfb127eaea51e#file-gistfile1-txt-L50 and since many versions of one app can be deployed at the same time, it makes much more sense to do things this way.

This task is to remove support for deployment tracking as a standalone feature and add a little UI around navigation errors that belong to specific app versions.

**Comment by mattbostock** [comment]
While not all apps will have awareness of their own version number, I think this change makes sense given:

a. blue-green deployments are being more common, especially given the rise in popularity of containers (so multiple versions of the same application running are more common)
b. tracking deployments is not an obvious feature for an application concerned with storing exceptions

Will it be possible to mark all errors tied to a specific version as resolved?

**Comment by stevecrozz** [comment]
Deployment tracking is gone in master

**Comment by svoop** [comment]
@stevecrozz Dropping the deployment tracking feature in favor of a version property sounds like a good move. However, given the app is aware of it's version (e.g. by asking git), how would you pass this info to the Airbrake gem in order to have the version property passed to Errbit? A little example would be very helpful.

**Comment by stevecrozz** [comment]
@svoop If you're using the JSON API, I think the right field to use is context.version: https://airbrake.io/docs/#create-notice-v3

Errbit doesn't yet have any smarts for what to do with this info, but if you have some ideas we could discuss them on the mailing list or the gitter chat.

**Comment by svoop** [comment]
@stevecrozz 

> If you're using the JSON API, I think the right field to use is context.version: https://airbrake.io/docs/#create-notice-v3

I'm just using the airbrake gem, can you give me a hint how to set the context.version there? (I was trying to find it in the docs, but I'm not sure whether Errbit is already compatible with the rewritten airbrake gem version 5.)

**Comment by svoop** [comment]
@stevecrozz 

> Errbit doesn't yet have any smarts for what to do with this info, but if you have some ideas we could discuss them on the mailing list or the gitter chat.

A dead-simple solution to track deployments now that this feature is gone:

    Airbrake.configure do |config|
      (...)
      config.environment_name = "#{Rails.env}@#{Rugged::Repository.new(Rails.root.to_s).last_commit.oid[0,4]}"
    end

No new smarts are required at all, Errbit shows the environment e.g. as "staging@0f3d". And clicking on it, the linked search returns only problems from this enviroment and release.

**Comment by arrowcircle** [comment]
Hey!
Another aspect of this feature is deploy tracking (who when what).
Also, it breaks compatibility with airbrake v5 feature. Should we stub it with OK https status to keep compatibility?

**Comment by stevecrozz** [comment]
@arrowcircle What would be the reason? Is there something broken? I wouldn't want to try to support the complete airbrake API for the purpose of completeness. Maybe we should instead clarify the language about API support in the README file. We do attempt to support the error notification action: https://airbrake.io/docs/api/#create-notice-v3 but I wouldn't make any claims to Airbrake API compatibility beyond that.

**Comment by mattscilipoti** [comment]
The initial description included both "remove support for deployment tracking as a standalone feature" and "**add a little UI around navigation errors that belong to specific app versions.**"  I can't find any commits for the second part, the UI changes that support this.  Am I just missing them?

**Comment by stevecrozz** [comment]
You haven't missed it. We do still want this feature. There's a number of stories like this one that I would group under 'advanced search' that would be super useful.
