### ISSUE TITLE
Documentation fail

### ISSUE THREAD

**Issue by prokopsimek** [errbit/errbit#915]
On page: http://errbit.github.io/errbit/#section-7-1 in upgrade guide you have link to "see configuration" and it return error 404.

**Comment by stevecrozz** [comment]
Thanks. The docs site does need some work. If you need a better reference, the README.md on github autolinks to the right locations:
https://github.com/errbit/errbit/blob/master/README.md

**Comment by lucianosousa** [comment]
outdated. I think it's can be closed

**Comment by stevecrozz** [comment]
@lucianosousa you're right, but I do actually have some big plans for a new docs site, so I'm going to replace this ticket with another one #1154 to track a docs site revamp.
