### ISSUE TITLE
Respect ERRBIT_PORT in creating notification URLs

### ISSUE THREAD

**Issue by wiltzius** [errbit/errbit#918]
I believe this line:

https://github.com/errbit/errbit/blob/master/app/models/notification_service.rb#L57

creates the URL that gets posted to various notification services (in our case, Slack).

We run errbit on a non-standard port, which we set via the ERRBIT_PORT env variable, but while links in the web app work fine (preserve this port) the links generated in the notifications go to the wrong place (we run another server on the same host on port 80/443).

**Comment by wiltzius** [comment]
Note that for now as a workaround I just set our ERRBIT_HOST to include the port and this seems to work, but obviously feels a little fragile

**Comment by stevecrozz** [comment]
Here's the fix I have in mind. Wanna give it a shot? https://github.com/errbit/errbit/pull/919

**Comment by wiltzius** [comment]
that seems to work great!

**Comment by wiltzius** [comment]
although, that'll only fix it for Slack. Won't anything else (e.g. other notification services) that uses the problem_url() function in notification_service.rb still have the same problem?

**Comment by stevecrozz** [comment]
good point. we should put together a PR for the other notification services

**Comment by wiltzius** [comment]
would it be reasonable to simply modify the line in the original function?

**Comment by stevecrozz** [comment]
I'd probably accept that PR, but I'd prefer not to have a method that just calls another method if I were doing it.

**Comment by stevecrozz** [comment]
fixed in master
