### ISSUE TITLE
github/bitbucket repo & repository tab

### ISSUE THREAD

**Issue by lucianosousa** [errbit/errbit#922]
hi guys,

just an idea here.

I start use it in a lot of projects here at the same time and was annoying all the time see in the form bitbucket repo, since I'm using github. This is the first part.
Second one is: why not just one field called repository and drop the repository tab in favor of a url link located on the top of the div `content-wrapper`

Looks like easier to navigate in the project like this.

What you guys think about?

**Comment by stevecrozz** [comment]
I think we do need something here, but it's lower on the priority list than most of the other backlogged items. My thought is we should have the github-centric logic wrapped up inside https://github.com/errbit/errbit_github_plugin. But there are no hooks in Errbit that would allow plugins to do what's needed.
