### ISSUE TITLE
NameError: uninitialized constant Mongoid::Errors::NoDefaultSession

### ISSUE THREAD

**Issue by ch3m1c** [errbit/errbit#927]
rake aborted!
NameError: uninitialized constant Mongoid::Errors::NoDefaultSession
/home/deploy/webapps/errbit/config/environment.rb:16:in `<top (required)>'
Mongoid::Errors::InvalidConfigOption: 

Problem:
  Invalid configuration option: identity_map_enabled.
Summary:
  A invalid configuration option was provided in your mongoid.yml, or a typo is potentially present. The valid configuration options are: :include_root_in_json, :include_type_for_serialization, :preload_models, :raise_not_found_error, :scope_overwrite_exception, :duplicate_fields_exception, :use_activesupport_time_zone, :use_utc, :timestamped_migrations.
Resolution:
  Remove the invalid option or fix the typo. If you were expecting the option to be there, please consult the following page with repect to Mongoid's configuration:

   http://mongoid.org/en/mongoid/docs/installation.html/home/deploy/webapps/errbit/config/environment.rb:16:in `<top (required)>'
Tasks: TOP => db:version => environment
(See full trace by running task with --trace)

**Comment by stevecrozz** [comment]
Looks like you still have a mongoid.yml file. You should delete that file and provide the mongo connection parameter as MONGO_URL (https://github.com/errbit/errbit/blob/master/docs/configuration.md).
