### ISSUE TITLE
App#unresolved_count is displayed as a float

### ISSUE THREAD

**Issue by funglaub** [errbit/errbit#928]
I just upgraded to the latest master and MongoDB 2.6. 

Now the unresolved problems count is displayed as a float, eg. 1.0 or 0.0.

**Comment by stevecrozz** [comment]
Thanks. I'm waiting for the answer to https://jira.mongodb.org/browse/MONGOID-4118 in order to figure out who's bug this is. But I think it may get fixed by mongoid 5 when it's officially released (we're currently using the beta).

**Comment by lucianosousa** [comment]
@funglaub mongoid was updated these days. Can you update your errbit and check if everything is fine?

**Comment by lucianosousa** [comment]
remember pull after #951 merge

**Comment by stevecrozz** [comment]
Thanks @lucianosousa. This is indeed fixed after upgrading to mongo 2.1.1. This fix is applied to master.
