### ISSUE TITLE
Any instructions on how to get errbit working with gitlab?

### ISSUE THREAD

**Issue by JohnMerlino1** [errbit/errbit#930]
I do not know where to begin with this. I read over the readme file and sparse information I found online, but it has not helped. Under App > Edit, there is a field for Github repo and Bitbucket repo, not no reference to gitlab. I found somewhere that you have to enter information under "TICKET PROJECT ID (USE NUMBER)". Unfortunately, that box does not appear. It seems like you have to create code for this. I tried using this https://github.com/brandedcrate/errbit_gitlab_plugin but again there are no instructions and in fact that gem was causing errors when loading Rails. Ultimately, where can I find instructions on how to get errbit working with gitlab?

**Comment by stevecrozz** [comment]
Errbit does not officially support any gitlab integrations. There is a third party plugin that could provide an integration with gitlab as an issue tracker. If all you need is issue tracker support for gitlab, then the plugin may work for you. Just file an issue in https://github.com/brandedcrate/errbit_gitlab_plugin and we'll try to sort out the problem you found.

And definitely let me know if you want to help maintain that plugin. As you've noticed by lack of documentation and other issues, I could use the help.

**Comment by JohnMerlino1** [comment]
@stevecrozz actually all I want is errbit to report errors. I assumed that using gitlab was the issue since it is not reporting any errors for me and I have already added the Airbrake.configure block in an initializer file.

**Comment by stevecrozz** [comment]
Most likely, the app is not sending errors properly. But you can give Errbit a quick test on the CLI with curl (replacing api-key and the hostname with your own):
```bash
echo '<?xml version="1.0" encoding="UTF-8"?>
<notice version="2.3">
  <api-key>3b3f89dd66ba3631eb0b1e8208d9330c</api-key>
  <error>
    <class>UglyError</class>
    <message>There was a problem in a buggy file</message>
    <backtrace>
      <line method="public" file="buggy_file.rb" number="53"/>
    </backtrace>
  </error>
  <server-environment></server-environment>
</notice>' | curl https://some-errbit.com/notifier_api/v2/notices/ \
  -H "Content-Type: text/xml" \
  --include \
  --data-binary @-
```
