### ISSUE TITLE
Duplicate File Name in Backtrace and Link

### ISSUE THREAD

**Issue by rposborne** [errbit/errbit#942]
A picture is worth a thousand words,  this is happening on all notices.

Happens on all projects,  
![screenshot 2015-09-09 12 14 35](https://cloud.githubusercontent.com/assets/243989/9767510/8ccb109a-56ec-11e5-809e-d10a0f6632e4.png)

**Comment by stevecrozz** [comment]
@rposborne would you be willing to try out this fix? https://github.com/stevecrozz/errbit/tree/942_undouble_filenames_in_backtraces

**Comment by stevecrozz** [comment]
I went ahead and merged the fix. You should be good to go now.
