### ISSUE TITLE
time_ago_in_words - no implicit conversion of true into Hash

### ISSUE THREAD

**Issue by j3ck** [errbit/errbit#947]
How this line working?
https://github.com/errbit/errbit/blob/master/app/views/problems/show.html.haml#L40

From 4.0 version rails hasn't ```include_seconds``` parameter, just a options hash

https://github.com/rails/rails/blob/97f2c4129ae23ee074986a588628acc689a86462/actionview/lib/action_view/helpers/date_helper.rb#L156
```
     ...
     71 def distance_of_time_in_words(from_time, to_time = 0, options = {})
     72   options = {
     73     scope: :'datetime.distance_in_words'
     74   }.merge!(options)
     ...
    138 end
```
I was moved by this question, because I get an error at this point.
```shell
[2] pry(main)> time_ago_in_words(1.minute.ago, true)
TypeError: no implicit conversion of true into Hash
```

**Comment by stevecrozz** [comment]
My guess is it doesn't work and this is a bug. I don't think many people use the comments feature and this bug would only appear when the comment is from a user who no longer exists. We should prepare a test case for this and then fix the issue.

**Comment by stevecrozz** [comment]
Thanks for reporting this @j3ck. I added a test and a fix.
