### ISSUE TITLE
SAML authentication

### ISSUE THREAD

**Issue by md5** [errbit/errbit#955]
Would you guys be open to a PR that adds `omniauth-saml` to enable optional SAML authentication for Errbit, similar to how the `GITHUB_AUTHENTICATION` stuff works?

If not, what approach would you recommend for integrating with SAML single-sign on? I'd love it if we didn't have to maintain a fork of Errbit in order to get SAML authentication.

**Comment by stevecrozz** [comment]
SAML integration sounds great. We should just talk about how it can work and be useful to a wide audience of SAML users. Do you have a place I can go look at your implementation?

**Comment by md5** [comment]
@stevecrozz I haven't written any code yet, but I'm going to talk to my colleagues next week about setting aside some time to do so. Since we'd rather not maintain a fork, my thought was that I'd fall back to using GitHub authentication against an internal GitHub Enterprise instance if you guys weren't amenable to adding `omniauth-saml` to Errbit itself.

**Comment by stevecrozz** [comment]
I'm fine with including that gem as long as the implementation is generic enough that other organizations could use it, and especially if you're willing to help maintain this feature and answer questions. I would just want to talk over how exactly the integration would work. Here's a barrage of starting questions do get the ball rolling:

Would you be able to provision new Errbit users using SAML or just log existing users in? New Errbit users would likely need at least an email address. Would we have to assume the name-id assertion is an email address? What if the SAML response doesn't contain any email address assertions? What about other assertions like first/last name or full name? Maybe we can ignore those for now and let users set their own names in the edit profile UI. Will SAML users still be able to log in with a password? Will they even be able to set a password? Would Errbit support SP-initiated login or just IdP-initiated log in? Do we care about logouts?

By the way, which IdP are you using?

**Comment by md5** [comment]
> Would you be able to provision new Errbit users using SAML or just log existing users in? New Errbit users would likely need at least an email address.

Since all apps under Errbit can be seen by all users (correct me if I'm wrong here), I think it would only make sense to allow SAML logins for existing users provisioned in Errbit. The SAML profile would be required to have an email address configured in order to make it available to Errbit for notifications.

I think this would at least work as an initial pass. I could see eventually supporting the mapping of a "role" or "member of" assertion to allow that to be used the way that `GITHUB_ORG_ID` is currently used.

> Would we have to assume the name-id assertion is an email address? What if the SAML response doesn't contain any email address assertions? What about other assertions like first/last name or full name? Maybe we can ignore those for now and let users set their own names in the edit profile UI.

I don't think we would have to assume the name-id assertion is an email address. I could envision having a `saml_name_id` field, similar to `github_user`, that could support looking up the user by name-id. However, since email address would be required for notifications anyways, I think it could also make sense to just look up the user by email address.

As for first/last/full name assertions, I don't think they matter much if users have to be provisioned in Errbit. It could be nice to update the name based on those assertions, however, to avoid having to make the user maintain their own name in the profile in the event that it changes. Then again, the IdP may not have up-to-date information about their name or may not use their preferred name. I guess that means it would depend on the integration. Probably safest to start with just ignoring the SAML name assertions.

> Will SAML users still be able to log in with a password? Will they even be able to set a password?

I don't think SAML users should be able to log in with or edit/set their password. I would like to see it be possible to disable the password field entirely to avoid confusing users and having them accidentally enter their IdP password into Errbit. This would pose a bootstrapping problem, though, so it would probably be necessary to have a link (perhaps just a JS-enabled link) that can show the password field for the initial non-SAML admin login.

Perhaps since there's already a Rake task for bootstrapping the first admin user, there could be a way to bootstrap an initial SAML admin user and allow only SAML logins.

> Would Errbit support SP-initiated login or just IdP-initiated log in?

I was thinking of SP-initiated logins, but I don't see why IdP-initiated logins wouldn't also work. Recent versions of `omniauth-saml` even provide a SAML metadata URL to make this easier.

> Do we care about logouts?

I think that logouts would just log out of Errbit. I haven't had to configure single-logout, so I'm not sure whether `omniauth` or `omniauth-saml` support it. A quick scan of the docs for `omniauth-saml` didn't mention it.

> By the way, which IdP are you using?

I'm integrating with PingFederate.

**Comment by stevecrozz** [comment]
These answers all make sense to me. For something like this, I'd encourage something like the README-driven approach http://tom.preston-werner.com/2010/08/23/readme-driven-development.html

It sounds like you've got a good handle on how to make this happen, but I'm available to answer questions and discuss the implementation if needed.

**Comment by stevecrozz** [comment]
@md5 Is this something you're working on now?

**Comment by md5** [comment]
We've been getting along OK with the GitHub Enterprise-based login, so I haven't been motivated to prioritize this work.

Aside from my relative satisfaction with using GHE for logins and competing priorities, I've also realized since I opened this issue that `omniauth-saml` is not being actively maintained. I've been watching that repo since about the time I opened this issue and there are quite a few outstanding PRs and issues that have had little or no input from the repository owners. Some of these issues, in particular the ones addressed by https://github.com/PracticallyGreen/omniauth-saml/pull/50 and https://github.com/PracticallyGreen/omniauth-saml/pull/51, have the effect of limiting the interoperability of systems using `omniauth-saml` with the actual SAML identity providers that exist in the wild. For this reason, I expect that getting a solid, interoperable SAML-based login solution for Errbit is something that still has to wait.

**Comment by MarkusHarmsen** [comment]
@md5 I made a (very basic) SAML authentication implementation (see #1192). Do you still see any issues using the `omniauth-saml` gem? I do see your point regarding an interoperable SAML-based login solution, but at least it worked fine for the GSuite.
