### ISSUE TITLE
Setting GITHUB_URL to a GitHub Enterprise URL doesn't work for logins

### ISSUE THREAD

**Issue by md5** [errbit/errbit#957]
I tried setting `GITHUB_URL` to our internal GitHub Enterprise instance in my `.env` file and I was still redirected to `github.com` when I attempted to log in via GitHub.

Looking at `config/initializers/devise.rb`, it looks like there isn't any code to set `client_options` correctly as indicated here: https://github.com/intridea/omniauth-github#github-enterprise-usage

```ruby
provider :github, ENV['GITHUB_KEY'], ENV['GITHUB_SECRET'],
    {
      :client_options => {
        :site => 'https://github.YOURDOMAIN.com/api/v3',
        :authorize_url => 'https://github.YOURDOMAIN.com/login/oauth/authorize',
        :token_url => 'https://github.YOURDOMAIN.com/login/oauth/access_token',
      }
    }
```

Has anyone successfully used a GitHub Enterprise server for Errbit logins? I can provide a patch if this isn't just user error on my part.

**Comment by md5** [comment]
I've started writing some code for this here: https://github.com/appropriate/errbit/tree/github-enterprise-login

It still needs to set `api_endpoint` on `Octokit::Client` when needed. I can also update the `CHANGELOG.md` and add specs if desired.

**Comment by stevecrozz** [comment]
@md5 That looks great! All it needs is a spec and a PR and I'll merge it in. Here's a quick example of another initializer test if it helps: https://github.com/errbit/errbit/blob/v0.4.0/spec/initializers/action_mailer_spec.rb
