### ISSUE TITLE
local .env file in development can wreak havoc on specs

### ISSUE THREAD

**Issue by stevecrozz** [errbit/errbit#959]
Any values in a local .env file affect the specs when I think they should not. In CI, there is no .env file. A developer should be able to set inputs in a local .env file without affecting the specs.

**Comment by md5** [comment]
Maybe something mocking `Dotenv::Environment.new('.env')` with something like this would work: https://relishapp.com/rspec/rspec-mocks/docs/configuring-responses/calling-the-original-implementation#`and-call-original`-can-configure-a-default-response-that-can-be-overriden-for-specific-args

**Comment by md5** [comment]
Per perhaps somehow mocking the `Dotenv.load` call that happens here to ignore the `.env` argument: https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/rails.rb#L27-L30

**Comment by stevecrozz** [comment]
I'm thinking it might be a good idea for developers to put their own configuration in a separate file, like .env.development or .env.local. This would be a gitignored file with lower precedence than .env, but if we document that it should give developers a way to set inputs that don't apply to the specs. Any thoughts?

**Comment by md5** [comment]
`dotenv` loads both of those filenames by default, but the idea seems reasonable.

I'm thinking this may be worth a feature request to `dotenv`, since this is probably a more general problem.

**Comment by md5** [comment]
Actually, I guess that telling developers to use `.env.development` would be fine since `.env.test` would be loaded for specs. Using `.env.local` would get loaded for all environments.

**Comment by md5** [comment]
I actually tried renaming my local `.env` to `.env.development` today and I was still seeing failures with `rake spec`. I had to run it as `RAILS_ENV=test rake spec` (after renaming the file) to avoid this issue. I'm not sure why that's the case, since the `spec/spec_helper.rb` sets `ENV['RAILS_ENV'] = 'test'` before `config/environment.rb` is loaded.

**Comment by stevecrozz** [comment]
@md5 What do you think about switching to the full-on dotenv-rails approach which is defined here: https://github.com/bkeepers/dotenv/blob/v2.0.2/lib/dotenv/rails.rb#L27-L31

Under this scenario I propose we check in a .env file which has sensible defaults, a .env.development file which has sensible default overrides for development and the same goes for a .env.test file. Finally we .gitignore the .env.local file which would override everything if you have it.

**Comment by md5** [comment]
A local `.env.local` file will have the same effect on running the specs as a local `.env` file. If I'm a developer who has used `.env.local` to customize how my server runs under `rails s`, then there's a high potential to break the specs, since `.env.local` overrides all other environment sources except `ENV`.

**Comment by stevecrozz** [comment]
This is true. Maybe we should get into some specifics so I can understand what you're doing. What is different between your test and development environments that you're overriding?

**Comment by md5** [comment]
At the time I ran into this failure, I was implementing the GitHub Enterprise login support in #958 and had the `GITHUB_*` variables configured for that purpose. This broke the tests. I have since removed my local `.env` to avoid this issue since I don't need to test GitHub Enterprise changes any more, but this seems like it's an easy thing to have problems with.

I think the settings in `.env.default` are generally fine for local development. Moving them to `.env` would probably be fine, assuming the docs were updated to tell people to use `.env.production` for production deployments (though this wouldn't help those already using `.env` for their deployments).

I also think that having developers customize a `gitignore`'d `.env.development` is a reasonable idea, though I don't understand why a plain `rake spec` is still loading `.env.development` instead of `.env.test`.

**Comment by stevecrozz** [comment]
@md5 I can't even find how .env.development would load at all. Do you happen to have a branch where this was happening?

**Comment by stevecrozz** [comment]
I just found it, right after that comment. I typically run the specs with the rspec binary (bundle exec rspec), but you're running them with rake spec and it looks like Dotenv has some magic to auto-load during rake tasks. And that's potentially another source of trouble (loading the environment in two different ways). That's probably a good reason to unify the approach and use the dotenv-rails defaults so there's no conflict.

**Comment by stevecrozz** [comment]
Here's what I've got to make sure the rake environment can't differ from the other environments:
https://github.com/errbit/errbit/compare/master...stevecrozz:959_standard_dotenv_loading

This should allow developers to put stuff in .env, .env.local, .env.development and .env.test however it makes sense and still have the defaults.

**Comment by md5** [comment]
I just checked out your branch and did `rake db:drop` and `RAILS_ENV=test rake db:drop`. My `.env.development` looks like this:

```shell
GITHUB_URL=https://github.example.com
```

I'm still seeing the following failures:

```
$ rake spec
/usr/local/var/rbenv/versions/2.2.3/bin/ruby -I/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib:/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Randomized with seed 395
....................................................................................................................................................F..............F..........F.F.F.................................................................................................F........................***.............................................................................................................................................................................................................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) UsersController Signed in as an admin #user_params with current user admin have admin field
     # Not yet implemented
     # ./spec/controllers/users_controller_spec.rb:246

  2) UsersController Signed in as an admin #user_params with current user admin with password and password_confirmation empty? not have password and password_confirmation field
     # Not yet implemented
     # ./spec/controllers/users_controller_spec.rb:248

  3) UsersController Signed in as an admin #user_params with current user admin on his own user not have admin field
     # Not yet implemented
     # ./spec/controllers/users_controller_spec.rb:251


Failures:

  1) BacktraceLineDecorator#link_to_source_file adds a link to the source file
     Failure/Error: expect(link).to eq(
       
       expected: "<a target=\"_blank\" href=\"https://github.com/foo/bar/blob/master/path/to/file/ea315ea4.rb#L884\">mytext</a>"
            got: "<a target=\"_blank\" href=\"https://github.example.com/foo/bar/blob/master/path/to/file/ea315ea4.rb#L884\">mytext</a>"
       
       (compared using ==)
     # ./spec/decorators/backtrace_line_decorator_spec.rb:25:in `block (3 levels) in <top (required)>'

  2) App#github_url_to_file resolves to full path to file
     Failure/Error: expect(app.github_url_to_file('path/to/file')).to eq "https://github.com/errbit/errbit/blob/master/path/to/file"
       
       expected: "https://github.com/errbit/errbit/blob/master/path/to/file"
            got: "https://github.example.com/errbit/errbit/blob/master/path/to/file"
       
       (compared using ==)
     # ./spec/models/app_spec.rb:105:in `block (3 levels) in <top (required)>'

  3) App being created normalizes public git repo as a github repo
     Failure/Error: expect(app.github_repo).to eq "errbit/errbit"
       
       expected: "errbit/errbit"
            got: "https://github.com/errbit/errbit"
       
       (compared using ==)
     # ./spec/models/app_spec.rb:92:in `block (3 levels) in <top (required)>'

  4) App being created removes domain from https github repos
     Failure/Error: expect(app.github_repo).to eq "errbit/errbit"
       
       expected: "errbit/errbit"
            got: "https://github.com/errbit/errbit"
       
       (compared using ==)
     # ./spec/models/app_spec.rb:86:in `block (3 levels) in <top (required)>'

  5) App being created normalizes private git repo as a github repo
     Failure/Error: expect(app.github_repo).to eq "errbit/errbit"
       
       expected: "errbit/errbit"
            got: "git@github.com:errbit/errbit"
       
       (compared using ==)
     # ./spec/models/app_spec.rb:98:in `block (3 levels) in <top (required)>'

  6) initializers/devise omniauth github sets the client options correctly for the default github_url
     Failure/Error: expect(options[:client_options]).to eq(
       
       expected: {:site=>"https://api.github.com", :authorize_url=>"https://github.com/login/oauth/authorize", :token_url=>"https://github.com/login/oauth/access_token"}
            got: {:site=>"https://api.github.com", :authorize_url=>"https://github.example.com/login/oauth/authorize", :token_url=>"https://github.example.com/login/oauth/access_token"}
       
       (compared using ==)
       
       Diff:
       
       @@ -1,4 +1,4 @@
       -:authorize_url => "https://github.com/login/oauth/authorize",
       +:authorize_url => "https://github.example.com/login/oauth/authorize",
        :site => "https://api.github.com",
       -:token_url => "https://github.com/login/oauth/access_token",
       +:token_url => "https://github.example.com/login/oauth/access_token",
       
     # ./spec/initializers/devise_spec.rb:17:in `block (3 levels) in <top (required)>'

Finished in 33.86 seconds (files took 3.47 seconds to load)
573 examples, 6 failures, 3 pending

Failed examples:

rspec ./spec/decorators/backtrace_line_decorator_spec.rb:23 # BacktraceLineDecorator#link_to_source_file adds a link to the source file
rspec ./spec/models/app_spec.rb:103 # App#github_url_to_file resolves to full path to file
rspec ./spec/models/app_spec.rb:89 # App being created normalizes public git repo as a github repo
rspec ./spec/models/app_spec.rb:83 # App being created removes domain from https github repos
rspec ./spec/models/app_spec.rb:95 # App being created normalizes private git repo as a github repo
rspec ./spec/initializers/devise_spec.rb:12 # initializers/devise omniauth github sets the client options correctly for the default github_url

Randomized with seed 395

/usr/local/var/rbenv/versions/2.2.3/bin/ruby -I/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib:/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by md5** [comment]
Just to be clear, all the tests pass with `RAILS_ENV=test rake spec`. I don't yet understand why this is happening either. I would have thought the setting of `ENV['RAILS_ENV']` on the first line of `spec_helper.rb` would make things work correct since `config/load.rb` gets loaded transitively a few lines lower when `config/environment` is loaded.

**Comment by stevecrozz** [comment]
This is because Dotenv automatically loads itself without being asked simply because you invoked it via rake. By the time we set RAILS_ENV=test in spec_helper.rb, its too late and we've already loaded inputs through Dotenv's internal magic. And now if you run specs the way I normally do, the behavior will be the same.

I'm not sure what to do about this actually other than instruct users to prepend RAILS_ENV=test.

**Comment by stevecrozz** [comment]
Here's another idea. I've removed the 'spec' rake task which would force the rspec entry point (rspec instead of rake spec).

**Comment by md5** [comment]
I don't think removing the default `spec` task is a good idea. My experience with all the Rails apps I've worked with is that running `rake` by itself should run the tests/specs.

Since the `rake spec` task shells out to `rspec`, I'm don't really understand why this doesn't work. It looks like `rake spec:prepare` even explicitly sets `RAILS_ENV=test` here: https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/tasks/rspec.rake#L23

I'm going to spend a bit of time looking into this and I'll report back.

**Comment by md5** [comment]
I figured out the issue.

When `rake` is run, the `Rakefile` loads `config/application.rb`, which initializes `Dotenv` under the current environment (i.e. `development`). The `rake spec` task then shells out to `rspec`, which runs under `RAILS_ENV=test`, but the environment has already been populated with the values from `.env.development`.

**Comment by md5** [comment]
Now that I understand what to look for, I found the issue reported in the `bkeepers/dotenv` repo: https://github.com/bkeepers/dotenv/issues/219

**Comment by md5** [comment]
See these also https://github.com/bkeepers/dotenv/issues/45 and https://github.com/bkeepers/dotenv/pull/159

**Comment by stevecrozz** [comment]
It's inconvenient that Rails wants me to have a Rakefile that loads my whole Rails application for all Rake tasks before I get a chance to initialize the environment. Because what we're saying is the environment configuration depends on the entry point. If you invoke rake spec, you want that to initialize a different environment than if you invoke rake db:migrate.

That's fair, but there aren't a lot of options here. We need to set RAILS_ENV before loading the Rails application, so it must either be done either on the CLI with RAILS_ENV=test rake spec or at the top of the Rakefile with something like. This is pretty ugly, but it could work:
```ruby
if File.basename($0) == 'rake' && (ARGV.first.empty? || ARGV.first == 'spec')
  ENV['RAILS_ENV'] = 'test'
end
```

One final thought I have is that I don't see the need for two separate entrypoints for test running. The rspec binary is the entrypoint we care about most because its the one we use in CI. But I do see your point that some people may be used to 'rake' or 'rake spec'. Although by default there is no 'rake spec' command on a new, default rails app, I think there is a default 'rake' command that runs tests. We could replace the 'rake spec' and 'rake' commands with a pointer to rspec that halts the program and prints a line directing you to run 'rspec' instead.

Does any of this sound like a good idea to you @md5?

**Comment by stevecrozz** [comment]
I had another idea just now and this seems very easy. I'm planning to write a documentation section on Errbit development / specs. Maybe the right thing to do is nothing, and instead expect test authors to prepare configuration stubs in their tests that require special values. This is easily done in RSpec with:
```ruby
allow(Errbit::Config).to receive(:foo).and_return('bar')
```

**Comment by md5** [comment]
Barring a fix in `dotenv`, I think replacing `rake spec` with an informative warning and having `rake` still have `spec` as the default task is fine.

**Comment by md5** [comment]
The only alternative I can think of is to have a pre-requisite task for `spec` that clears `ENV`. That assumes that developers should not be setting external `ENV` variables to affect tests, which is probably reasonable since they can use `.env.test`.

**Comment by md5** [comment]
(or `.env.local`)

**Comment by md5** [comment]
I also think the configuration stub is a good idea, though I'm not sure how much of a developer burden it will add.

**Comment by md5** [comment]
Perhaps stubbing it by default to only return the values from `.env.default` would mitigate that.

**Comment by md5** [comment]
Clearing the `ENV` seems to work great. See https://github.com/appropriate/errbit/commit/9dec3e2be57261a8a13827baa3c3ff5b39f8178e

**Comment by stevecrozz** [comment]
Its a neat idea, but it would keep us from using regular environment variables as only the values in the dotenv files would have an effect.

But I think I may have a winner: https://github.com/errbit/errbit/pull/1028

I think this does exactly what we want. We can keep a list here of 'special' rake tasks that should always be run in the test environment. As long as we set the environment name to test before loading the rails application, dotenv shouldn't give us any trouble by loading the wrong files. Seem reasonable?

**Comment by stevecrozz** [comment]
I think this is resolved. Thanks for all the help in figuring out how to handle this.
