### ISSUE TITLE
Response on succesfull error creation should have 201 status

### ISSUE THREAD

**Issue by gsalgado** [errbit/errbit#967]
Airbrake seems to reply with a 201 status when new errors are added, but errbit (HEAD) replies with 200, thus causing an error on gobrake: https://github.com/airbrake/gobrake/blob/master/notifier.go#L138

**Comment by stevecrozz** [comment]
Thanks for the report, I'm calling this a bug and will prioritize this.

**Comment by stevecrozz** [comment]
@gsalgado Fixed in master
