### ISSUE TITLE
cross domain javascript error reporting not working (airbrake-js)

### ISSUE THREAD

**Issue by stevecrozz** [errbit/errbit#970]
It looks like we lost the Access-Control-Allow-Origin header along with:
https://github.com/errbit/errbit/commit/6a233224beeb6f7882f488cbfc41a2858f8f00bb

This will need to be restored in order to use airbrake-js

**Comment by xdmx** [comment]
I'm still experiencing this issue.
I've installed the last version of errbit (06569f9d9215370a8964bfbb4848611249bb0309) and I'm using it with [airbrake js 0.3.12](https://ssljscdn.airbrake.io/0.3/airbrake.min.js)
This is from the console:

```
Airbrake.push({error: {message: "test"}})

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://domain.com/api/v3/projects/5218d664818a00ee7e6bf49fd1b0797a/notices?key=5219df3a6bc1f0ee7e6bbe642560797a. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
```

From the rails log it appears to be missing the OPTIONS route:
```
ActionController::RoutingError (No route matches [OPTIONS]
```

**Comment by stevecrozz** [comment]
Hi @xdmx . Your version of airbrake-js is too old. As of https://github.com/airbrake/airbrake-js/pull/143 (v0.4.3), airbrake-js no longer sends the preflight (OPTIONS) request. This should not be a problem once you upgrade airbrake-js. The most recent version is v0.5.3.

**Comment by xdmx** [comment]
You're right. I've upgraded to the last version and errors are correctly sent. Thank you for your hard work on errbit :smile:  :beers:
