### ISSUE TITLE
App Search by name

### ISSUE THREAD

**Issue by lucianosousa** [errbit/errbit#975]
As I mentioned in another issues, it's quite hard to find app infos when you have a lot of them.

I'm thinking about a search by name feature.
What you guys think about it?

**Comment by stevecrozz** [comment]
@lucianosousa how many apps do you have?

**Comment by lucianosousa** [comment]
more than 40 registered.
few are the same but with different envs(acceptance, production)

**Comment by stevecrozz** [comment]
It sounds like that's small enough to do a nice little typeahead client-side search. Something to consider I think as long as people don't tend to have hundreds or thousands of apps.

**Comment by lucianosousa** [comment]
Will you reject my PR if I build it? :)

**Comment by stevecrozz** [comment]
I would pull it in as long as the implementation is simple and has a test or two to make sure it doesn't break.

**Comment by nielspetersen** [comment]
We've included this issue in the current issue (13th) of the RubyIssues: https://rubyissues.ongoodbits.com/. :gem:

**Comment by scicco** [comment]
Hi guys, this is my PR for this, let me know if it's ok.
Thank you in advance for your work!

#1150
