### ISSUE TITLE
How to configure Errbit to fix "Errbit Timeout::Error: Waited 0.5 sec"

### ISSUE THREAD

**Issue by taelor** [errbit/errbit#978]
Does anyone have any suggestions on how to configure errbit to avoid this error? I'm not sure what exactly the problem is, but I have a feeling it might be our Mongo configuration. I'm not too familiar with Mongo, so I'm not sure what I would need to change to help avoid this issue.

Is there some sort of connection pool that I might need to turn up on Mongo? 

```
connection_pool-2.1.1/lib/connection_pool/timed_stack.rb:85→ block (2 levels) in pop
connection_pool-2.1.1/lib/connection_pool/timed_stack.rb:77→ loop
connection_pool-2.1.1/lib/connection_pool/timed_stack.rb:77→ block in pop
connection_pool-2.1.1/lib/connection_pool/timed_stack.rb:76→ synchronize
...
mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:198→ block in first
mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:457→ try_cache
mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:197→ first
mongoid-4.0.2/lib/mongoid/contextual.rb:20→ first
app/models/error_report.rb:39→ app
app/models/error_report.rb:78→ valid?
app/controllers/notices_controller.rb:13→ create
actionpack-4.1.8/lib/action_controller/metal/implicit_render.rb:4→ send_action
actionpack-4.1.8/lib/abstract_controller/base.rb:189→ process_action
actionpack-4.1.8/lib/action_controller/metal/rendering.rb:10→ process_action
actionpack-4.1.8/lib/abstract_controller/callbacks.rb:20→ block in process_action
...
puma-2.11.2/lib/puma/server.rb:375→ process_client
puma-2.11.2/lib/puma/server.rb:262→ block in run
puma-2.11.2/lib/puma/thread_pool.rb:104→ call
puma-2.11.2/lib/puma/thread_pool.rb:104→ block in spawn_thread
```

**Comment by stevecrozz** [comment]
@taelor are you using the google talk / jabber / xmpp notifier?

**Comment by taelor** [comment]
No, not using either of those. It also seems like its happening before the error is getting created/logged.

**Comment by stevecrozz** [comment]
@taelor You may be running out of connections in your connection pool. Most errbit users likely use a single-threaded, multiple-process unicorn server and that's the way we have documented the capistrano and heroku deployment scenarios.

If you're wanting to just get past this, I'd suggest adopting that model. On the other hand, if you're wanting to help forge the path ahead, let's keep this issue open and start digging in. Just be aware that you're not on a well-traveled path.

According to the mongoid docs, the default maximum connection pool size is 5. Have you configured to run your puma with more than 5 threads? If so, that could be one explanation...

**Comment by stevecrozz** [comment]
Did you get anywhere on this issue @taelor? Do you want to talk it over on gitter or on the mailing list?

**Comment by taelor** [comment]
Sorry @stevecrozz, I got side tracked by a bunch of end-of-the-year projects and we threw it on the back burner.

My co-worker @penguincoder is going to take a look at this, and either upgrade our errbit deploy to use the fix in the referenced issue, or re-deploy it with unicorn. 

We'll update our progress soon and will probably be able to close this ticket. Thanks.

**Comment by penguincoder** [comment]
I updated errbit to 79a0f0a and so far it seems to be working a lot better. I will report back in a day or so with my results. I need to generate a bit of traffic to errbit, because if the issue was being run in a threaded environment when it was not threadsafe, there needs to be some traffic to validate the results.

Thanks for everyone's help in the matter.

**Comment by penguincoder** [comment]
Our timeout issue appears to be resolved, thanks for everyone's input.
