### ISSUE TITLE
Password reset broken

### ISSUE THREAD

**Issue by robinboening** [errbit/errbit#981]
Hey there,

Situation: (Errbit v0.5.0) I request a new password and click on the link from the mail to set a new password. Then I type a new password and submit the form. 

Issue: I receive an error telling me I need to provide a username.

Expected behavior: After submitting the form with the new password, it should be set (without the need of a username).

<img width="679" alt="errbit_password-reset" src="https://cloud.githubusercontent.com/assets/342977/10607548/858efd32-773a-11e5-9316-db6a3a72338d.png">

**Comment by stevecrozz** [comment]
It seems that you are running errbit with ERRBIT_USER_HAS_USERNAME=true, but your user does not have a username. When this flag is enabled, it means users without usernames are invalid. What's interesting about this is you shouldn't be able to have a user in this state unless you were formerly running with ERRBIT_USER_HAS_USERNAME=false and enabled it later. Is that what's going on?

**Comment by stevecrozz** [comment]
My plan is to disable all validations other than password validations when doing a password reset. This should be safe enough since only the password can be updated during a password reset.

**Comment by yannvery** [comment]
Do you need a PR for this one ?

**Comment by stevecrozz** [comment]
@yannvery that would be great
