### ISSUE TITLE
Email says "This error has occured 0 times" for the first occurance

### ISSUE THREAD

**Issue by funglaub** [errbit/errbit#982]
If you enable email notifications, the email says "This error occured 0 times" for the first exception that errbit catches.

Shouldn't that be "1 times"?

**Comment by stevecrozz** [comment]
Yeah zero must be wrong. It sounds like a bug.

**Comment by stevecrozz** [comment]
@funglaub Are you still seeing this issue? I went to track it down today, but I'm no longer seeing it.

**Comment by stevecrozz** [comment]
I'm closing this because I cannot reproduce it. I think its been fixed since this issue first came up.
