### ISSUE TITLE
Custom fingerprints are ignored when a new error is created

### ISSUE THREAD

**Issue by xdmx** [errbit/errbit#984]
I've upgraded to the current master and the last airbrake-js, but the custom fingerprints don't seem to work correctly. After the upgrade I ran rake errbit:notice_refingerprint and also after each time I enabled/disabled each options in the config, but the errors weren't splitted/merged as expected.

The only thing that changes in errors it's the backtrace.. but it shouldn't use it since I've set to use 0 lines. Even playing with options and running the rake task each time doesn't change anything

![1](https://cloud.githubusercontent.com/assets/115298/10633548/4f73b07c-77e3-11e5-960b-a5f9bdefbdbe.png)

![2](https://cloud.githubusercontent.com/assets/115298/10633551/565d5f1e-77e3-11e5-8514-9484cec81252.png)

**Comment by stevecrozz** [comment]
@xdmx The spec only proves it works for varying backtraces: https://github.com/errbit/errbit/blob/master/spec/interactors/notice_refingerprinter_spec.rb

Do you want to try to add your case here? It would be awesome if you could take two of your actual notices and write a spec that shows how the notice refingerprinter is not working the way you expect.

**Comment by stevecrozz** [comment]
actually, it might be easier to implement specs here https://github.com/errbit/errbit/blob/5639825eace4f18839a5b3279f4223060def471a/spec/models/notice_fingerprinter_spec.rb

**Comment by xdmx** [comment]
Hi Stephen, I'm not sure how I should add it, maybe editing the fabricator? Or adding directly the text in that spec?
Anyway, taking the current errors, two are the same but not merged (the backtrace config in the fingerprint is disabled), this is the common data:
```
Message 	
100.0% 	TypeError: b is undefined
Error Class 	
URL 	https://domain.com/admin/192/edit
  	curl -X GET -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.5; rv:13.0) Gecko/20100101 Firefox/13.0.1' https://domain.com/admin/192/edit
Where 	
Occurred 	Oct 26 14:57:35
Similar 	3
Browser 	
100.0% 	Firefox 13.0.1 (OS X 10.5)
Tenant 	
100.0% 	domain.com
App Server 	domain.com
Rel. Directory 	https://domain.com
```

And this the first backtrace:
```
https://assets.domain.com/assets/common-ed56596ebc471ab6ec6c971483eb8175cd1b911b6c30a597766509d3c28bc1c7.js:28311:0→ ((function () {"use strict";b.resolve();}))
https://assets.domain.com/assets/common-ed56596ebc471ab6ec6c971483eb8175cd1b911b6c30a597766509d3c28bc1c7.js:28299:0→ ()
https://assets.domain.com/assets/common-ed56596ebc471ab6ec6c971483eb8175cd1b911b6c30a597766509d3c28bc1c7.js:16276:0→ ()
https://assets.domain.com/assets/common-ed56596ebc471ab6ec6c971483eb8175cd1b911b6c30a597766509d3c28bc1c7.js:16489:0→ ()
https://assets.domain.com/assets/common-ed56596ebc471ab6ec6c971483eb8175cd1b911b6c30a597766509d3c28bc1c7.js:34326:0→ ([object Object])
https://assets.domain.com/assets/common-ed56596ebc471ab6ec6c971483eb8175cd1b911b6c30a597766509d3c28bc1c7.js:1:0→ ([object Object])
https://assets.domain.com/assets/common-ed56596ebc471ab6ec6c971483eb8175cd1b911b6c30a597766509d3c28bc1c7.js:1:0→ ([object Event])
```

And here the second:
```
https://assets.domain.com/assets/common-ed56596ebc471ab6ec6c971483eb8175cd1b911b6c30a597766509d3c28bc1c7.js:28311:0→ ((function () {"use strict";b.resolve();}))
https://assets.domain.com/assets/common-ed56596ebc471ab6ec6c971483eb8175cd1b911b6c30a597766509d3c28bc1c7.js:28299:0→ ()
https://assets.domain.com/assets/common-ed56596ebc471ab6ec6c971483eb8175cd1b911b6c30a597766509d3c28bc1c7.js:16276:0→ ()
https://assets.domain.com/assets/common-ed56596ebc471ab6ec6c971483eb8175cd1b911b6c30a597766509d3c28bc1c7.js:16489:0→ ()
https://assets.domain.com/assets/common-ed56596ebc471ab6ec6c971483eb8175cd1b911b6c30a597766509d3c28bc1c7.js:11563:0→ done(200,"{}","Server: cloudflare-nginx\nDate: Mon, 26 Oct 2015 13:57:20 GMT\nContent-Type: application/json; charset=utf-8\nTransfer-Encoding: chunked\nConnection: keep-alive\nStatus: 200 OK\nX-Frame-Options: SAMEORIGIN\nX-XSS-Protection: 1; mode=block\nX-Content-Type-Options: nosniff\nEtag: W/\"057d01b4e8f955beb2b557456e5e0abb\"\nCache-Control: max-age=0, private, must-revalidate\nStrict-Transport-Security: max-age=31536000\nX-Request-Id: ea5f57e4-40a1-47c2-b220-a6ba5091a83e\nX-Runtime: 0.033329\nAccess-Control-Allow-Origin: *\nAccess-Control-Allow-Methods: GET\nCF-RAY: 23b6ab7239b22f6b-MAD\nContent-Encoding: gzip\n","OK")
https://assets.domain.com/assets/common-ed56596ebc471ab6ec6c971483eb8175cd1b911b6c30a597766509d3c28bc1c7.js:11753:0→ completeRequest(done,200,"{}","Server: cloudflare-nginx\nDate: Mon, 26 Oct 2015 13:57:20 GMT\nContent-Type: application/json; charset=utf-8\nTransfer-Encoding: chunked\nConnection: keep-alive\nStatus: 200 OK\nX-Frame-Options: SAMEORIGIN\nX-XSS-Protection: 1; mode=block\nX-Content-Type-Options: nosniff\nEtag: W/\"057d01b4e8f955beb2b557456e5e0abb\"\nCache-Control: max-age=0, private, must-revalidate\nStrict-Transport-Security: max-age=31536000\nX-Request-Id: ea5f57e4-40a1-47c2-b220-a6ba5091a83e\nX-Runtime: 0.033329\nAccess-Control-Allow-Origin: *\nAccess-Control-Allow-Methods: GET\nCF-RAY: 23b6ab7239b22f6b-MAD\nContent-Encoding: gzip\n","OK")
https://assets.domain.com/assets/common-ed56596ebc471ab6ec6c971483eb8175cd1b911b6c30a597766509d3c28bc1c7.js:11698:0→ requestLoaded([object ProgressEvent])
```

**Comment by stevecrozz** [comment]
I would like to get this straightened out before releasing v0.5.0. I'll see if I can reproduce the problem with the information you provided. If you can provide a dump of your notices table, that could be helpful too.

**Comment by stevecrozz** [comment]
@xdmx: this test supposedly proves this works: https://github.com/errbit/errbit/blob/master/spec/models/notice_fingerprinter_spec.rb#L13-L24

Can you tell what's wrong by plugging your data into this test? Even if you just hack it all up to illustrate your the problem you're seeing that would be super helpful.

**Comment by xdmx** [comment]
I haven't tried to put my data, but simply changing the [one testing the backtrace](https://github.com/errbit/errbit/blob/master/spec/models/notice_fingerprinter_spec.rb#L26) with the follow:

```
    it 'affects the fingerprint with different backtrace_lines config' do
      f1 = fingerprinter.generate('123', notice, backtrace)
      f2 = fingerprinter.generate('123', notice, backtrace)

      fingerprinter.backtrace_lines = 1
      f3 = fingerprinter.generate('123', notice, Fabricate(:backtrace))

      fingerprinter.backtrace_lines = 0
      f4 = fingerprinter.generate('123', notice, Fabricate(:backtrace))

      expect(f1).to eq(f2)
      expect(f1).to_not eq(f3)
      expect(f1).to eq(f4)
    end
```

f1 and f2 have the same notice and backtrace, so the fingerprint is expected to be the same

f1 and f3 have 2 completely different backtraces, and the config is set to consider the first line, so it's correct that the fingerprint is different

The bug is with f1 and f4, the backtraces are different, but the config option is set to 0 lines, so the fingerprint should be the same since the notice is the same

This may be the reason why after the rake task notices weren't merged

Checking through the existing notices (I cannot share the dump unfortunately :disappointed: ) I've also notices 3 separated notices which are exactly the same, also the backtrace, 2 of them have even the same creation datetime, and the other is 1 second later.. my guess would be that the client sent various notices at the same time and errbit created different notices (some kind of race condition)

**Comment by xdmx** [comment]
My bad, it seems that the backtrace_lines is used to generate the fingerprint as well, trying with:
```
      f1 = fingerprinter.generate('123', notice, backtrace)
      f2 = fingerprinter.generate('123', notice, backtrace)

      fingerprinter.backtrace_lines = 2
      f3 = fingerprinter.generate('123', notice, backtrace)
      f4 = fingerprinter.generate('123', notice, backtrace)

      fingerprinter.backtrace_lines = 1
      f5 = fingerprinter.generate('123', notice, Fabricate(:backtrace))
      f6 = fingerprinter.generate('123', notice, Fabricate(:backtrace))

      fingerprinter.backtrace_lines = 0
      f7 = fingerprinter.generate('123', notice, Fabricate(:backtrace))
      f8 = fingerprinter.generate('123', notice, Fabricate(:backtrace))
```

it seems that it generated the correct fingerprints (f1=f2, f3=f4, f5!=f6, f7=f8). I'm not sure how I can replicate what it happens on the deployed version.

Could it be because I upgraded from 0.4 (even though I've followed the instructions and regenerated the fingerprints)?

**Comment by stevecrozz** [comment]
I don't think it could be the fault of this upgrade, but if you're in a debugging kind of mood, it would be interesting to see how this ends up doing the wrong thing. You could modify the finder on line 10 here to grab a couple of interesting notices and print the fingerprints to see what's happening:
https://github.com/errbit/errbit/blob/7352a1ce773b04a326c841531fe4b6b338a2cac6/app/interactors/notice_refingerprinter.rb

**Comment by stevecrozz** [comment]
Did you find a way past this issue @xdmx or are you still seeing it?

**Comment by xdmx** [comment]
To be honest I haven't had much time to check it out more, I see that it still duplicates some errors.

In the weekend I'll try to reinstall errbit on a clean install and check if it changes something. Hopefully during the next week I'll have a dump to share :wink:

**Comment by xdmx** [comment]
@stevecrozz I've been able to reinstall errbit, using the master branch, on a clean instance and db and I had it running for a couple of days. Unfortunately I still get this problem.

I've [dumped the db](https://github.com/errbit/errbit/files/53729/errbit.zip) (redacting users' info and removing errors that weren't duplicated) in order for you to be able to see the data and config.

As you can see there are 3 errors, each one of them, even if they're the same, they've been duplicated. 

For example `TypeError: Cannot read property '0' of undefined` the only data to change are the backtrace and the user agent, everything else is the same.

The config has `backtrace lines = 0`, so it shouldn't consider it, and after running `rake errbit:notice_refingerprint`I'd expect them to merge (or even better merge at the creation)

**Comment by stevecrozz** [comment]
Thanks @xdmx. This should be a big help in tracking down the problem.

**Comment by xdmx** [comment]
I've upgraded to master and it seems that now it's fixed. I've just run into a small bug after the deploy

```
$ heroku run rake errbit:notice_refingerprint
Running rake errbit:notice_refingerprint... up, run.7255
Notice: no rspec tasks available in this environment
Overwriting existing field _id in class App.
Creating scope :page. Overwriting existing method NotificationServices::CampfireService.page.
Creating scope :page. Overwriting existing method NotificationServices::FlowdockService.page.
Creating scope :page. Overwriting existing method NotificationServices::GtalkService.page.
Creating scope :page. Overwriting existing method NotificationServices::HipchatService.page.
Creating scope :page. Overwriting existing method NotificationServices::HoiioService.page.
Creating scope :page. Overwriting existing method NotificationServices::HubotService.page.
Creating scope :page. Overwriting existing method NotificationServices::PushoverService.page.
Creating scope :page. Overwriting existing method NotificationServices::SlackService.page.
Creating scope :page. Overwriting existing method NotificationServices::WebhookService.page.
Regenerating notice fingerprints for 830 notices
rake aborted!
NoMethodError: undefined method `generate' for nil:NilClass
/app/app/interactors/notice_refingerprinter.rb:30:in `refingerprint'
/app/app/interactors/notice_refingerprinter.rb:11:in `block in run'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/contextual/mongo.rb:668:in `yield_document'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/contextual/mongo.rb:122:in `block in each'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/collection/view/iterable.rb:45:in `block in each'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/cursor.rb:78:in `block in each'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/cursor.rb:78:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/cursor.rb:78:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/collection/view/iterable.rb:44:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/query_cache.rb:207:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/contextual/mongo.rb:121:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/contextual.rb:20:in `each'
/app/app/interactors/notice_refingerprinter.rb:10:in `each_with_index'
/app/app/interactors/notice_refingerprinter.rb:10:in `run'
/app/lib/tasks/errbit/database.rake:15:in `block (2 levels) in <top (required)>'
Tasks: TOP => errbit:notice_refingerprint
(See full trace by running task with --trace)
```

The fingerprint wasn't generated on apps (even after editing the config and apps), I had to run
```
attrs = SiteConfig.document.notice_fingerprinter_attributes
App.all.each do |app|
  app.notice_fingerprinter = attrs
  app.save
end
```

Then I did the refingerprint and everything worked

I'll give it few more days, if anything comes up I'll let you know, otherwise you can consider this fixed :wink:

**Comment by stevecrozz** [comment]
Great. I just noticed the same issue. I'm trying to decide if I should handle it with a migration (which people may forget to run), or a method to do this whenever an app references its fingerprinter and doesn't have one. I'm thinking that's the better way.

**Comment by stevecrozz** [comment]
I ended up with a commit to create and save a new fingerprinter when accessing a nil one on the app:
https://github.com/errbit/errbit/commit/a8af7b22ca29ff534a2f7a01d33c10135d14b4a1

Hopefully this prevents anyone from running into a blank fingerprinter.
