### ISSUE TITLE
Moped::Errors::AuthenticationFailure in Devise::SessionsController#create

### ISSUE THREAD

**Issue by meliborn** [errbit/errbit#996]
Errbit hosted on Heroku. Version is ```0.3.0.dev```
When I trying to sign in, I getting this:
```
Moped::Errors::AuthenticationFailure in Devise::SessionsController#create

The operation: #<Moped::Protocol::Commands::Authenticate
  @length=174
  @request_id=6
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="heroku_app31601904.$cmd"
  @skip=0
  @limit=-1
  @selector={:authenticate=>1, :user=>"heroku_app31601904", :nonce=>"bd262fcee90e685e", :key=>"50a1556654f629efa1d7261ae952b1e1"}
  @fields=nil>
failed with error 18: "auth failed"

See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error.
```

What's wrong? It works fine before, but I visit my errbit long time ago (2 month approx.)

**Comment by stevecrozz** [comment]
Your mongo may have been recently updated. I think mongolab did this recently for all users.

**Comment by meliborn** [comment]
What does it mean for me? What should I do?

**Comment by stevecrozz** [comment]
If you have recently been upgraded to mongo 3.0, then you may just need to upgrade errbit. Try (after backing up your db), upgrading errbit to the latest version to see if that fixes your issue. Remember to follow along with https://github.com/errbit/errbit#upgrading

**Comment by stevecrozz** [comment]
@meliborn Do you have any updates on this? Are you still seeing an issue?

**Comment by meliborn** [comment]
@stevecrozz No, after upgrade errbit to the last version it works fine. Thx.

**Comment by stevecrozz** [comment]
Excellent
