### ISSUE TITLE
change server support from unicorn to puma

### ISSUE THREAD

**Issue by stevecrozz** [errbit/errbit#999]
Unicorn has been great, but puma has a cleaner API and easier threading support. According to anecdotal evidence from various blog entries I've found, puma has significant performance advantages and is also now [officially recommended over unicorn by heroku](https://devcenter.heroku.com/changelog-items/594).

**Comment by otzy007** [comment]
:+1:

**Comment by stevecrozz** [comment]
Fixed in master
